package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name = "AGENT", schema = "TOM")
public class Agent implements java.io.Serializable {

	private String matricule;
	private Unite unite;
	private String nom;
	private String prenom;
	private String email;
	private String tel;
	private boolean etat;
	private Date DEtat;
	private Set<EquipeRess> equipeResses = new HashSet<EquipeRess>(0);

	public Agent() {
	}

	public Agent(String matricule, Unite unite, String nom, String prenom, boolean etat, Date DEtat) {
		this.matricule = matricule;
		this.unite = unite;
		this.nom = nom;
		this.prenom = prenom;
		this.etat = etat;
		this.DEtat = DEtat;
	}

	public Agent(String matricule, Unite unite, String nom, String prenom, String email, String tel, boolean etat,
			Date DEtat, Set<EquipeRess> equipeResses) {
		this.matricule = matricule;
		this.unite = unite;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.tel = tel;
		this.etat = etat;
		this.DEtat = DEtat;
		this.equipeResses = equipeResses;
	}

	@Id

	@Column(name = "MATRICULE", unique = true, nullable = false, length = 10)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_UNITE", nullable = false)
	public Unite getUnite() {
		return this.unite;
	}

	public void setUnite(Unite unite) {
		this.unite = unite;
	}

	@Column(name = "NOM", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TEL", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "ETAT", nullable = false, precision = 1, scale = 0)
	public boolean isEtat() {
		return this.etat;
	}

	public void setEtat(boolean etat) {
		this.etat = etat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ETAT", nullable = false, length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agent")
	public Set<EquipeRess> getEquipeResses() {
		return this.equipeResses;
	}

	public void setEquipeResses(Set<EquipeRess> equipeResses) {
		this.equipeResses = equipeResses;
	}

}
