package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BillingNatEvent generated by hbm2java
 */
@Entity
@Table(name = "BILLING_NAT_EVENT", schema = "TOM")
public class BillingNatEvent implements java.io.Serializable {

	private BigDecimal idNatEvent;
	private String natEvent;
	private boolean FMotif;
	private Set<BillingParamEvent> billingParamEvents = new HashSet<BillingParamEvent>(0);

	public BillingNatEvent() {
	}

	public BillingNatEvent(BigDecimal idNatEvent, String natEvent, boolean FMotif) {
		this.idNatEvent = idNatEvent;
		this.natEvent = natEvent;
		this.FMotif = FMotif;
	}

	public BillingNatEvent(BigDecimal idNatEvent, String natEvent, boolean FMotif,
			Set<BillingParamEvent> billingParamEvents) {
		this.idNatEvent = idNatEvent;
		this.natEvent = natEvent;
		this.FMotif = FMotif;
		this.billingParamEvents = billingParamEvents;
	}

	@Id

	@Column(name = "ID_NAT_EVENT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdNatEvent() {
		return this.idNatEvent;
	}

	public void setIdNatEvent(BigDecimal idNatEvent) {
		this.idNatEvent = idNatEvent;
	}

	@Column(name = "NAT_EVENT", nullable = false, length = 200)
	public String getNatEvent() {
		return this.natEvent;
	}

	public void setNatEvent(String natEvent) {
		this.natEvent = natEvent;
	}

	@Column(name = "F_MOTIF", nullable = false, precision = 1, scale = 0)
	public boolean isFMotif() {
		return this.FMotif;
	}

	public void setFMotif(boolean FMotif) {
		this.FMotif = FMotif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "billingNatEvent")
	public Set<BillingParamEvent> getBillingParamEvents() {
		return this.billingParamEvents;
	}

	public void setBillingParamEvents(Set<BillingParamEvent> billingParamEvents) {
		this.billingParamEvents = billingParamEvents;
	}

}
