package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillingJms generated by hbm2java
 */
@Entity
@Table(name = "BILLING_JMS", schema = "TOM")
public class BillingJms implements java.io.Serializable {

	private String id;
	private String correlationId;
	private String message;
	private Date dateMsg;
	private String typeMsg;
	private BigDecimal idEvent;
	private BigDecimal etat;

	public BillingJms() {
	}

	public BillingJms(String id) {
		this.id = id;
	}

	public BillingJms(String id, String correlationId, String message, Date dateMsg, String typeMsg, BigDecimal idEvent,
			BigDecimal etat) {
		this.id = id;
		this.correlationId = correlationId;
		this.message = message;
		this.dateMsg = dateMsg;
		this.typeMsg = typeMsg;
		this.idEvent = idEvent;
		this.etat = etat;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CORRELATION_ID", length = 100)
	public String getCorrelationId() {
		return this.correlationId;
	}

	public void setCorrelationId(String correlationId) {
		this.correlationId = correlationId;
	}

	@Column(name = "MESSAGE", length = 1000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_MSG", length = 7)
	public Date getDateMsg() {
		return this.dateMsg;
	}

	public void setDateMsg(Date dateMsg) {
		this.dateMsg = dateMsg;
	}

	@Column(name = "TYPE_MSG", length = 10)
	public String getTypeMsg() {
		return this.typeMsg;
	}

	public void setTypeMsg(String typeMsg) {
		this.typeMsg = typeMsg;
	}

	@Column(name = "ID_EVENT", precision = 22, scale = 0)
	public BigDecimal getIdEvent() {
		return this.idEvent;
	}

	public void setIdEvent(BigDecimal idEvent) {
		this.idEvent = idEvent;
	}

	@Column(name = "ETAT", precision = 22, scale = 0)
	public BigDecimal getEtat() {
		return this.etat;
	}

	public void setEtat(BigDecimal etat) {
		this.etat = etat;
	}

}
