package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillingEventHist generated by hbm2java
 */
@Entity
@Table(name = "BILLING_EVENT_HIST", schema = "TOM")
public class BillingEventHist implements java.io.Serializable {

	private BigDecimal idEvent;
	private Date dateEvent;
	private String codeEvent;
	private String codeOperateur;
	private String codeOperation;
	private String refDem;
	private Date dateDemande;
	private String numLigne;
	private String externalRess;
	private Date dateEnvoi;
	private String debit;
	private Boolean etatEvent;
	private Date dateRetourBscs;
	private String motifRetourBscs;
	private String codeMotifEtat;
	private String libelleMotifEtat;

	public BillingEventHist() {
	}

	public BillingEventHist(BigDecimal idEvent, Date dateEvent, String codeEvent, String codeOperateur) {
		this.idEvent = idEvent;
		this.dateEvent = dateEvent;
		this.codeEvent = codeEvent;
		this.codeOperateur = codeOperateur;
	}

	public BillingEventHist(BigDecimal idEvent, Date dateEvent, String codeEvent, String codeOperateur,
			String codeOperation, String refDem, Date dateDemande, String numLigne, String externalRess, Date dateEnvoi,
			String debit, Boolean etatEvent, Date dateRetourBscs, String motifRetourBscs, String codeMotifEtat,
			String libelleMotifEtat) {
		this.idEvent = idEvent;
		this.dateEvent = dateEvent;
		this.codeEvent = codeEvent;
		this.codeOperateur = codeOperateur;
		this.codeOperation = codeOperation;
		this.refDem = refDem;
		this.dateDemande = dateDemande;
		this.numLigne = numLigne;
		this.externalRess = externalRess;
		this.dateEnvoi = dateEnvoi;
		this.debit = debit;
		this.etatEvent = etatEvent;
		this.dateRetourBscs = dateRetourBscs;
		this.motifRetourBscs = motifRetourBscs;
		this.codeMotifEtat = codeMotifEtat;
		this.libelleMotifEtat = libelleMotifEtat;
	}

	@Id

	@Column(name = "ID_EVENT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdEvent() {
		return this.idEvent;
	}

	public void setIdEvent(BigDecimal idEvent) {
		this.idEvent = idEvent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_EVENT", nullable = false, length = 7)
	public Date getDateEvent() {
		return this.dateEvent;
	}

	public void setDateEvent(Date dateEvent) {
		this.dateEvent = dateEvent;
	}

	@Column(name = "CODE_EVENT", nullable = false, length = 50)
	public String getCodeEvent() {
		return this.codeEvent;
	}

	public void setCodeEvent(String codeEvent) {
		this.codeEvent = codeEvent;
	}

	@Column(name = "CODE_OPERATEUR", nullable = false, length = 100)
	public String getCodeOperateur() {
		return this.codeOperateur;
	}

	public void setCodeOperateur(String codeOperateur) {
		this.codeOperateur = codeOperateur;
	}

	@Column(name = "CODE_OPERATION", length = 100)
	public String getCodeOperation() {
		return this.codeOperation;
	}

	public void setCodeOperation(String codeOperation) {
		this.codeOperation = codeOperation;
	}

	@Column(name = "REF_DEM", length = 100)
	public String getRefDem() {
		return this.refDem;
	}

	public void setRefDem(String refDem) {
		this.refDem = refDem;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEMANDE", length = 7)
	public Date getDateDemande() {
		return this.dateDemande;
	}

	public void setDateDemande(Date dateDemande) {
		this.dateDemande = dateDemande;
	}

	@Column(name = "NUM_LIGNE", length = 20)
	public String getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(String numLigne) {
		this.numLigne = numLigne;
	}

	@Column(name = "EXTERNAL_RESS", length = 100)
	public String getExternalRess() {
		return this.externalRess;
	}

	public void setExternalRess(String externalRess) {
		this.externalRess = externalRess;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ENVOI", length = 7)
	public Date getDateEnvoi() {
		return this.dateEnvoi;
	}

	public void setDateEnvoi(Date dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}

	@Column(name = "DEBIT", length = 50)
	public String getDebit() {
		return this.debit;
	}

	public void setDebit(String debit) {
		this.debit = debit;
	}

	@Column(name = "ETAT_EVENT", precision = 1, scale = 0)
	public Boolean getEtatEvent() {
		return this.etatEvent;
	}

	public void setEtatEvent(Boolean etatEvent) {
		this.etatEvent = etatEvent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_RETOUR_BSCS", length = 7)
	public Date getDateRetourBscs() {
		return this.dateRetourBscs;
	}

	public void setDateRetourBscs(Date dateRetourBscs) {
		this.dateRetourBscs = dateRetourBscs;
	}

	@Column(name = "MOTIF_RETOUR_BSCS", length = 500)
	public String getMotifRetourBscs() {
		return this.motifRetourBscs;
	}

	public void setMotifRetourBscs(String motifRetourBscs) {
		this.motifRetourBscs = motifRetourBscs;
	}

	@Column(name = "CODE_MOTIF_ETAT", length = 100)
	public String getCodeMotifEtat() {
		return this.codeMotifEtat;
	}

	public void setCodeMotifEtat(String codeMotifEtat) {
		this.codeMotifEtat = codeMotifEtat;
	}

	@Column(name = "LIBELLE_MOTIF_ETAT", length = 100)
	public String getLibelleMotifEtat() {
		return this.libelleMotifEtat;
	}

	public void setLibelleMotifEtat(String libelleMotifEtat) {
		this.libelleMotifEtat = libelleMotifEtat;
	}

}
