package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BillingParamMotif generated by hbm2java
 */
@Entity
@Table(name = "BILLING_PARAM_MOTIF", schema = "TOM")
public class BillingParamMotif implements java.io.Serializable {

	private BillingParamMotifId id;

	public BillingParamMotif() {
	}

	public BillingParamMotif(BillingParamMotifId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codeEvent", column = @Column(name = "CODE_EVENT", nullable = false, length = 50)),
			@AttributeOverride(name = "CMotif", column = @Column(name = "C_MOTIF", nullable = false, length = 100)) })
	public BillingParamMotifId getId() {
		return this.id;
	}

	public void setId(BillingParamMotifId id) {
		this.id = id;
	}

}
