package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillingEvent generated by hbm2java
 */
@Entity
@Table(name = "BILLING_EVENT", schema = "TOM")
public class BillingEvent implements java.io.Serializable {

	private BigDecimal idEvent;
	private BillingParamEvent billingParamEvent;
	private Motif motif;
	private Partenaire partenaire;
	private Date dateEvent;
	private String refDem;
	private Date dateDemande;
	private String numLigne;
	private String externalRess;
	private Date dateEnvoi;
	private String debit;
	private boolean etatEvent;
	private Date dateRetourBscs;
	private String motifRetourBscs;

	public BillingEvent() {
	}

	public BillingEvent(BigDecimal idEvent, BillingParamEvent billingParamEvent, Partenaire partenaire, Date dateEvent,
			boolean etatEvent) {
		this.idEvent = idEvent;
		this.billingParamEvent = billingParamEvent;
		this.partenaire = partenaire;
		this.dateEvent = dateEvent;
		this.etatEvent = etatEvent;
	}

	public BillingEvent(BigDecimal idEvent, BillingParamEvent billingParamEvent, Motif motif, Partenaire partenaire,
			Date dateEvent, String refDem, Date dateDemande, String numLigne, String externalRess, Date dateEnvoi,
			String debit, boolean etatEvent, Date dateRetourBscs, String motifRetourBscs) {
		this.idEvent = idEvent;
		this.billingParamEvent = billingParamEvent;
		this.motif = motif;
		this.partenaire = partenaire;
		this.dateEvent = dateEvent;
		this.refDem = refDem;
		this.dateDemande = dateDemande;
		this.numLigne = numLigne;
		this.externalRess = externalRess;
		this.dateEnvoi = dateEnvoi;
		this.debit = debit;
		this.etatEvent = etatEvent;
		this.dateRetourBscs = dateRetourBscs;
		this.motifRetourBscs = motifRetourBscs;
	}

	@Id

	@Column(name = "ID_EVENT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdEvent() {
		return this.idEvent;
	}

	public void setIdEvent(BigDecimal idEvent) {
		this.idEvent = idEvent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_EVENT", nullable = false)
	public BillingParamEvent getBillingParamEvent() {
		return this.billingParamEvent;
	}

	public void setBillingParamEvent(BillingParamEvent billingParamEvent) {
		this.billingParamEvent = billingParamEvent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_MOTIF")
	public Motif getMotif() {
		return this.motif;
	}

	public void setMotif(Motif motif) {
		this.motif = motif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PART", nullable = false)
	public Partenaire getPartenaire() {
		return this.partenaire;
	}

	public void setPartenaire(Partenaire partenaire) {
		this.partenaire = partenaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_EVENT", nullable = false, length = 7)
	public Date getDateEvent() {
		return this.dateEvent;
	}

	public void setDateEvent(Date dateEvent) {
		this.dateEvent = dateEvent;
	}

	@Column(name = "REF_DEM", length = 100)
	public String getRefDem() {
		return this.refDem;
	}

	public void setRefDem(String refDem) {
		this.refDem = refDem;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEMANDE", length = 7)
	public Date getDateDemande() {
		return this.dateDemande;
	}

	public void setDateDemande(Date dateDemande) {
		this.dateDemande = dateDemande;
	}

	@Column(name = "NUM_LIGNE", length = 20)
	public String getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(String numLigne) {
		this.numLigne = numLigne;
	}

	@Column(name = "EXTERNAL_RESS", length = 100)
	public String getExternalRess() {
		return this.externalRess;
	}

	public void setExternalRess(String externalRess) {
		this.externalRess = externalRess;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ENVOI", length = 7)
	public Date getDateEnvoi() {
		return this.dateEnvoi;
	}

	public void setDateEnvoi(Date dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}

	@Column(name = "DEBIT", length = 50)
	public String getDebit() {
		return this.debit;
	}

	public void setDebit(String debit) {
		this.debit = debit;
	}

	@Column(name = "ETAT_EVENT", nullable = false, precision = 1, scale = 0)
	public boolean isEtatEvent() {
		return this.etatEvent;
	}

	public void setEtatEvent(boolean etatEvent) {
		this.etatEvent = etatEvent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_RETOUR_BSCS", length = 7)
	public Date getDateRetourBscs() {
		return this.dateRetourBscs;
	}

	public void setDateRetourBscs(Date dateRetourBscs) {
		this.dateRetourBscs = dateRetourBscs;
	}

	@Column(name = "MOTIF_RETOUR_BSCS", length = 500)
	public String getMotifRetourBscs() {
		return this.motifRetourBscs;
	}

	public void setMotifRetourBscs(String motifRetourBscs) {
		this.motifRetourBscs = motifRetourBscs;
	}

}
