package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BillingParamMotifId generated by hbm2java
 */
@Embeddable
public class BillingParamMotifId implements java.io.Serializable {

	private String codeEvent;
	private String CMotif;

	public BillingParamMotifId() {
	}

	public BillingParamMotifId(String codeEvent, String CMotif) {
		this.codeEvent = codeEvent;
		this.CMotif = CMotif;
	}

	@Column(name = "CODE_EVENT", nullable = false, length = 50)
	public String getCodeEvent() {
		return this.codeEvent;
	}

	public void setCodeEvent(String codeEvent) {
		this.codeEvent = codeEvent;
	}

	@Column(name = "C_MOTIF", nullable = false, length = 100)
	public String getCMotif() {
		return this.CMotif;
	}

	public void setCMotif(String CMotif) {
		this.CMotif = CMotif;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BillingParamMotifId))
			return false;
		BillingParamMotifId castOther = (BillingParamMotifId) other;

		return ((this.getCodeEvent() == castOther.getCodeEvent()) || (this.getCodeEvent() != null
				&& castOther.getCodeEvent() != null && this.getCodeEvent().equals(castOther.getCodeEvent())))
				&& ((this.getCMotif() == castOther.getCMotif()) || (this.getCMotif() != null
						&& castOther.getCMotif() != null && this.getCMotif().equals(castOther.getCMotif())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodeEvent() == null ? 0 : this.getCodeEvent().hashCode());
		result = 37 * result + (getCMotif() == null ? 0 : this.getCMotif().hashCode());
		return result;
	}

}
