package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Delegation generated by hbm2java
 */
@Entity
@Table(name = "DELEGATION", schema = "TOM")
public class Delegation implements java.io.Serializable {

	private String CDeleg;
	private Region region;
	private String deleg;
	private Set<Localite> localites = new HashSet<Localite>(0);

	public Delegation() {
	}

	public Delegation(String CDeleg, Region region, String deleg) {
		this.CDeleg = CDeleg;
		this.region = region;
		this.deleg = deleg;
	}

	public Delegation(String CDeleg, Region region, String deleg, Set<Localite> localites) {
		this.CDeleg = CDeleg;
		this.region = region;
		this.deleg = deleg;
		this.localites = localites;
	}

	@Id

	@Column(name = "C_DELEG", unique = true, nullable = false, length = 10)
	public String getCDeleg() {
		return this.CDeleg;
	}

	public void setCDeleg(String CDeleg) {
		this.CDeleg = CDeleg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_REGION", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "DELEG", nullable = false, length = 100)
	public String getDeleg() {
		return this.deleg;
	}

	public void setDeleg(String deleg) {
		this.deleg = deleg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "delegation")
	public Set<Localite> getLocalites() {
		return this.localites;
	}

	public void setLocalites(Set<Localite> localites) {
		this.localites = localites;
	}

}
