package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Demande generated by hbm2java
 */
@Entity
@Table(name = "DEMANDE", schema = "TOM")
public class Demande implements java.io.Serializable {

	private BigDecimal idDem;
	private Demande demande;
	private Localite localite;
	private Motif motif;
	private Operation operation;
	private Parc parc;
	private Partenaire partenaire;
	private PrmDemEtat prmDemEtat;
	private Region region;
	private String bpmUid;
	private Date DCreation;
	private Date DEtat;
	private String sysSrc;
	private String refDemSrc;
	private Date DDemSrc;
	private String pointVente;
	private String numLigne;
	private String codeAcces;
	private Date dcp;
	private Date DInsProv;
	private String typeClient;
	private String idClient;
	private String nom;
	private Date DFinInsProv;
	private Date DSuspProv;
	private BigDecimal nbreLignes;
	private String prenom;
	private String typeIdentifiant;
	private String identifiant;
	private String contact1;
	private String contact1Tel;
	private String contact1Fax;
	private String contact1Mail;
	private String contact2;
	private String contact2Tel;
	private String contact2Fax;
	private String contact2Mail;
	private String idOffre;
	private String offre;
	private String offreCodeBscs;
	private String idOldOffre;
	private String oldOffre;
	private BigDecimal idAdrInst;
	private String adrInst;
	private String adrInstX;
	private String adrInstY;
	private BigDecimal idOldAdrInst;
	private String oldAdrInst;
	private String oldAdrInstX;
	private String oldAdrInstY;
	private String objetModif;
	private Date DModif;
	private Date DFinSuspProv;
	private Date DMes;
	private Boolean FHp;
	private String motifSrc;
	private Boolean FFacturee;
	private String codeUgs;
	private String codeUls;
	private String codeCsc;
	private String codeDrt;
	private String CRegionSig;
	private String idSig;
	private String idOldAdrInstSig;
	private String idOffreFix;
	private Set<DemGroupement> demGroupements = new HashSet<DemGroupement>(0);
	private Set<DemSuivi> demSuivis = new HashSet<DemSuivi>(0);
	private Set<DenumOffice> denumOffices = new HashSet<DenumOffice>(0);
	private Set<Ot> ots = new HashSet<Ot>(0);
	private Set<DemProp> demProps = new HashSet<DemProp>(0);
	private Set<DemJms> demJmses = new HashSet<DemJms>(0);
	private Set<DemSs> demSses = new HashSet<DemSs>(0);
	private Set<Demande> demandes = new HashSet<Demande>(0);

	public Demande() {
	}

	public Demande(BigDecimal idDem, Operation operation, PrmDemEtat prmDemEtat, Date DCreation, Date DEtat,
			String sysSrc) {
		this.idDem = idDem;
		this.operation = operation;
		this.prmDemEtat = prmDemEtat;
		this.DCreation = DCreation;
		this.DEtat = DEtat;
		this.sysSrc = sysSrc;
	}

	public Demande(BigDecimal idDem, Demande demande, Localite localite, Motif motif, Operation operation, Parc parc,
			Partenaire partenaire, PrmDemEtat prmDemEtat, Region region, String bpmUid, Date DCreation, Date DEtat,
			String sysSrc, String refDemSrc, Date DDemSrc, String pointVente, String numLigne, String codeAcces,
			Date dcp, Date DInsProv, String typeClient, String idClient, String nom, Date DFinInsProv, Date DSuspProv,
			BigDecimal nbreLignes, String prenom, String typeIdentifiant, String identifiant, String contact1,
			String contact1Tel, String contact1Fax, String contact1Mail, String contact2, String contact2Tel,
			String contact2Fax, String contact2Mail, String idOffre, String offre, String offreCodeBscs,
			String idOldOffre, String oldOffre, BigDecimal idAdrInst, String adrInst, String adrInstX, String adrInstY,
			BigDecimal idOldAdrInst, String oldAdrInst, String oldAdrInstX, String oldAdrInstY, String objetModif,
			Date DModif, Date DFinSuspProv, Date DMes, Boolean FHp, String motifSrc, Boolean FFacturee, String codeUgs,
			String codeUls, String codeCsc, String codeDrt, String CRegionSig, String idSig, String idOldAdrInstSig,
			String idOffreFix, Set<DemGroupement> demGroupements, Set<DemSuivi> demSuivis,
			Set<DenumOffice> denumOffices, Set<Ot> ots, Set<DemProp> demProps, Set<DemJms> demJmses, Set<DemSs> demSses,
			Set<Demande> demandes) {
		this.idDem = idDem;
		this.demande = demande;
		this.localite = localite;
		this.motif = motif;
		this.operation = operation;
		this.parc = parc;
		this.partenaire = partenaire;
		this.prmDemEtat = prmDemEtat;
		this.region = region;
		this.bpmUid = bpmUid;
		this.DCreation = DCreation;
		this.DEtat = DEtat;
		this.sysSrc = sysSrc;
		this.refDemSrc = refDemSrc;
		this.DDemSrc = DDemSrc;
		this.pointVente = pointVente;
		this.numLigne = numLigne;
		this.codeAcces = codeAcces;
		this.dcp = dcp;
		this.DInsProv = DInsProv;
		this.typeClient = typeClient;
		this.idClient = idClient;
		this.nom = nom;
		this.DFinInsProv = DFinInsProv;
		this.DSuspProv = DSuspProv;
		this.nbreLignes = nbreLignes;
		this.prenom = prenom;
		this.typeIdentifiant = typeIdentifiant;
		this.identifiant = identifiant;
		this.contact1 = contact1;
		this.contact1Tel = contact1Tel;
		this.contact1Fax = contact1Fax;
		this.contact1Mail = contact1Mail;
		this.contact2 = contact2;
		this.contact2Tel = contact2Tel;
		this.contact2Fax = contact2Fax;
		this.contact2Mail = contact2Mail;
		this.idOffre = idOffre;
		this.offre = offre;
		this.offreCodeBscs = offreCodeBscs;
		this.idOldOffre = idOldOffre;
		this.oldOffre = oldOffre;
		this.idAdrInst = idAdrInst;
		this.adrInst = adrInst;
		this.adrInstX = adrInstX;
		this.adrInstY = adrInstY;
		this.idOldAdrInst = idOldAdrInst;
		this.oldAdrInst = oldAdrInst;
		this.oldAdrInstX = oldAdrInstX;
		this.oldAdrInstY = oldAdrInstY;
		this.objetModif = objetModif;
		this.DModif = DModif;
		this.DFinSuspProv = DFinSuspProv;
		this.DMes = DMes;
		this.FHp = FHp;
		this.motifSrc = motifSrc;
		this.FFacturee = FFacturee;
		this.codeUgs = codeUgs;
		this.codeUls = codeUls;
		this.codeCsc = codeCsc;
		this.codeDrt = codeDrt;
		this.CRegionSig = CRegionSig;
		this.idSig = idSig;
		this.idOldAdrInstSig = idOldAdrInstSig;
		this.idOffreFix = idOffreFix;
		this.demGroupements = demGroupements;
		this.demSuivis = demSuivis;
		this.denumOffices = denumOffices;
		this.ots = ots;
		this.demProps = demProps;
		this.demJmses = demJmses;
		this.demSses = demSses;
		this.demandes = demandes;
	}

	@Id

	@Column(name = "ID_DEM", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEM_MERE")
	public Demande getDemande() {
		return this.demande;
	}

	public void setDemande(Demande demande) {
		this.demande = demande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_LOC")
	public Localite getLocalite() {
		return this.localite;
	}

	public void setLocalite(Localite localite) {
		this.localite = localite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_MOTIF")
	public Motif getMotif() {
		return this.motif;
	}

	public void setMotif(Motif motif) {
		this.motif = motif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_OP", nullable = false)
	public Operation getOperation() {
		return this.operation;
	}

	public void setOperation(Operation operation) {
		this.operation = operation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARC")
	public Parc getParc() {
		return this.parc;
	}

	public void setParc(Parc parc) {
		this.parc = parc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PART")
	public Partenaire getPartenaire() {
		return this.partenaire;
	}

	public void setPartenaire(Partenaire partenaire) {
		this.partenaire = partenaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmDemEtat getPrmDemEtat() {
		return this.prmDemEtat;
	}

	public void setPrmDemEtat(PrmDemEtat prmDemEtat) {
		this.prmDemEtat = prmDemEtat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_REGION")
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "BPM_UID", length = 50)
	public String getBpmUid() {
		return this.bpmUid;
	}

	public void setBpmUid(String bpmUid) {
		this.bpmUid = bpmUid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CREATION", nullable = false, length = 11)
	public Date getDCreation() {
		return this.DCreation;
	}

	public void setDCreation(Date DCreation) {
		this.DCreation = DCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ETAT", nullable = false, length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	@Column(name = "SYS_SRC", nullable = false, length = 50)
	public String getSysSrc() {
		return this.sysSrc;
	}

	public void setSysSrc(String sysSrc) {
		this.sysSrc = sysSrc;
	}

	@Column(name = "REF_DEM_SRC", length = 200)
	public String getRefDemSrc() {
		return this.refDemSrc;
	}

	public void setRefDemSrc(String refDemSrc) {
		this.refDemSrc = refDemSrc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_DEM_SRC", length = 11)
	public Date getDDemSrc() {
		return this.DDemSrc;
	}

	public void setDDemSrc(Date DDemSrc) {
		this.DDemSrc = DDemSrc;
	}

	@Column(name = "POINT_VENTE", length = 100)
	public String getPointVente() {
		return this.pointVente;
	}

	public void setPointVente(String pointVente) {
		this.pointVente = pointVente;
	}

	@Column(name = "NUM_LIGNE", length = 20)
	public String getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(String numLigne) {
		this.numLigne = numLigne;
	}

	@Column(name = "CODE_ACCES", length = 50)
	public String getCodeAcces() {
		return this.codeAcces;
	}

	public void setCodeAcces(String codeAcces) {
		this.codeAcces = codeAcces;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DCP", length = 11)
	public Date getDcp() {
		return this.dcp;
	}

	public void setDcp(Date dcp) {
		this.dcp = dcp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_INS_PROV", length = 7)
	public Date getDInsProv() {
		return this.DInsProv;
	}

	public void setDInsProv(Date DInsProv) {
		this.DInsProv = DInsProv;
	}

	@Column(name = "TYPE_CLIENT", length = 50)
	public String getTypeClient() {
		return this.typeClient;
	}

	public void setTypeClient(String typeClient) {
		this.typeClient = typeClient;
	}

	@Column(name = "ID_CLIENT", length = 100)
	public String getIdClient() {
		return this.idClient;
	}

	public void setIdClient(String idClient) {
		this.idClient = idClient;
	}

	@Column(name = "NOM", length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_FIN_INS_PROV", length = 7)
	public Date getDFinInsProv() {
		return this.DFinInsProv;
	}

	public void setDFinInsProv(Date DFinInsProv) {
		this.DFinInsProv = DFinInsProv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_SUSP_PROV", length = 7)
	public Date getDSuspProv() {
		return this.DSuspProv;
	}

	public void setDSuspProv(Date DSuspProv) {
		this.DSuspProv = DSuspProv;
	}

	@Column(name = "NBRE_LIGNES", precision = 22, scale = 0)
	public BigDecimal getNbreLignes() {
		return this.nbreLignes;
	}

	public void setNbreLignes(BigDecimal nbreLignes) {
		this.nbreLignes = nbreLignes;
	}

	@Column(name = "PRENOM", length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "TYPE_IDENTIFIANT", length = 50)
	public String getTypeIdentifiant() {
		return this.typeIdentifiant;
	}

	public void setTypeIdentifiant(String typeIdentifiant) {
		this.typeIdentifiant = typeIdentifiant;
	}

	@Column(name = "IDENTIFIANT", length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "CONTACT_1", length = 200)
	public String getContact1() {
		return this.contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	@Column(name = "CONTACT_1_TEL", length = 50)
	public String getContact1Tel() {
		return this.contact1Tel;
	}

	public void setContact1Tel(String contact1Tel) {
		this.contact1Tel = contact1Tel;
	}

	@Column(name = "CONTACT_1_FAX", length = 50)
	public String getContact1Fax() {
		return this.contact1Fax;
	}

	public void setContact1Fax(String contact1Fax) {
		this.contact1Fax = contact1Fax;
	}

	@Column(name = "CONTACT_1_MAIL", length = 50)
	public String getContact1Mail() {
		return this.contact1Mail;
	}

	public void setContact1Mail(String contact1Mail) {
		this.contact1Mail = contact1Mail;
	}

	@Column(name = "CONTACT_2", length = 200)
	public String getContact2() {
		return this.contact2;
	}

	public void setContact2(String contact2) {
		this.contact2 = contact2;
	}

	@Column(name = "CONTACT_2_TEL", length = 50)
	public String getContact2Tel() {
		return this.contact2Tel;
	}

	public void setContact2Tel(String contact2Tel) {
		this.contact2Tel = contact2Tel;
	}

	@Column(name = "CONTACT_2_FAX", length = 50)
	public String getContact2Fax() {
		return this.contact2Fax;
	}

	public void setContact2Fax(String contact2Fax) {
		this.contact2Fax = contact2Fax;
	}

	@Column(name = "CONTACT_2_MAIL", length = 50)
	public String getContact2Mail() {
		return this.contact2Mail;
	}

	public void setContact2Mail(String contact2Mail) {
		this.contact2Mail = contact2Mail;
	}

	@Column(name = "ID_OFFRE", length = 50)
	public String getIdOffre() {
		return this.idOffre;
	}

	public void setIdOffre(String idOffre) {
		this.idOffre = idOffre;
	}

	@Column(name = "OFFRE", length = 200)
	public String getOffre() {
		return this.offre;
	}

	public void setOffre(String offre) {
		this.offre = offre;
	}

	@Column(name = "OFFRE_CODE_BSCS", length = 100)
	public String getOffreCodeBscs() {
		return this.offreCodeBscs;
	}

	public void setOffreCodeBscs(String offreCodeBscs) {
		this.offreCodeBscs = offreCodeBscs;
	}

	@Column(name = "ID_OLD_OFFRE", length = 50)
	public String getIdOldOffre() {
		return this.idOldOffre;
	}

	public void setIdOldOffre(String idOldOffre) {
		this.idOldOffre = idOldOffre;
	}

	@Column(name = "OLD_OFFRE", length = 200)
	public String getOldOffre() {
		return this.oldOffre;
	}

	public void setOldOffre(String oldOffre) {
		this.oldOffre = oldOffre;
	}

	@Column(name = "ID_ADR_INST", precision = 22, scale = 0)
	public BigDecimal getIdAdrInst() {
		return this.idAdrInst;
	}

	public void setIdAdrInst(BigDecimal idAdrInst) {
		this.idAdrInst = idAdrInst;
	}

	@Column(name = "ADR_INST", length = 500)
	public String getAdrInst() {
		return this.adrInst;
	}

	public void setAdrInst(String adrInst) {
		this.adrInst = adrInst;
	}

	@Column(name = "ADR_INST_X", length = 20)
	public String getAdrInstX() {
		return this.adrInstX;
	}

	public void setAdrInstX(String adrInstX) {
		this.adrInstX = adrInstX;
	}

	@Column(name = "ADR_INST_Y", length = 20)
	public String getAdrInstY() {
		return this.adrInstY;
	}

	public void setAdrInstY(String adrInstY) {
		this.adrInstY = adrInstY;
	}

	@Column(name = "ID_OLD_ADR_INST", precision = 22, scale = 0)
	public BigDecimal getIdOldAdrInst() {
		return this.idOldAdrInst;
	}

	public void setIdOldAdrInst(BigDecimal idOldAdrInst) {
		this.idOldAdrInst = idOldAdrInst;
	}

	@Column(name = "OLD_ADR_INST", length = 500)
	public String getOldAdrInst() {
		return this.oldAdrInst;
	}

	public void setOldAdrInst(String oldAdrInst) {
		this.oldAdrInst = oldAdrInst;
	}

	@Column(name = "OLD_ADR_INST_X", length = 20)
	public String getOldAdrInstX() {
		return this.oldAdrInstX;
	}

	public void setOldAdrInstX(String oldAdrInstX) {
		this.oldAdrInstX = oldAdrInstX;
	}

	@Column(name = "OLD_ADR_INST_Y", length = 20)
	public String getOldAdrInstY() {
		return this.oldAdrInstY;
	}

	public void setOldAdrInstY(String oldAdrInstY) {
		this.oldAdrInstY = oldAdrInstY;
	}

	@Column(name = "OBJET_MODIF", length = 500)
	public String getObjetModif() {
		return this.objetModif;
	}

	public void setObjetModif(String objetModif) {
		this.objetModif = objetModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_MODIF", length = 11)
	public Date getDModif() {
		return this.DModif;
	}

	public void setDModif(Date DModif) {
		this.DModif = DModif;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_FIN_SUSP_PROV", length = 7)
	public Date getDFinSuspProv() {
		return this.DFinSuspProv;
	}

	public void setDFinSuspProv(Date DFinSuspProv) {
		this.DFinSuspProv = DFinSuspProv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_MES", length = 7)
	public Date getDMes() {
		return this.DMes;
	}

	public void setDMes(Date DMes) {
		this.DMes = DMes;
	}

	@Column(name = "F_HP", precision = 1, scale = 0)
	public Boolean getFHp() {
		return this.FHp;
	}

	public void setFHp(Boolean FHp) {
		this.FHp = FHp;
	}

	@Column(name = "MOTIF_SRC", length = 500)
	public String getMotifSrc() {
		return this.motifSrc;
	}

	public void setMotifSrc(String motifSrc) {
		this.motifSrc = motifSrc;
	}

	@Column(name = "F_FACTUREE", precision = 1, scale = 0)
	public Boolean getFFacturee() {
		return this.FFacturee;
	}

	public void setFFacturee(Boolean FFacturee) {
		this.FFacturee = FFacturee;
	}

	@Column(name = "CODE_UGS", length = 200)
	public String getCodeUgs() {
		return this.codeUgs;
	}

	public void setCodeUgs(String codeUgs) {
		this.codeUgs = codeUgs;
	}

	@Column(name = "CODE_ULS", length = 200)
	public String getCodeUls() {
		return this.codeUls;
	}

	public void setCodeUls(String codeUls) {
		this.codeUls = codeUls;
	}

	@Column(name = "CODE_CSC", length = 200)
	public String getCodeCsc() {
		return this.codeCsc;
	}

	public void setCodeCsc(String codeCsc) {
		this.codeCsc = codeCsc;
	}

	@Column(name = "CODE_DRT", length = 200)
	public String getCodeDrt() {
		return this.codeDrt;
	}

	public void setCodeDrt(String codeDrt) {
		this.codeDrt = codeDrt;
	}

	@Column(name = "C_REGION_SIG", length = 200)
	public String getCRegionSig() {
		return this.CRegionSig;
	}

	public void setCRegionSig(String CRegionSig) {
		this.CRegionSig = CRegionSig;
	}

	@Column(name = "ID_SIG", length = 200)
	public String getIdSig() {
		return this.idSig;
	}

	public void setIdSig(String idSig) {
		this.idSig = idSig;
	}

	@Column(name = "ID_OLD_ADR_INST_SIG", length = 200)
	public String getIdOldAdrInstSig() {
		return this.idOldAdrInstSig;
	}

	public void setIdOldAdrInstSig(String idOldAdrInstSig) {
		this.idOldAdrInstSig = idOldAdrInstSig;
	}

	@Column(name = "ID_OFFRE_FIX", length = 200)
	public String getIdOffreFix() {
		return this.idOffreFix;
	}

	public void setIdOffreFix(String idOffreFix) {
		this.idOffreFix = idOffreFix;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<DemGroupement> getDemGroupements() {
		return this.demGroupements;
	}

	public void setDemGroupements(Set<DemGroupement> demGroupements) {
		this.demGroupements = demGroupements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<DemSuivi> getDemSuivis() {
		return this.demSuivis;
	}

	public void setDemSuivis(Set<DemSuivi> demSuivis) {
		this.demSuivis = demSuivis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<DenumOffice> getDenumOffices() {
		return this.denumOffices;
	}

	public void setDenumOffices(Set<DenumOffice> denumOffices) {
		this.denumOffices = denumOffices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<Ot> getOts() {
		return this.ots;
	}

	public void setOts(Set<Ot> ots) {
		this.ots = ots;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<DemProp> getDemProps() {
		return this.demProps;
	}

	public void setDemProps(Set<DemProp> demProps) {
		this.demProps = demProps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<DemJms> getDemJmses() {
		return this.demJmses;
	}

	public void setDemJmses(Set<DemJms> demJmses) {
		this.demJmses = demJmses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<DemSs> getDemSses() {
		return this.demSses;
	}

	public void setDemSses(Set<DemSs> demSses) {
		this.demSses = demSses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demande")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

}
