package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DemGroupement generated by hbm2java
 */
@Entity
@Table(name = "DEM_GROUPEMENT", schema = "TOM")
public class DemGroupement implements java.io.Serializable {

	private DemGroupementId id;
	private Demande demande;

	public DemGroupement() {
	}

	public DemGroupement(DemGroupementId id, Demande demande) {
		this.id = id;
		this.demande = demande;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "numLigne", column = @Column(name = "NUM_LIGNE", nullable = false, length = 20)) })
	public DemGroupementId getId() {
		return this.id;
	}

	public void setId(DemGroupementId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEM", nullable = false, insertable = false, updatable = false)
	public Demande getDemande() {
		return this.demande;
	}

	public void setDemande(Demande demande) {
		this.demande = demande;
	}

}
