package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DemGroupementId generated by hbm2java
 */
@Embeddable
public class DemGroupementId implements java.io.Serializable {

	private BigDecimal idDem;
	private String numLigne;

	public DemGroupementId() {
	}

	public DemGroupementId(BigDecimal idDem, String numLigne) {
		this.idDem = idDem;
		this.numLigne = numLigne;
	}

	@Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "NUM_LIGNE", nullable = false, length = 20)
	public String getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(String numLigne) {
		this.numLigne = numLigne;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DemGroupementId))
			return false;
		DemGroupementId castOther = (DemGroupementId) other;

		return ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null && castOther.getIdDem() != null
				&& this.getIdDem().equals(castOther.getIdDem())))
				&& ((this.getNumLigne() == castOther.getNumLigne()) || (this.getNumLigne() != null
						&& castOther.getNumLigne() != null && this.getNumLigne().equals(castOther.getNumLigne())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + (getNumLigne() == null ? 0 : this.getNumLigne().hashCode());
		return result;
	}

}
