package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DemJmsId generated by hbm2java
 */
@Embeddable
public class DemJmsId implements java.io.Serializable {

	private BigDecimal idDem;
	private String idJms;

	public DemJmsId() {
	}

	public DemJmsId(BigDecimal idDem, String idJms) {
		this.idDem = idDem;
		this.idJms = idJms;
	}

	@Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "ID_JMS", nullable = false, length = 50)
	public String getIdJms() {
		return this.idJms;
	}

	public void setIdJms(String idJms) {
		this.idJms = idJms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DemJmsId))
			return false;
		DemJmsId castOther = (DemJmsId) other;

		return ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null && castOther.getIdDem() != null
				&& this.getIdDem().equals(castOther.getIdDem())))
				&& ((this.getIdJms() == castOther.getIdJms()) || (this.getIdJms() != null
						&& castOther.getIdJms() != null && this.getIdJms().equals(castOther.getIdJms())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + (getIdJms() == null ? 0 : this.getIdJms().hashCode());
		return result;
	}

}
