package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.sql.Clob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DemJms generated by hbm2java
 */
@Entity
@Table(name = "DEM_JMS", schema = "TOM")
public class DemJms implements java.io.Serializable {

	private DemJmsId id;
	private Demande demande;
	private Clob jms;

	public DemJms() {
	}

	public DemJms(DemJmsId id, Demande demande, Clob jms) {
		this.id = id;
		this.demande = demande;
		this.jms = jms;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idJms", column = @Column(name = "ID_JMS", nullable = false, length = 50)) })
	public DemJmsId getId() {
		return this.id;
	}

	public void setId(DemJmsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEM", nullable = false, insertable = false, updatable = false)
	public Demande getDemande() {
		return this.demande;
	}

	public void setDemande(Demande demande) {
		this.demande = demande;
	}

	@Column(name = "JMS", nullable = false)
	public Clob getJms() {
		return this.jms;
	}

	public void setJms(Clob jms) {
		this.jms = jms;
	}

}
