package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DemPropSuivi generated by hbm2java
 */
@Entity
@Table(name = "DEM_PROP_SUIVI", schema = "TOM")
public class DemPropSuivi implements java.io.Serializable {

	private DemPropSuiviId id;
	private DemProp demProp;
	private String valeur;
	private String idValeur;
	private Date DModif;
	private String loginModif;

	public DemPropSuivi() {
	}

	public DemPropSuivi(DemPropSuiviId id, DemProp demProp) {
		this.id = id;
		this.demProp = demProp;
	}

	public DemPropSuivi(DemPropSuiviId id, DemProp demProp, String valeur, String idValeur, Date DModif,
			String loginModif) {
		this.id = id;
		this.demProp = demProp;
		this.valeur = valeur;
		this.idValeur = idValeur;
		this.DModif = DModif;
		this.loginModif = loginModif;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "CProp", column = @Column(name = "C_PROP", nullable = false, length = 50)),
			@AttributeOverride(name = "groupe", column = @Column(name = "GROUPE", nullable = false, length = 50)),
			@AttributeOverride(name = "DSuivi", column = @Column(name = "D_SUIVI", nullable = false, length = 11)) })
	public DemPropSuiviId getId() {
		return this.id;
	}

	public void setId(DemPropSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_DEM", referencedColumnName = "ID_DEM", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "C_PROP", referencedColumnName = "C_PROP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "GROUPE", referencedColumnName = "GROUPE", nullable = false, insertable = false, updatable = false) })
	public DemProp getDemProp() {
		return this.demProp;
	}

	public void setDemProp(DemProp demProp) {
		this.demProp = demProp;
	}

	@Column(name = "VALEUR", length = 200)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "ID_VALEUR", length = 100)
	public String getIdValeur() {
		return this.idValeur;
	}

	public void setIdValeur(String idValeur) {
		this.idValeur = idValeur;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_MODIF", length = 11)
	public Date getDModif() {
		return this.DModif;
	}

	public void setDModif(Date DModif) {
		this.DModif = DModif;
	}

	@Column(name = "LOGIN_MODIF", length = 20)
	public String getLoginModif() {
		return this.loginModif;
	}

	public void setLoginModif(String loginModif) {
		this.loginModif = loginModif;
	}

}
