package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DemPropId generated by hbm2java
 */
@Embeddable
public class DemPropId implements java.io.Serializable {

	private BigDecimal idDem;
	private String CProp;
	private String groupe;

	public DemPropId() {
	}

	public DemPropId(BigDecimal idDem, String CProp, String groupe) {
		this.idDem = idDem;
		this.CProp = CProp;
		this.groupe = groupe;
	}

	@Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "C_PROP", nullable = false, length = 50)
	public String getCProp() {
		return this.CProp;
	}

	public void setCProp(String CProp) {
		this.CProp = CProp;
	}

	@Column(name = "GROUPE", nullable = false, length = 50)
	public String getGroupe() {
		return this.groupe;
	}

	public void setGroupe(String groupe) {
		this.groupe = groupe;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DemPropId))
			return false;
		DemPropId castOther = (DemPropId) other;

		return ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null && castOther.getIdDem() != null
				&& this.getIdDem().equals(castOther.getIdDem())))
				&& ((this.getCProp() == castOther.getCProp()) || (this.getCProp() != null
						&& castOther.getCProp() != null && this.getCProp().equals(castOther.getCProp())))
				&& ((this.getGroupe() == castOther.getGroupe()) || (this.getGroupe() != null
						&& castOther.getGroupe() != null && this.getGroupe().equals(castOther.getGroupe())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + (getCProp() == null ? 0 : this.getCProp().hashCode());
		result = 37 * result + (getGroupe() == null ? 0 : this.getGroupe().hashCode());
		return result;
	}

}
