package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DemSsPrmId generated by hbm2java
 */
@Embeddable
public class DemSsPrmId implements java.io.Serializable {

	private BigDecimal idDem;
	private short noSs;
	private short noValSs;

	public DemSsPrmId() {
	}

	public DemSsPrmId(BigDecimal idDem, short noSs, short noValSs) {
		this.idDem = idDem;
		this.noSs = noSs;
		this.noValSs = noValSs;
	}

	@Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "NO_SS", nullable = false, precision = 3, scale = 0)
	public short getNoSs() {
		return this.noSs;
	}

	public void setNoSs(short noSs) {
		this.noSs = noSs;
	}

	@Column(name = "NO_VAL_SS", nullable = false, precision = 3, scale = 0)
	public short getNoValSs() {
		return this.noValSs;
	}

	public void setNoValSs(short noValSs) {
		this.noValSs = noValSs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DemSsPrmId))
			return false;
		DemSsPrmId castOther = (DemSsPrmId) other;

		return ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null && castOther.getIdDem() != null
				&& this.getIdDem().equals(castOther.getIdDem()))) && (this.getNoSs() == castOther.getNoSs())
				&& (this.getNoValSs() == castOther.getNoValSs());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + this.getNoSs();
		result = 37 * result + this.getNoValSs();
		return result;
	}

}
