package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DemSs generated by hbm2java
 */
@Entity
@Table(name = "DEM_SS", schema = "TOM")
public class DemSs implements java.io.Serializable {

	private DemSsId id;
	private Demande demande;
	private String idSsSrc;
	private String srvSupp;
	private String typeServSup;
	private Date DActiv;
	private Date DDesactiv;
	private Set<DemSsPrm> demSsPrms = new HashSet<DemSsPrm>(0);

	public DemSs() {
	}

	public DemSs(DemSsId id, Demande demande, String srvSupp, String typeServSup) {
		this.id = id;
		this.demande = demande;
		this.srvSupp = srvSupp;
		this.typeServSup = typeServSup;
	}

	public DemSs(DemSsId id, Demande demande, String idSsSrc, String srvSupp, String typeServSup, Date DActiv,
			Date DDesactiv, Set<DemSsPrm> demSsPrms) {
		this.id = id;
		this.demande = demande;
		this.idSsSrc = idSsSrc;
		this.srvSupp = srvSupp;
		this.typeServSup = typeServSup;
		this.DActiv = DActiv;
		this.DDesactiv = DDesactiv;
		this.demSsPrms = demSsPrms;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noSs", column = @Column(name = "NO_SS", nullable = false, precision = 3, scale = 0)) })
	public DemSsId getId() {
		return this.id;
	}

	public void setId(DemSsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEM", nullable = false, insertable = false, updatable = false)
	public Demande getDemande() {
		return this.demande;
	}

	public void setDemande(Demande demande) {
		this.demande = demande;
	}

	@Column(name = "ID_SS_SRC", length = 50)
	public String getIdSsSrc() {
		return this.idSsSrc;
	}

	public void setIdSsSrc(String idSsSrc) {
		this.idSsSrc = idSsSrc;
	}

	@Column(name = "SRV_SUPP", nullable = false, length = 100)
	public String getSrvSupp() {
		return this.srvSupp;
	}

	public void setSrvSupp(String srvSupp) {
		this.srvSupp = srvSupp;
	}

	@Column(name = "TYPE_SERV_SUP", nullable = false, length = 10)
	public String getTypeServSup() {
		return this.typeServSup;
	}

	public void setTypeServSup(String typeServSup) {
		this.typeServSup = typeServSup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ACTIV", length = 11)
	public Date getDActiv() {
		return this.DActiv;
	}

	public void setDActiv(Date DActiv) {
		this.DActiv = DActiv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_DESACTIV", length = 11)
	public Date getDDesactiv() {
		return this.DDesactiv;
	}

	public void setDDesactiv(Date DDesactiv) {
		this.DDesactiv = DDesactiv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demSs")
	public Set<DemSsPrm> getDemSsPrms() {
		return this.demSsPrms;
	}

	public void setDemSsPrms(Set<DemSsPrm> demSsPrms) {
		this.demSsPrms = demSsPrms;
	}

}
