package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DemSsId generated by hbm2java
 */
@Embeddable
public class DemSsId implements java.io.Serializable {

	private BigDecimal idDem;
	private short noSs;

	public DemSsId() {
	}

	public DemSsId(BigDecimal idDem, short noSs) {
		this.idDem = idDem;
		this.noSs = noSs;
	}

	@Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "NO_SS", nullable = false, precision = 3, scale = 0)
	public short getNoSs() {
		return this.noSs;
	}

	public void setNoSs(short noSs) {
		this.noSs = noSs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DemSsId))
			return false;
		DemSsId castOther = (DemSsId) other;

		return ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null && castOther.getIdDem() != null
				&& this.getIdDem().equals(castOther.getIdDem()))) && (this.getNoSs() == castOther.getNoSs());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + this.getNoSs();
		return result;
	}

}
