package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DemSsPrm generated by hbm2java
 */
@Entity
@Table(name = "DEM_SS_PRM", schema = "TOM")
public class DemSsPrm implements java.io.Serializable {

	private DemSsPrmId id;
	private DemSs demSs;
	private String param;
	private String valeur;

	public DemSsPrm() {
	}

	public DemSsPrm(DemSsPrmId id, DemSs demSs, String valeur) {
		this.id = id;
		this.demSs = demSs;
		this.valeur = valeur;
	}

	public DemSsPrm(DemSsPrmId id, DemSs demSs, String param, String valeur) {
		this.id = id;
		this.demSs = demSs;
		this.param = param;
		this.valeur = valeur;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noSs", column = @Column(name = "NO_SS", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "noValSs", column = @Column(name = "NO_VAL_SS", nullable = false, precision = 3, scale = 0)) })
	public DemSsPrmId getId() {
		return this.id;
	}

	public void setId(DemSsPrmId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_DEM", referencedColumnName = "ID_DEM", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NO_SS", referencedColumnName = "NO_SS", nullable = false, insertable = false, updatable = false) })
	public DemSs getDemSs() {
		return this.demSs;
	}

	public void setDemSs(DemSs demSs) {
		this.demSs = demSs;
	}

	@Column(name = "PARAM", length = 100)
	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	@Column(name = "VALEUR", nullable = false, length = 100)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

}
