package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DemSuivi generated by hbm2java
 */
@Entity
@Table(name = "DEM_SUIVI", schema = "TOM")
public class DemSuivi implements java.io.Serializable {

	private DemSuiviId id;
	private Demande demande;
	private Motif motif;
	private PrmDemEtat prmDemEtat;

	public DemSuivi() {
	}

	public DemSuivi(DemSuiviId id, Demande demande, PrmDemEtat prmDemEtat) {
		this.id = id;
		this.demande = demande;
		this.prmDemEtat = prmDemEtat;
	}

	public DemSuivi(DemSuiviId id, Demande demande, Motif motif, PrmDemEtat prmDemEtat) {
		this.id = id;
		this.demande = demande;
		this.motif = motif;
		this.prmDemEtat = prmDemEtat;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "DEtat", column = @Column(name = "D_ETAT", nullable = false, length = 11)) })
	public DemSuiviId getId() {
		return this.id;
	}

	public void setId(DemSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEM", nullable = false, insertable = false, updatable = false)
	public Demande getDemande() {
		return this.demande;
	}

	public void setDemande(Demande demande) {
		this.demande = demande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_MOTIF")
	public Motif getMotif() {
		return this.motif;
	}

	public void setMotif(Motif motif) {
		this.motif = motif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmDemEtat getPrmDemEtat() {
		return this.prmDemEtat;
	}

	public void setPrmDemEtat(PrmDemEtat prmDemEtat) {
		this.prmDemEtat = prmDemEtat;
	}

}
