package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DenumOfficePropId generated by hbm2java
 */
@Embeddable
public class DenumOfficePropId implements java.io.Serializable {

	private int idDenum;
	private String CProp;

	public DenumOfficePropId() {
	}

	public DenumOfficePropId(int idDenum, String CProp) {
		this.idDenum = idDenum;
		this.CProp = CProp;
	}

	@Column(name = "ID_DENUM", nullable = false, precision = 6, scale = 0)
	public int getIdDenum() {
		return this.idDenum;
	}

	public void setIdDenum(int idDenum) {
		this.idDenum = idDenum;
	}

	@Column(name = "C_PROP", nullable = false, length = 50)
	public String getCProp() {
		return this.CProp;
	}

	public void setCProp(String CProp) {
		this.CProp = CProp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DenumOfficePropId))
			return false;
		DenumOfficePropId castOther = (DenumOfficePropId) other;

		return (this.getIdDenum() == castOther.getIdDenum())
				&& ((this.getCProp() == castOther.getCProp()) || (this.getCProp() != null
						&& castOther.getCProp() != null && this.getCProp().equals(castOther.getCProp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDenum();
		result = 37 * result + (getCProp() == null ? 0 : this.getCProp().hashCode());
		return result;
	}

}
