package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DenumOffice generated by hbm2java
 */
@Entity
@Table(name = "DENUM_OFFICE", schema = "TOM")
public class DenumOffice implements java.io.Serializable {

	private int idDenum;
	private Demande demande;
	private String numLigne;
	private String nouvLigne;
	private String contactNum;
	private String contactPrenom;
	private String contactNom;
	private boolean FXdsl;
	private boolean FTraiteWfbb;
	private String refDemWfbb;
	private boolean FRejetConfPaie;
	private boolean FVoip;
	private boolean FRejetOt;
	private Set<DenumOfficeProp> denumOfficeProps = new HashSet<DenumOfficeProp>(0);

	public DenumOffice() {
	}

	public DenumOffice(int idDenum, Demande demande, String numLigne, String nouvLigne, boolean FXdsl,
			boolean FTraiteWfbb, boolean FRejetConfPaie, boolean FVoip, boolean FRejetOt) {
		this.idDenum = idDenum;
		this.demande = demande;
		this.numLigne = numLigne;
		this.nouvLigne = nouvLigne;
		this.FXdsl = FXdsl;
		this.FTraiteWfbb = FTraiteWfbb;
		this.FRejetConfPaie = FRejetConfPaie;
		this.FVoip = FVoip;
		this.FRejetOt = FRejetOt;
	}

	public DenumOffice(int idDenum, Demande demande, String numLigne, String nouvLigne, String contactNum,
			String contactPrenom, String contactNom, boolean FXdsl, boolean FTraiteWfbb, String refDemWfbb,
			boolean FRejetConfPaie, boolean FVoip, boolean FRejetOt, Set<DenumOfficeProp> denumOfficeProps) {
		this.idDenum = idDenum;
		this.demande = demande;
		this.numLigne = numLigne;
		this.nouvLigne = nouvLigne;
		this.contactNum = contactNum;
		this.contactPrenom = contactPrenom;
		this.contactNom = contactNom;
		this.FXdsl = FXdsl;
		this.FTraiteWfbb = FTraiteWfbb;
		this.refDemWfbb = refDemWfbb;
		this.FRejetConfPaie = FRejetConfPaie;
		this.FVoip = FVoip;
		this.FRejetOt = FRejetOt;
		this.denumOfficeProps = denumOfficeProps;
	}

	@Id

	@Column(name = "ID_DENUM", unique = true, nullable = false, precision = 6, scale = 0)
	public int getIdDenum() {
		return this.idDenum;
	}

	public void setIdDenum(int idDenum) {
		this.idDenum = idDenum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEM", nullable = false)
	public Demande getDemande() {
		return this.demande;
	}

	public void setDemande(Demande demande) {
		this.demande = demande;
	}

	@Column(name = "NUM_LIGNE", nullable = false, length = 20)
	public String getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(String numLigne) {
		this.numLigne = numLigne;
	}

	@Column(name = "NOUV_LIGNE", nullable = false, length = 20)
	public String getNouvLigne() {
		return this.nouvLigne;
	}

	public void setNouvLigne(String nouvLigne) {
		this.nouvLigne = nouvLigne;
	}

	@Column(name = "CONTACT_NUM", length = 20)
	public String getContactNum() {
		return this.contactNum;
	}

	public void setContactNum(String contactNum) {
		this.contactNum = contactNum;
	}

	@Column(name = "CONTACT_PRENOM", length = 100)
	public String getContactPrenom() {
		return this.contactPrenom;
	}

	public void setContactPrenom(String contactPrenom) {
		this.contactPrenom = contactPrenom;
	}

	@Column(name = "CONTACT_NOM", length = 100)
	public String getContactNom() {
		return this.contactNom;
	}

	public void setContactNom(String contactNom) {
		this.contactNom = contactNom;
	}

	@Column(name = "F_XDSL", nullable = false, precision = 1, scale = 0)
	public boolean isFXdsl() {
		return this.FXdsl;
	}

	public void setFXdsl(boolean FXdsl) {
		this.FXdsl = FXdsl;
	}

	@Column(name = "F_TRAITE_WFBB", nullable = false, precision = 1, scale = 0)
	public boolean isFTraiteWfbb() {
		return this.FTraiteWfbb;
	}

	public void setFTraiteWfbb(boolean FTraiteWfbb) {
		this.FTraiteWfbb = FTraiteWfbb;
	}

	@Column(name = "REF_DEM_WFBB", length = 50)
	public String getRefDemWfbb() {
		return this.refDemWfbb;
	}

	public void setRefDemWfbb(String refDemWfbb) {
		this.refDemWfbb = refDemWfbb;
	}

	@Column(name = "F_REJET_CONF_PAIE", nullable = false, precision = 1, scale = 0)
	public boolean isFRejetConfPaie() {
		return this.FRejetConfPaie;
	}

	public void setFRejetConfPaie(boolean FRejetConfPaie) {
		this.FRejetConfPaie = FRejetConfPaie;
	}

	@Column(name = "F_VOIP", nullable = false, precision = 1, scale = 0)
	public boolean isFVoip() {
		return this.FVoip;
	}

	public void setFVoip(boolean FVoip) {
		this.FVoip = FVoip;
	}

	@Column(name = "F_REJET_OT", nullable = false, precision = 1, scale = 0)
	public boolean isFRejetOt() {
		return this.FRejetOt;
	}

	public void setFRejetOt(boolean FRejetOt) {
		this.FRejetOt = FRejetOt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "denumOffice")
	public Set<DenumOfficeProp> getDenumOfficeProps() {
		return this.denumOfficeProps;
	}

	public void setDenumOfficeProps(Set<DenumOfficeProp> denumOfficeProps) {
		this.denumOfficeProps = denumOfficeProps;
	}

}
