package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DroitAccesId generated by hbm2java
 */
@Embeddable
public class DroitAccesId implements java.io.Serializable {

	private BigDecimal idProfil;
	private String CFonction;

	public DroitAccesId() {
	}

	public DroitAccesId(BigDecimal idProfil, String CFonction) {
		this.idProfil = idProfil;
		this.CFonction = CFonction;
	}

	@Column(name = "ID_PROFIL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdProfil() {
		return this.idProfil;
	}

	public void setIdProfil(BigDecimal idProfil) {
		this.idProfil = idProfil;
	}

	@Column(name = "C_FONCTION", nullable = false, length = 20)
	public String getCFonction() {
		return this.CFonction;
	}

	public void setCFonction(String CFonction) {
		this.CFonction = CFonction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DroitAccesId))
			return false;
		DroitAccesId castOther = (DroitAccesId) other;

		return ((this.getIdProfil() == castOther.getIdProfil()) || (this.getIdProfil() != null
				&& castOther.getIdProfil() != null && this.getIdProfil().equals(castOther.getIdProfil())))
				&& ((this.getCFonction() == castOther.getCFonction()) || (this.getCFonction() != null
						&& castOther.getCFonction() != null && this.getCFonction().equals(castOther.getCFonction())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProfil() == null ? 0 : this.getIdProfil().hashCode());
		result = 37 * result + (getCFonction() == null ? 0 : this.getCFonction().hashCode());
		return result;
	}

}
