package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DroitAcces generated by hbm2java
 */
@Entity
@Table(name = "DROIT_ACCES", schema = "TOM")
public class DroitAcces implements java.io.Serializable {

	private DroitAccesId id;

	public DroitAcces() {
	}

	public DroitAcces(DroitAccesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProfil", column = @Column(name = "ID_PROFIL", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "CFonction", column = @Column(name = "C_FONCTION", nullable = false, length = 20)) })
	public DroitAccesId getId() {
		return this.id;
	}

	public void setId(DroitAccesId id) {
		this.id = id;
	}

}
