package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DunningOtSuivi generated by hbm2java
 */
@Entity
@Table(name = "DUNNING_OT_SUIVI", schema = "TOM")
public class DunningOtSuivi implements java.io.Serializable {

	private DunningOtSuiviId id;
	private DunningOt dunningOt;
	private PrmOtEtat prmOtEtat;
	private String loginEtat;
	private String comm;

	public DunningOtSuivi() {
	}

	public DunningOtSuivi(DunningOtSuiviId id, DunningOt dunningOt, PrmOtEtat prmOtEtat) {
		this.id = id;
		this.dunningOt = dunningOt;
		this.prmOtEtat = prmOtEtat;
	}

	public DunningOtSuivi(DunningOtSuiviId id, DunningOt dunningOt, PrmOtEtat prmOtEtat, String loginEtat,
			String comm) {
		this.id = id;
		this.dunningOt = dunningOt;
		this.prmOtEtat = prmOtEtat;
		this.loginEtat = loginEtat;
		this.comm = comm;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDunning", column = @Column(name = "ID_DUNNING", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noOtDunn", column = @Column(name = "NO_OT_DUNN", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "DEtat", column = @Column(name = "D_ETAT", nullable = false, length = 11)) })
	public DunningOtSuiviId getId() {
		return this.id;
	}

	public void setId(DunningOtSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_DUNNING", referencedColumnName = "ID_DUNNING", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NO_OT_DUNN", referencedColumnName = "NO_OT_DUNN", nullable = false, insertable = false, updatable = false) })
	public DunningOt getDunningOt() {
		return this.dunningOt;
	}

	public void setDunningOt(DunningOt dunningOt) {
		this.dunningOt = dunningOt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmOtEtat getPrmOtEtat() {
		return this.prmOtEtat;
	}

	public void setPrmOtEtat(PrmOtEtat prmOtEtat) {
		this.prmOtEtat = prmOtEtat;
	}

	@Column(name = "LOGIN_ETAT", length = 20)
	public String getLoginEtat() {
		return this.loginEtat;
	}

	public void setLoginEtat(String loginEtat) {
		this.loginEtat = loginEtat;
	}

	@Column(name = "COMM", length = 500)
	public String getComm() {
		return this.comm;
	}

	public void setComm(String comm) {
		this.comm = comm;
	}

}
