package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DunningOtId generated by hbm2java
 */
@Embeddable
public class DunningOtId implements java.io.Serializable {

	private BigDecimal idDunning;
	private int noOtDunn;

	public DunningOtId() {
	}

	public DunningOtId(BigDecimal idDunning, int noOtDunn) {
		this.idDunning = idDunning;
		this.noOtDunn = noOtDunn;
	}

	@Column(name = "ID_DUNNING", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDunning() {
		return this.idDunning;
	}

	public void setIdDunning(BigDecimal idDunning) {
		this.idDunning = idDunning;
	}

	@Column(name = "NO_OT_DUNN", nullable = false, precision = 6, scale = 0)
	public int getNoOtDunn() {
		return this.noOtDunn;
	}

	public void setNoOtDunn(int noOtDunn) {
		this.noOtDunn = noOtDunn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DunningOtId))
			return false;
		DunningOtId castOther = (DunningOtId) other;

		return ((this.getIdDunning() == castOther.getIdDunning()) || (this.getIdDunning() != null
				&& castOther.getIdDunning() != null && this.getIdDunning().equals(castOther.getIdDunning())))
				&& (this.getNoOtDunn() == castOther.getNoOtDunn());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDunning() == null ? 0 : this.getIdDunning().hashCode());
		result = 37 * result + this.getNoOtDunn();
		return result;
	}

}
