package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DunningOtSuiviId generated by hbm2java
 */
@Embeddable
public class DunningOtSuiviId implements java.io.Serializable {

	private BigDecimal idDunning;
	private int noOtDunn;
	private Date DEtat;

	public DunningOtSuiviId() {
	}

	public DunningOtSuiviId(BigDecimal idDunning, int noOtDunn, Date DEtat) {
		this.idDunning = idDunning;
		this.noOtDunn = noOtDunn;
		this.DEtat = DEtat;
	}

	@Column(name = "ID_DUNNING", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDunning() {
		return this.idDunning;
	}

	public void setIdDunning(BigDecimal idDunning) {
		this.idDunning = idDunning;
	}

	@Column(name = "NO_OT_DUNN", nullable = false, precision = 6, scale = 0)
	public int getNoOtDunn() {
		return this.noOtDunn;
	}

	public void setNoOtDunn(int noOtDunn) {
		this.noOtDunn = noOtDunn;
	}

	@Column(name = "D_ETAT", nullable = false, length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DunningOtSuiviId))
			return false;
		DunningOtSuiviId castOther = (DunningOtSuiviId) other;

		return ((this.getIdDunning() == castOther.getIdDunning()) || (this.getIdDunning() != null
				&& castOther.getIdDunning() != null && this.getIdDunning().equals(castOther.getIdDunning())))
				&& (this.getNoOtDunn() == castOther.getNoOtDunn())
				&& ((this.getDEtat() == castOther.getDEtat()) || (this.getDEtat() != null
						&& castOther.getDEtat() != null && this.getDEtat().equals(castOther.getDEtat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDunning() == null ? 0 : this.getIdDunning().hashCode());
		result = 37 * result + this.getNoOtDunn();
		result = 37 * result + (getDEtat() == null ? 0 : this.getDEtat().hashCode());
		return result;
	}

}
