package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DunningPropSuivi generated by hbm2java
 */
@Entity
@Table(name = "DUNNING_PROP_SUIVI", schema = "TOM")
public class DunningPropSuivi implements java.io.Serializable {

	private DunningPropSuiviId id;
	private DunningOtProp dunningOtProp;
	private String valeur;
	private String idValeur;
	private String comm;
	private Date DModif;
	private String loginModif;

	public DunningPropSuivi() {
	}

	public DunningPropSuivi(DunningPropSuiviId id, DunningOtProp dunningOtProp) {
		this.id = id;
		this.dunningOtProp = dunningOtProp;
	}

	public DunningPropSuivi(DunningPropSuiviId id, DunningOtProp dunningOtProp, String valeur, String idValeur,
			String comm, Date DModif, String loginModif) {
		this.id = id;
		this.dunningOtProp = dunningOtProp;
		this.valeur = valeur;
		this.idValeur = idValeur;
		this.comm = comm;
		this.DModif = DModif;
		this.loginModif = loginModif;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDunning", column = @Column(name = "ID_DUNNING", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noOtDunn", column = @Column(name = "NO_OT_DUNN", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "CProp", column = @Column(name = "C_PROP", nullable = false, length = 50)),
			@AttributeOverride(name = "groupe", column = @Column(name = "GROUPE", nullable = false, length = 50)),
			@AttributeOverride(name = "DSuivi", column = @Column(name = "D_SUIVI", nullable = false, length = 11)) })
	public DunningPropSuiviId getId() {
		return this.id;
	}

	public void setId(DunningPropSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_DUNNING", referencedColumnName = "ID_DUNNING", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NO_OT_DUNN", referencedColumnName = "NO_OT_DUNN", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "C_PROP", referencedColumnName = "C_PROP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "GROUPE", referencedColumnName = "GROUPE", nullable = false, insertable = false, updatable = false) })
	public DunningOtProp getDunningOtProp() {
		return this.dunningOtProp;
	}

	public void setDunningOtProp(DunningOtProp dunningOtProp) {
		this.dunningOtProp = dunningOtProp;
	}

	@Column(name = "VALEUR", length = 200)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "ID_VALEUR", length = 100)
	public String getIdValeur() {
		return this.idValeur;
	}

	public void setIdValeur(String idValeur) {
		this.idValeur = idValeur;
	}

	@Column(name = "COMM", length = 500)
	public String getComm() {
		return this.comm;
	}

	public void setComm(String comm) {
		this.comm = comm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_MODIF", length = 11)
	public Date getDModif() {
		return this.DModif;
	}

	public void setDModif(Date DModif) {
		this.DModif = DModif;
	}

	@Column(name = "LOGIN_MODIF", length = 20)
	public String getLoginModif() {
		return this.loginModif;
	}

	public void setLoginModif(String loginModif) {
		this.loginModif = loginModif;
	}

}
