package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DunningOt generated by hbm2java
 */
@Entity
@Table(name = "DUNNING_OT", schema = "TOM")
public class DunningOt implements java.io.Serializable {

	private DunningOtId id;
	private Dunning dunning;
	private Equipe equipe;
	private PrmOtEtat prmOtEtat;
	private PrmOtType prmOtType;
	private Unite unite;
	private String comm;
	private Date DCreation;
	private Date DAffectation;
	private Date DEtat;
	private String loginEtat;
	private Date DFinReelle;
	private Date DFinPrevue;
	private Set<DunningOtProp> dunningOtProps = new HashSet<DunningOtProp>(0);
	private Set<DunningOtSuivi> dunningOtSuivis = new HashSet<DunningOtSuivi>(0);

	public DunningOt() {
	}

	public DunningOt(DunningOtId id, Dunning dunning, PrmOtEtat prmOtEtat, PrmOtType prmOtType, Unite unite,
			Date DCreation, Date DEtat) {
		this.id = id;
		this.dunning = dunning;
		this.prmOtEtat = prmOtEtat;
		this.prmOtType = prmOtType;
		this.unite = unite;
		this.DCreation = DCreation;
		this.DEtat = DEtat;
	}

	public DunningOt(DunningOtId id, Dunning dunning, Equipe equipe, PrmOtEtat prmOtEtat, PrmOtType prmOtType,
			Unite unite, String comm, Date DCreation, Date DAffectation, Date DEtat, String loginEtat, Date DFinReelle,
			Date DFinPrevue, Set<DunningOtProp> dunningOtProps, Set<DunningOtSuivi> dunningOtSuivis) {
		this.id = id;
		this.dunning = dunning;
		this.equipe = equipe;
		this.prmOtEtat = prmOtEtat;
		this.prmOtType = prmOtType;
		this.unite = unite;
		this.comm = comm;
		this.DCreation = DCreation;
		this.DAffectation = DAffectation;
		this.DEtat = DEtat;
		this.loginEtat = loginEtat;
		this.DFinReelle = DFinReelle;
		this.DFinPrevue = DFinPrevue;
		this.dunningOtProps = dunningOtProps;
		this.dunningOtSuivis = dunningOtSuivis;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDunning", column = @Column(name = "ID_DUNNING", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noOtDunn", column = @Column(name = "NO_OT_DUNN", nullable = false, precision = 6, scale = 0)) })
	public DunningOtId getId() {
		return this.id;
	}

	public void setId(DunningOtId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DUNNING", nullable = false, insertable = false, updatable = false)
	public Dunning getDunning() {
		return this.dunning;
	}

	public void setDunning(Dunning dunning) {
		this.dunning = dunning;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EQUIPE")
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmOtEtat getPrmOtEtat() {
		return this.prmOtEtat;
	}

	public void setPrmOtEtat(PrmOtEtat prmOtEtat) {
		this.prmOtEtat = prmOtEtat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_OT", nullable = false)
	public PrmOtType getPrmOtType() {
		return this.prmOtType;
	}

	public void setPrmOtType(PrmOtType prmOtType) {
		this.prmOtType = prmOtType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_UNITE", nullable = false)
	public Unite getUnite() {
		return this.unite;
	}

	public void setUnite(Unite unite) {
		this.unite = unite;
	}

	@Column(name = "COMM", length = 500)
	public String getComm() {
		return this.comm;
	}

	public void setComm(String comm) {
		this.comm = comm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CREATION", nullable = false, length = 11)
	public Date getDCreation() {
		return this.DCreation;
	}

	public void setDCreation(Date DCreation) {
		this.DCreation = DCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_AFFECTATION", length = 11)
	public Date getDAffectation() {
		return this.DAffectation;
	}

	public void setDAffectation(Date DAffectation) {
		this.DAffectation = DAffectation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ETAT", nullable = false, length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	@Column(name = "LOGIN_ETAT", length = 20)
	public String getLoginEtat() {
		return this.loginEtat;
	}

	public void setLoginEtat(String loginEtat) {
		this.loginEtat = loginEtat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_FIN_REELLE", length = 11)
	public Date getDFinReelle() {
		return this.DFinReelle;
	}

	public void setDFinReelle(Date DFinReelle) {
		this.DFinReelle = DFinReelle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_FIN_PREVUE", length = 11)
	public Date getDFinPrevue() {
		return this.DFinPrevue;
	}

	public void setDFinPrevue(Date DFinPrevue) {
		this.DFinPrevue = DFinPrevue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dunningOt")
	public Set<DunningOtProp> getDunningOtProps() {
		return this.dunningOtProps;
	}

	public void setDunningOtProps(Set<DunningOtProp> dunningOtProps) {
		this.dunningOtProps = dunningOtProps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dunningOt")
	public Set<DunningOtSuivi> getDunningOtSuivis() {
		return this.dunningOtSuivis;
	}

	public void setDunningOtSuivis(Set<DunningOtSuivi> dunningOtSuivis) {
		this.dunningOtSuivis = dunningOtSuivis;
	}

}
