package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EquipeValidId generated by hbm2java
 */
@Embeddable
public class EquipeValidId implements java.io.Serializable {

	private BigDecimal idEquipe;
	private String login;

	public EquipeValidId() {
	}

	public EquipeValidId(BigDecimal idEquipe, String login) {
		this.idEquipe = idEquipe;
		this.login = login;
	}

	@Column(name = "ID_EQUIPE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(BigDecimal idEquipe) {
		this.idEquipe = idEquipe;
	}

	@Column(name = "LOGIN", nullable = false, length = 20)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EquipeValidId))
			return false;
		EquipeValidId castOther = (EquipeValidId) other;

		return ((this.getIdEquipe() == castOther.getIdEquipe()) || (this.getIdEquipe() != null
				&& castOther.getIdEquipe() != null && this.getIdEquipe().equals(castOther.getIdEquipe())))
				&& ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null
						&& castOther.getLogin() != null && this.getLogin().equals(castOther.getLogin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdEquipe() == null ? 0 : this.getIdEquipe().hashCode());
		result = 37 * result + (getLogin() == null ? 0 : this.getLogin().hashCode());
		return result;
	}

}
