package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EquipeRess generated by hbm2java
 */
@Entity
@Table(name = "EQUIPE_RESS", schema = "TOM")
public class EquipeRess implements java.io.Serializable {

	private BigDecimal idRess;
	private Agent agent;
	private Equipe equipe;
	private SousTraitant sousTraitant;
	private Date DDebAffect;
	private Date DFinAffect;
	private String obs;
	private Date DCreation;
	private String loginCreation;
	private Date DModif;
	private String loginModif;

	public EquipeRess() {
	}

	public EquipeRess(BigDecimal idRess, Equipe equipe, Date DDebAffect) {
		this.idRess = idRess;
		this.equipe = equipe;
		this.DDebAffect = DDebAffect;
	}

	public EquipeRess(BigDecimal idRess, Agent agent, Equipe equipe, SousTraitant sousTraitant, Date DDebAffect,
			Date DFinAffect, String obs, Date DCreation, String loginCreation, Date DModif, String loginModif) {
		this.idRess = idRess;
		this.agent = agent;
		this.equipe = equipe;
		this.sousTraitant = sousTraitant;
		this.DDebAffect = DDebAffect;
		this.DFinAffect = DFinAffect;
		this.obs = obs;
		this.DCreation = DCreation;
		this.loginCreation = loginCreation;
		this.DModif = DModif;
		this.loginModif = loginModif;
	}

	@Id

	@Column(name = "ID_RESS", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdRess() {
		return this.idRess;
	}

	public void setIdRess(BigDecimal idRess) {
		this.idRess = idRess;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATRICULE")
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EQUIPE", nullable = false)
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_STRAITANT")
	public SousTraitant getSousTraitant() {
		return this.sousTraitant;
	}

	public void setSousTraitant(SousTraitant sousTraitant) {
		this.sousTraitant = sousTraitant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_DEB_AFFECT", nullable = false, length = 7)
	public Date getDDebAffect() {
		return this.DDebAffect;
	}

	public void setDDebAffect(Date DDebAffect) {
		this.DDebAffect = DDebAffect;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_FIN_AFFECT", length = 7)
	public Date getDFinAffect() {
		return this.DFinAffect;
	}

	public void setDFinAffect(Date DFinAffect) {
		this.DFinAffect = DFinAffect;
	}

	@Column(name = "OBS", length = 500)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CREATION", length = 11)
	public Date getDCreation() {
		return this.DCreation;
	}

	public void setDCreation(Date DCreation) {
		this.DCreation = DCreation;
	}

	@Column(name = "LOGIN_CREATION", length = 20)
	public String getLoginCreation() {
		return this.loginCreation;
	}

	public void setLoginCreation(String loginCreation) {
		this.loginCreation = loginCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_MODIF", length = 11)
	public Date getDModif() {
		return this.DModif;
	}

	public void setDModif(Date DModif) {
		this.DModif = DModif;
	}

	@Column(name = "LOGIN_MODIF", length = 20)
	public String getLoginModif() {
		return this.loginModif;
	}

	public void setLoginModif(String loginModif) {
		this.loginModif = loginModif;
	}

}
