package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FailedRequestsId generated by hbm2java
 */
@Embeddable
public class FailedRequestsId implements java.io.Serializable {

	private BigDecimal idRequest;
	private Date DRequest;
	private String type;
	private String sens;
	private String ws;
	private String methode;
	private String sysAppele;
	private String CRetour;
	private String operation;
	private Clob txtLog;
	private Clob request;
	private Clob response;
	private BigDecimal idDem;
	private String bpmUid;
	private String refDemSrc;

	public FailedRequestsId() {
	}

	public FailedRequestsId(BigDecimal idRequest, Date DRequest, String type, String sens, String ws, String methode,
			String sysAppele, String CRetour, String operation, Clob txtLog, Clob request, Clob response,
			BigDecimal idDem, String bpmUid, String refDemSrc) {
		this.idRequest = idRequest;
		this.DRequest = DRequest;
		this.type = type;
		this.sens = sens;
		this.ws = ws;
		this.methode = methode;
		this.sysAppele = sysAppele;
		this.CRetour = CRetour;
		this.operation = operation;
		this.txtLog = txtLog;
		this.request = request;
		this.response = response;
		this.idDem = idDem;
		this.bpmUid = bpmUid;
		this.refDemSrc = refDemSrc;
	}

	@Column(name = "ID_REQUEST", precision = 22, scale = 0)
	public BigDecimal getIdRequest() {
		return this.idRequest;
	}

	public void setIdRequest(BigDecimal idRequest) {
		this.idRequest = idRequest;
	}

	@Column(name = "D_REQUEST", length = 11)
	public Date getDRequest() {
		return this.DRequest;
	}

	public void setDRequest(Date DRequest) {
		this.DRequest = DRequest;
	}

	@Column(name = "TYPE", length = 3)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "SENS", length = 3)
	public String getSens() {
		return this.sens;
	}

	public void setSens(String sens) {
		this.sens = sens;
	}

	@Column(name = "WS", length = 100)
	public String getWs() {
		return this.ws;
	}

	public void setWs(String ws) {
		this.ws = ws;
	}

	@Column(name = "METHODE", length = 100)
	public String getMethode() {
		return this.methode;
	}

	public void setMethode(String methode) {
		this.methode = methode;
	}

	@Column(name = "SYS_APPELE", length = 50)
	public String getSysAppele() {
		return this.sysAppele;
	}

	public void setSysAppele(String sysAppele) {
		this.sysAppele = sysAppele;
	}

	@Column(name = "C_RETOUR", length = 20)
	public String getCRetour() {
		return this.CRetour;
	}

	public void setCRetour(String CRetour) {
		this.CRetour = CRetour;
	}

	@Column(name = "OPERATION", length = 50)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "TXT_LOG")
	public Clob getTxtLog() {
		return this.txtLog;
	}

	public void setTxtLog(Clob txtLog) {
		this.txtLog = txtLog;
	}

	@Column(name = "REQUEST")
	public Clob getRequest() {
		return this.request;
	}

	public void setRequest(Clob request) {
		this.request = request;
	}

	@Column(name = "RESPONSE")
	public Clob getResponse() {
		return this.response;
	}

	public void setResponse(Clob response) {
		this.response = response;
	}

	@Column(name = "ID_DEM", precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "BPM_UID", length = 50)
	public String getBpmUid() {
		return this.bpmUid;
	}

	public void setBpmUid(String bpmUid) {
		this.bpmUid = bpmUid;
	}

	@Column(name = "REF_DEM_SRC", length = 100)
	public String getRefDemSrc() {
		return this.refDemSrc;
	}

	public void setRefDemSrc(String refDemSrc) {
		this.refDemSrc = refDemSrc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FailedRequestsId))
			return false;
		FailedRequestsId castOther = (FailedRequestsId) other;

		return ((this.getIdRequest() == castOther.getIdRequest()) || (this.getIdRequest() != null
				&& castOther.getIdRequest() != null && this.getIdRequest().equals(castOther.getIdRequest())))
				&& ((this.getDRequest() == castOther.getDRequest()) || (this.getDRequest() != null
						&& castOther.getDRequest() != null && this.getDRequest().equals(castOther.getDRequest())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getSens() == castOther.getSens()) || (this.getSens() != null && castOther.getSens() != null
						&& this.getSens().equals(castOther.getSens())))
				&& ((this.getWs() == castOther.getWs()) || (this.getWs() != null && castOther.getWs() != null
						&& this.getWs().equals(castOther.getWs())))
				&& ((this.getMethode() == castOther.getMethode()) || (this.getMethode() != null
						&& castOther.getMethode() != null && this.getMethode().equals(castOther.getMethode())))
				&& ((this.getSysAppele() == castOther.getSysAppele()) || (this.getSysAppele() != null
						&& castOther.getSysAppele() != null && this.getSysAppele().equals(castOther.getSysAppele())))
				&& ((this.getCRetour() == castOther.getCRetour()) || (this.getCRetour() != null
						&& castOther.getCRetour() != null && this.getCRetour().equals(castOther.getCRetour())))
				&& ((this.getOperation() == castOther.getOperation()) || (this.getOperation() != null
						&& castOther.getOperation() != null && this.getOperation().equals(castOther.getOperation())))
				&& ((this.getTxtLog() == castOther.getTxtLog()) || (this.getTxtLog() != null
						&& castOther.getTxtLog() != null && this.getTxtLog().equals(castOther.getTxtLog())))
				&& ((this.getRequest() == castOther.getRequest()) || (this.getRequest() != null
						&& castOther.getRequest() != null && this.getRequest().equals(castOther.getRequest())))
				&& ((this.getResponse() == castOther.getResponse()) || (this.getResponse() != null
						&& castOther.getResponse() != null && this.getResponse().equals(castOther.getResponse())))
				&& ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null
						&& castOther.getIdDem() != null && this.getIdDem().equals(castOther.getIdDem())))
				&& ((this.getBpmUid() == castOther.getBpmUid()) || (this.getBpmUid() != null
						&& castOther.getBpmUid() != null && this.getBpmUid().equals(castOther.getBpmUid())))
				&& ((this.getRefDemSrc() == castOther.getRefDemSrc()) || (this.getRefDemSrc() != null
						&& castOther.getRefDemSrc() != null && this.getRefDemSrc().equals(castOther.getRefDemSrc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdRequest() == null ? 0 : this.getIdRequest().hashCode());
		result = 37 * result + (getDRequest() == null ? 0 : this.getDRequest().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getSens() == null ? 0 : this.getSens().hashCode());
		result = 37 * result + (getWs() == null ? 0 : this.getWs().hashCode());
		result = 37 * result + (getMethode() == null ? 0 : this.getMethode().hashCode());
		result = 37 * result + (getSysAppele() == null ? 0 : this.getSysAppele().hashCode());
		result = 37 * result + (getCRetour() == null ? 0 : this.getCRetour().hashCode());
		result = 37 * result + (getOperation() == null ? 0 : this.getOperation().hashCode());
		result = 37 * result + (getTxtLog() == null ? 0 : this.getTxtLog().hashCode());
		result = 37 * result + (getRequest() == null ? 0 : this.getRequest().hashCode());
		result = 37 * result + (getResponse() == null ? 0 : this.getResponse().hashCode());
		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + (getBpmUid() == null ? 0 : this.getBpmUid().hashCode());
		result = 37 * result + (getRefDemSrc() == null ? 0 : this.getRefDemSrc().hashCode());
		return result;
	}

}
