package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FonctionProftypeId generated by hbm2java
 */
@Embeddable
public class FonctionProftypeId implements java.io.Serializable {

	private String CTypeProfil;
	private String CFonction;

	public FonctionProftypeId() {
	}

	public FonctionProftypeId(String CTypeProfil, String CFonction) {
		this.CTypeProfil = CTypeProfil;
		this.CFonction = CFonction;
	}

	@Column(name = "C_TYPE_PROFIL", nullable = false, length = 20)
	public String getCTypeProfil() {
		return this.CTypeProfil;
	}

	public void setCTypeProfil(String CTypeProfil) {
		this.CTypeProfil = CTypeProfil;
	}

	@Column(name = "C_FONCTION", nullable = false, length = 20)
	public String getCFonction() {
		return this.CFonction;
	}

	public void setCFonction(String CFonction) {
		this.CFonction = CFonction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FonctionProftypeId))
			return false;
		FonctionProftypeId castOther = (FonctionProftypeId) other;

		return ((this.getCTypeProfil() == castOther.getCTypeProfil()) || (this.getCTypeProfil() != null
				&& castOther.getCTypeProfil() != null && this.getCTypeProfil().equals(castOther.getCTypeProfil())))
				&& ((this.getCFonction() == castOther.getCFonction()) || (this.getCFonction() != null
						&& castOther.getCFonction() != null && this.getCFonction().equals(castOther.getCFonction())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCTypeProfil() == null ? 0 : this.getCTypeProfil().hashCode());
		result = 37 * result + (getCFonction() == null ? 0 : this.getCFonction().hashCode());
		return result;
	}

}
