package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fonction generated by hbm2java
 */
@Entity
@Table(name = "FONCTION", schema = "TOM")
public class Fonction implements java.io.Serializable {

	private String CFonction;
	private Fonction fonction;
	private String fonction_1;
	private String type;
	private String cle;
	private String page;
	private String controleur;
	private BigDecimal ordre;
	private boolean FLog;
	private Set<Fonction> fonctions = new HashSet<Fonction>(0);
	private Set<Profil> profils = new HashSet<Profil>(0);
	private Set<FonctionProftype> fonctionProftypes = new HashSet<FonctionProftype>(0);

	public Fonction() {
	}

	public Fonction(String CFonction, String fonction_1, String type, BigDecimal ordre, boolean FLog) {
		this.CFonction = CFonction;
		this.fonction_1 = fonction_1;
		this.type = type;
		this.ordre = ordre;
		this.FLog = FLog;
	}

	public Fonction(String CFonction, Fonction fonction, String fonction_1, String type, String cle, String page,
			String controleur, BigDecimal ordre, boolean FLog, Set<Fonction> fonctions, Set<Profil> profils,
			Set<FonctionProftype> fonctionProftypes) {
		this.CFonction = CFonction;
		this.fonction = fonction;
		this.fonction_1 = fonction_1;
		this.type = type;
		this.cle = cle;
		this.page = page;
		this.controleur = controleur;
		this.ordre = ordre;
		this.FLog = FLog;
		this.fonctions = fonctions;
		this.profils = profils;
		this.fonctionProftypes = fonctionProftypes;
	}

	@Id

	@Column(name = "C_FONCTION", unique = true, nullable = false, length = 20)
	public String getCFonction() {
		return this.CFonction;
	}

	public void setCFonction(String CFonction) {
		this.CFonction = CFonction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_FONCTION_MERE")
	public Fonction getFonction() {
		return this.fonction;
	}

	public void setFonction(Fonction fonction) {
		this.fonction = fonction;
	}

	@Column(name = "FONCTION", nullable = false, length = 100)
	public String getFonction_1() {
		return this.fonction_1;
	}

	public void setFonction_1(String fonction_1) {
		this.fonction_1 = fonction_1;
	}

	@Column(name = "TYPE", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "CLE", length = 100)
	public String getCle() {
		return this.cle;
	}

	public void setCle(String cle) {
		this.cle = cle;
	}

	@Column(name = "PAGE", length = 200)
	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	@Column(name = "CONTROLEUR", length = 50)
	public String getControleur() {
		return this.controleur;
	}

	public void setControleur(String controleur) {
		this.controleur = controleur;
	}

	@Column(name = "ORDRE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOrdre() {
		return this.ordre;
	}

	public void setOrdre(BigDecimal ordre) {
		this.ordre = ordre;
	}

	@Column(name = "F_LOG", nullable = false, precision = 1, scale = 0)
	public boolean isFLog() {
		return this.FLog;
	}

	public void setFLog(boolean FLog) {
		this.FLog = FLog;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fonction")
	public Set<Fonction> getFonctions() {
		return this.fonctions;
	}

	public void setFonctions(Set<Fonction> fonctions) {
		this.fonctions = fonctions;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "fonctions")
	public Set<Profil> getProfils() {
		return this.profils;
	}

	public void setProfils(Set<Profil> profils) {
		this.profils = profils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fonction")
	public Set<FonctionProftype> getFonctionProftypes() {
		return this.fonctionProftypes;
	}

	public void setFonctionProftypes(Set<FonctionProftype> fonctionProftypes) {
		this.fonctionProftypes = fonctionProftypes;
	}

}
