package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImpInSuspId generated by hbm2java
 */
@Embeddable
public class ImpInSuspId implements java.io.Serializable {

	private BigDecimal idImpLog;
	private long noLigne;

	public ImpInSuspId() {
	}

	public ImpInSuspId(BigDecimal idImpLog, long noLigne) {
		this.idImpLog = idImpLog;
		this.noLigne = noLigne;
	}

	@Column(name = "ID_IMP_LOG", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdImpLog() {
		return this.idImpLog;
	}

	public void setIdImpLog(BigDecimal idImpLog) {
		this.idImpLog = idImpLog;
	}

	@Column(name = "NO_LIGNE", nullable = false, precision = 15, scale = 0)
	public long getNoLigne() {
		return this.noLigne;
	}

	public void setNoLigne(long noLigne) {
		this.noLigne = noLigne;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImpInSuspId))
			return false;
		ImpInSuspId castOther = (ImpInSuspId) other;

		return ((this.getIdImpLog() == castOther.getIdImpLog()) || (this.getIdImpLog() != null
				&& castOther.getIdImpLog() != null && this.getIdImpLog().equals(castOther.getIdImpLog())))
				&& (this.getNoLigne() == castOther.getNoLigne());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdImpLog() == null ? 0 : this.getIdImpLog().hashCode());
		result = 37 * result + (int) this.getNoLigne();
		return result;
	}

}
