package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ImpLog generated by hbm2java
 */
@Entity
@Table(name = "IMP_LOG", schema = "TOM")
public class ImpLog implements java.io.Serializable {

	private BigDecimal idImpLog;
	private String nomFichier;
	private String sysSource;
	private String objet;
	private Date DCreation;
	private Date DDebImp;
	private Date DFinImp;
	private Date DDebTrait;
	private int nbLigne;
	private Date DFinTrait;
	private int nbLigneImp;
	private int nbLigneTrait;
	private String etat;
	private String motif;
	private Set<ImpInSusp> impInSusps = new HashSet<ImpInSusp>(0);

	public ImpLog() {
	}

	public ImpLog(BigDecimal idImpLog, String nomFichier, String sysSource, String objet, Date DCreation, int nbLigne,
			int nbLigneImp, int nbLigneTrait, String etat) {
		this.idImpLog = idImpLog;
		this.nomFichier = nomFichier;
		this.sysSource = sysSource;
		this.objet = objet;
		this.DCreation = DCreation;
		this.nbLigne = nbLigne;
		this.nbLigneImp = nbLigneImp;
		this.nbLigneTrait = nbLigneTrait;
		this.etat = etat;
	}

	public ImpLog(BigDecimal idImpLog, String nomFichier, String sysSource, String objet, Date DCreation, Date DDebImp,
			Date DFinImp, Date DDebTrait, int nbLigne, Date DFinTrait, int nbLigneImp, int nbLigneTrait, String etat,
			String motif, Set<ImpInSusp> impInSusps) {
		this.idImpLog = idImpLog;
		this.nomFichier = nomFichier;
		this.sysSource = sysSource;
		this.objet = objet;
		this.DCreation = DCreation;
		this.DDebImp = DDebImp;
		this.DFinImp = DFinImp;
		this.DDebTrait = DDebTrait;
		this.nbLigne = nbLigne;
		this.DFinTrait = DFinTrait;
		this.nbLigneImp = nbLigneImp;
		this.nbLigneTrait = nbLigneTrait;
		this.etat = etat;
		this.motif = motif;
		this.impInSusps = impInSusps;
	}

	@Id

	@Column(name = "ID_IMP_LOG", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdImpLog() {
		return this.idImpLog;
	}

	public void setIdImpLog(BigDecimal idImpLog) {
		this.idImpLog = idImpLog;
	}

	@Column(name = "NOM_FICHIER", nullable = false, length = 50)
	public String getNomFichier() {
		return this.nomFichier;
	}

	public void setNomFichier(String nomFichier) {
		this.nomFichier = nomFichier;
	}

	@Column(name = "SYS_SOURCE", nullable = false, length = 20)
	public String getSysSource() {
		return this.sysSource;
	}

	public void setSysSource(String sysSource) {
		this.sysSource = sysSource;
	}

	@Column(name = "OBJET", nullable = false, length = 50)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CREATION", nullable = false, length = 11)
	public Date getDCreation() {
		return this.DCreation;
	}

	public void setDCreation(Date DCreation) {
		this.DCreation = DCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_DEB_IMP", length = 11)
	public Date getDDebImp() {
		return this.DDebImp;
	}

	public void setDDebImp(Date DDebImp) {
		this.DDebImp = DDebImp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_FIN_IMP", length = 11)
	public Date getDFinImp() {
		return this.DFinImp;
	}

	public void setDFinImp(Date DFinImp) {
		this.DFinImp = DFinImp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_DEB_TRAIT", length = 11)
	public Date getDDebTrait() {
		return this.DDebTrait;
	}

	public void setDDebTrait(Date DDebTrait) {
		this.DDebTrait = DDebTrait;
	}

	@Column(name = "NB_LIGNE", nullable = false, precision = 9, scale = 0)
	public int getNbLigne() {
		return this.nbLigne;
	}

	public void setNbLigne(int nbLigne) {
		this.nbLigne = nbLigne;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_FIN_TRAIT", length = 11)
	public Date getDFinTrait() {
		return this.DFinTrait;
	}

	public void setDFinTrait(Date DFinTrait) {
		this.DFinTrait = DFinTrait;
	}

	@Column(name = "NB_LIGNE_IMP", nullable = false, precision = 9, scale = 0)
	public int getNbLigneImp() {
		return this.nbLigneImp;
	}

	public void setNbLigneImp(int nbLigneImp) {
		this.nbLigneImp = nbLigneImp;
	}

	@Column(name = "NB_LIGNE_TRAIT", nullable = false, precision = 9, scale = 0)
	public int getNbLigneTrait() {
		return this.nbLigneTrait;
	}

	public void setNbLigneTrait(int nbLigneTrait) {
		this.nbLigneTrait = nbLigneTrait;
	}

	@Column(name = "ETAT", nullable = false, length = 1)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "MOTIF", length = 100)
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "impLog")
	public Set<ImpInSusp> getImpInSusps() {
		return this.impInSusps;
	}

	public void setImpInSusps(Set<ImpInSusp> impInSusps) {
		this.impInSusps = impInSusps;
	}

}
