package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jeton generated by hbm2java
 */
@Entity
@Table(name = "JETON", schema = "TOM")
public class Jeton implements java.io.Serializable {

	private String jeton;
	private String sysTarget;
	private String refDemSrc;
	private BigDecimal noOt;
	private String accessMode;
	private String vue;
	private String etat;
	private Date DCreation;

	public Jeton() {
	}

	public Jeton(String jeton, String sysTarget, String refDemSrc, BigDecimal noOt, String accessMode, String vue,
			String etat, Date DCreation) {
		this.jeton = jeton;
		this.sysTarget = sysTarget;
		this.refDemSrc = refDemSrc;
		this.noOt = noOt;
		this.accessMode = accessMode;
		this.vue = vue;
		this.etat = etat;
		this.DCreation = DCreation;
	}

	@Id

	@Column(name = "JETON", unique = true, nullable = false, length = 50)
	public String getJeton() {
		return this.jeton;
	}

	public void setJeton(String jeton) {
		this.jeton = jeton;
	}

	@Column(name = "SYS_TARGET", nullable = false, length = 50)
	public String getSysTarget() {
		return this.sysTarget;
	}

	public void setSysTarget(String sysTarget) {
		this.sysTarget = sysTarget;
	}

	@Column(name = "REF_DEM_SRC", nullable = false, length = 200)
	public String getRefDemSrc() {
		return this.refDemSrc;
	}

	public void setRefDemSrc(String refDemSrc) {
		this.refDemSrc = refDemSrc;
	}

	@Column(name = "NO_OT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNoOt() {
		return this.noOt;
	}

	public void setNoOt(BigDecimal noOt) {
		this.noOt = noOt;
	}

	@Column(name = "ACCESS_MODE", nullable = false, length = 20)
	public String getAccessMode() {
		return this.accessMode;
	}

	public void setAccessMode(String accessMode) {
		this.accessMode = accessMode;
	}

	@Column(name = "VUE", nullable = false, length = 20)
	public String getVue() {
		return this.vue;
	}

	public void setVue(String vue) {
		this.vue = vue;
	}

	@Column(name = "ETAT", nullable = false, length = 50)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CREATION", nullable = false, length = 11)
	public Date getDCreation() {
		return this.DCreation;
	}

	public void setDCreation(Date DCreation) {
		this.DCreation = DCreation;
	}

}
