package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JournalAcces generated by hbm2java
 */
@Entity
@Table(name = "JOURNAL_ACCES", schema = "TOM")
public class JournalAcces implements java.io.Serializable {

	private BigDecimal idLog;
	private Date DAcces;
	private String login;
	private String nomUtil;
	private String matricule;
	private BigDecimal idProfil;
	private String nomProfil;
	private String CTypeProfil;
	private String typeProfil;
	private Boolean FCentral;
	private String typAcces;
	private Boolean FAccesApp;
	private String pwdErr;
	private String posteAcces;
	private String adresseIp;
	private String droitAcces;
	private String CFonction;
	private String fonction;

	public JournalAcces() {
	}

	public JournalAcces(BigDecimal idLog, Date DAcces, String typAcces) {
		this.idLog = idLog;
		this.DAcces = DAcces;
		this.typAcces = typAcces;
	}

	public JournalAcces(BigDecimal idLog, Date DAcces, String login, String nomUtil, String matricule,
			BigDecimal idProfil, String nomProfil, String CTypeProfil, String typeProfil, Boolean FCentral,
			String typAcces, Boolean FAccesApp, String pwdErr, String posteAcces, String adresseIp, String droitAcces,
			String CFonction, String fonction) {
		this.idLog = idLog;
		this.DAcces = DAcces;
		this.login = login;
		this.nomUtil = nomUtil;
		this.matricule = matricule;
		this.idProfil = idProfil;
		this.nomProfil = nomProfil;
		this.CTypeProfil = CTypeProfil;
		this.typeProfil = typeProfil;
		this.FCentral = FCentral;
		this.typAcces = typAcces;
		this.FAccesApp = FAccesApp;
		this.pwdErr = pwdErr;
		this.posteAcces = posteAcces;
		this.adresseIp = adresseIp;
		this.droitAcces = droitAcces;
		this.CFonction = CFonction;
		this.fonction = fonction;
	}

	@Id

	@Column(name = "ID_LOG", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdLog() {
		return this.idLog;
	}

	public void setIdLog(BigDecimal idLog) {
		this.idLog = idLog;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ACCES", nullable = false, length = 11)
	public Date getDAcces() {
		return this.DAcces;
	}

	public void setDAcces(Date DAcces) {
		this.DAcces = DAcces;
	}

	@Column(name = "LOGIN", length = 20)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "NOM_UTIL", length = 200)
	public String getNomUtil() {
		return this.nomUtil;
	}

	public void setNomUtil(String nomUtil) {
		this.nomUtil = nomUtil;
	}

	@Column(name = "MATRICULE", length = 20)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "ID_PROFIL", precision = 22, scale = 0)
	public BigDecimal getIdProfil() {
		return this.idProfil;
	}

	public void setIdProfil(BigDecimal idProfil) {
		this.idProfil = idProfil;
	}

	@Column(name = "NOM_PROFIL", length = 200)
	public String getNomProfil() {
		return this.nomProfil;
	}

	public void setNomProfil(String nomProfil) {
		this.nomProfil = nomProfil;
	}

	@Column(name = "C_TYPE_PROFIL", length = 20)
	public String getCTypeProfil() {
		return this.CTypeProfil;
	}

	public void setCTypeProfil(String CTypeProfil) {
		this.CTypeProfil = CTypeProfil;
	}

	@Column(name = "TYPE_PROFIL", length = 100)
	public String getTypeProfil() {
		return this.typeProfil;
	}

	public void setTypeProfil(String typeProfil) {
		this.typeProfil = typeProfil;
	}

	@Column(name = "F_CENTRAL", precision = 1, scale = 0)
	public Boolean getFCentral() {
		return this.FCentral;
	}

	public void setFCentral(Boolean FCentral) {
		this.FCentral = FCentral;
	}

	@Column(name = "TYP_ACCES", nullable = false, length = 1)
	public String getTypAcces() {
		return this.typAcces;
	}

	public void setTypAcces(String typAcces) {
		this.typAcces = typAcces;
	}

	@Column(name = "F_ACCES_APP", precision = 1, scale = 0)
	public Boolean getFAccesApp() {
		return this.FAccesApp;
	}

	public void setFAccesApp(Boolean FAccesApp) {
		this.FAccesApp = FAccesApp;
	}

	@Column(name = "PWD_ERR", length = 20)
	public String getPwdErr() {
		return this.pwdErr;
	}

	public void setPwdErr(String pwdErr) {
		this.pwdErr = pwdErr;
	}

	@Column(name = "POSTE_ACCES", length = 100)
	public String getPosteAcces() {
		return this.posteAcces;
	}

	public void setPosteAcces(String posteAcces) {
		this.posteAcces = posteAcces;
	}

	@Column(name = "ADRESSE_IP", length = 20)
	public String getAdresseIp() {
		return this.adresseIp;
	}

	public void setAdresseIp(String adresseIp) {
		this.adresseIp = adresseIp;
	}

	@Column(name = "DROIT_ACCES", length = 1500)
	public String getDroitAcces() {
		return this.droitAcces;
	}

	public void setDroitAcces(String droitAcces) {
		this.droitAcces = droitAcces;
	}

	@Column(name = "C_FONCTION", length = 20)
	public String getCFonction() {
		return this.CFonction;
	}

	public void setCFonction(String CFonction) {
		this.CFonction = CFonction;
	}

	@Column(name = "FONCTION", length = 100)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

}
