package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocaliteMigId generated by hbm2java
 */
@Embeddable
public class LocaliteMigId implements java.io.Serializable {

	private String codeRegionSyratt;
	private String region;
	private String CDelegation;
	private String deleg;
	private String CLoc;
	private String loc;
	private String CPostal;
	private String myaddressecode;
	private String myaddressenom;

	public LocaliteMigId() {
	}

	public LocaliteMigId(String codeRegionSyratt, String region, String CDelegation, String deleg, String CLoc,
			String loc, String CPostal, String myaddressecode, String myaddressenom) {
		this.codeRegionSyratt = codeRegionSyratt;
		this.region = region;
		this.CDelegation = CDelegation;
		this.deleg = deleg;
		this.CLoc = CLoc;
		this.loc = loc;
		this.CPostal = CPostal;
		this.myaddressecode = myaddressecode;
		this.myaddressenom = myaddressenom;
	}

	@Column(name = "CODE_REGION_SYRATT", length = 200)
	public String getCodeRegionSyratt() {
		return this.codeRegionSyratt;
	}

	public void setCodeRegionSyratt(String codeRegionSyratt) {
		this.codeRegionSyratt = codeRegionSyratt;
	}

	@Column(name = "REGION", length = 200)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "C_DELEGATION", length = 200)
	public String getCDelegation() {
		return this.CDelegation;
	}

	public void setCDelegation(String CDelegation) {
		this.CDelegation = CDelegation;
	}

	@Column(name = "DELEG", length = 200)
	public String getDeleg() {
		return this.deleg;
	}

	public void setDeleg(String deleg) {
		this.deleg = deleg;
	}

	@Column(name = "C_LOC", length = 200)
	public String getCLoc() {
		return this.CLoc;
	}

	public void setCLoc(String CLoc) {
		this.CLoc = CLoc;
	}

	@Column(name = "LOC", length = 200)
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	@Column(name = "C_POSTAL", length = 200)
	public String getCPostal() {
		return this.CPostal;
	}

	public void setCPostal(String CPostal) {
		this.CPostal = CPostal;
	}

	@Column(name = "MYADDRESSECODE", length = 200)
	public String getMyaddressecode() {
		return this.myaddressecode;
	}

	public void setMyaddressecode(String myaddressecode) {
		this.myaddressecode = myaddressecode;
	}

	@Column(name = "MYADDRESSENOM", length = 200)
	public String getMyaddressenom() {
		return this.myaddressenom;
	}

	public void setMyaddressenom(String myaddressenom) {
		this.myaddressenom = myaddressenom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocaliteMigId))
			return false;
		LocaliteMigId castOther = (LocaliteMigId) other;

		return ((this.getCodeRegionSyratt() == castOther.getCodeRegionSyratt())
				|| (this.getCodeRegionSyratt() != null && castOther.getCodeRegionSyratt() != null
						&& this.getCodeRegionSyratt().equals(castOther.getCodeRegionSyratt())))
				&& ((this.getRegion() == castOther.getRegion()) || (this.getRegion() != null
						&& castOther.getRegion() != null && this.getRegion().equals(castOther.getRegion())))
				&& ((this.getCDelegation() == castOther.getCDelegation())
						|| (this.getCDelegation() != null && castOther.getCDelegation() != null
								&& this.getCDelegation().equals(castOther.getCDelegation())))
				&& ((this.getDeleg() == castOther.getDeleg()) || (this.getDeleg() != null
						&& castOther.getDeleg() != null && this.getDeleg().equals(castOther.getDeleg())))
				&& ((this.getCLoc() == castOther.getCLoc()) || (this.getCLoc() != null && castOther.getCLoc() != null
						&& this.getCLoc().equals(castOther.getCLoc())))
				&& ((this.getLoc() == castOther.getLoc()) || (this.getLoc() != null && castOther.getLoc() != null
						&& this.getLoc().equals(castOther.getLoc())))
				&& ((this.getCPostal() == castOther.getCPostal()) || (this.getCPostal() != null
						&& castOther.getCPostal() != null && this.getCPostal().equals(castOther.getCPostal())))
				&& ((this.getMyaddressecode() == castOther.getMyaddressecode())
						|| (this.getMyaddressecode() != null && castOther.getMyaddressecode() != null
								&& this.getMyaddressecode().equals(castOther.getMyaddressecode())))
				&& ((this.getMyaddressenom() == castOther.getMyaddressenom())
						|| (this.getMyaddressenom() != null && castOther.getMyaddressenom() != null
								&& this.getMyaddressenom().equals(castOther.getMyaddressenom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodeRegionSyratt() == null ? 0 : this.getCodeRegionSyratt().hashCode());
		result = 37 * result + (getRegion() == null ? 0 : this.getRegion().hashCode());
		result = 37 * result + (getCDelegation() == null ? 0 : this.getCDelegation().hashCode());
		result = 37 * result + (getDeleg() == null ? 0 : this.getDeleg().hashCode());
		result = 37 * result + (getCLoc() == null ? 0 : this.getCLoc().hashCode());
		result = 37 * result + (getLoc() == null ? 0 : this.getLoc().hashCode());
		result = 37 * result + (getCPostal() == null ? 0 : this.getCPostal().hashCode());
		result = 37 * result + (getMyaddressecode() == null ? 0 : this.getMyaddressecode().hashCode());
		result = 37 * result + (getMyaddressenom() == null ? 0 : this.getMyaddressenom().hashCode());
		return result;
	}

}
