package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogOld generated by hbm2java
 */
@Entity
@Table(name = "LOG_OLD", schema = "TOM")
public class LogOld implements java.io.Serializable {

	private BigDecimal idLog;
	private Date DLog;
	private String type;
	private String sens;
	private String ws;
	private String methode;
	private String sysAppelant;
	private String CRetour;
	private String operation;
	private Clob txtLog;
	private Clob request;
	private Clob response;
	private BigDecimal idDem;
	private String bpmUid;
	private String refDemSrc;

	public LogOld() {
	}

	public LogOld(BigDecimal idLog, Date DLog, String type, String sens, Clob request) {
		this.idLog = idLog;
		this.DLog = DLog;
		this.type = type;
		this.sens = sens;
		this.request = request;
	}

	public LogOld(BigDecimal idLog, Date DLog, String type, String sens, String ws, String methode, String sysAppelant,
			String CRetour, String operation, Clob txtLog, Clob request, Clob response, BigDecimal idDem, String bpmUid,
			String refDemSrc) {
		this.idLog = idLog;
		this.DLog = DLog;
		this.type = type;
		this.sens = sens;
		this.ws = ws;
		this.methode = methode;
		this.sysAppelant = sysAppelant;
		this.CRetour = CRetour;
		this.operation = operation;
		this.txtLog = txtLog;
		this.request = request;
		this.response = response;
		this.idDem = idDem;
		this.bpmUid = bpmUid;
		this.refDemSrc = refDemSrc;
	}

	@Id

	@Column(name = "ID_LOG", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdLog() {
		return this.idLog;
	}

	public void setIdLog(BigDecimal idLog) {
		this.idLog = idLog;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_LOG", nullable = false, length = 11)
	public Date getDLog() {
		return this.DLog;
	}

	public void setDLog(Date DLog) {
		this.DLog = DLog;
	}

	@Column(name = "TYPE", nullable = false, length = 3)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "SENS", nullable = false, length = 3)
	public String getSens() {
		return this.sens;
	}

	public void setSens(String sens) {
		this.sens = sens;
	}

	@Column(name = "WS", length = 100)
	public String getWs() {
		return this.ws;
	}

	public void setWs(String ws) {
		this.ws = ws;
	}

	@Column(name = "METHODE", length = 100)
	public String getMethode() {
		return this.methode;
	}

	public void setMethode(String methode) {
		this.methode = methode;
	}

	@Column(name = "SYS_APPELANT", length = 50)
	public String getSysAppelant() {
		return this.sysAppelant;
	}

	public void setSysAppelant(String sysAppelant) {
		this.sysAppelant = sysAppelant;
	}

	@Column(name = "C_RETOUR", length = 20)
	public String getCRetour() {
		return this.CRetour;
	}

	public void setCRetour(String CRetour) {
		this.CRetour = CRetour;
	}

	@Column(name = "OPERATION", length = 50)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "TXT_LOG")
	public Clob getTxtLog() {
		return this.txtLog;
	}

	public void setTxtLog(Clob txtLog) {
		this.txtLog = txtLog;
	}

	@Column(name = "REQUEST", nullable = false)
	public Clob getRequest() {
		return this.request;
	}

	public void setRequest(Clob request) {
		this.request = request;
	}

	@Column(name = "RESPONSE")
	public Clob getResponse() {
		return this.response;
	}

	public void setResponse(Clob response) {
		this.response = response;
	}

	@Column(name = "ID_DEM", precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "BPM_UID", length = 50)
	public String getBpmUid() {
		return this.bpmUid;
	}

	public void setBpmUid(String bpmUid) {
		this.bpmUid = bpmUid;
	}

	@Column(name = "REF_DEM_SRC", length = 100)
	public String getRefDemSrc() {
		return this.refDemSrc;
	}

	public void setRefDemSrc(String refDemSrc) {
		this.refDemSrc = refDemSrc;
	}

}
