package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LogWsParamId generated by hbm2java
 */
@Embeddable
public class LogWsParamId implements java.io.Serializable {

	private BigDecimal idLog;
	private String code;

	public LogWsParamId() {
	}

	public LogWsParamId(BigDecimal idLog, String code) {
		this.idLog = idLog;
		this.code = code;
	}

	@Column(name = "ID_LOG", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdLog() {
		return this.idLog;
	}

	public void setIdLog(BigDecimal idLog) {
		this.idLog = idLog;
	}

	@Column(name = "CODE", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogWsParamId))
			return false;
		LogWsParamId castOther = (LogWsParamId) other;

		return ((this.getIdLog() == castOther.getIdLog()) || (this.getIdLog() != null && castOther.getIdLog() != null
				&& this.getIdLog().equals(castOther.getIdLog())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null
						&& this.getCode().equals(castOther.getCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdLog() == null ? 0 : this.getIdLog().hashCode());
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		return result;
	}

}
