package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LogWsParam generated by hbm2java
 */
@Entity
@Table(name = "LOG_WS_PARAM", schema = "TOM")
public class LogWsParam implements java.io.Serializable {

	private LogWsParamId id;
	private LogWs logWs;
	private String valeur;
	private String format;
	private String className;

	public LogWsParam() {
	}

	public LogWsParam(LogWsParamId id, LogWs logWs) {
		this.id = id;
		this.logWs = logWs;
	}

	public LogWsParam(LogWsParamId id, LogWs logWs, String valeur, String format, String className) {
		this.id = id;
		this.logWs = logWs;
		this.valeur = valeur;
		this.format = format;
		this.className = className;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idLog", column = @Column(name = "ID_LOG", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", nullable = false, length = 50)) })
	public LogWsParamId getId() {
		return this.id;
	}

	public void setId(LogWsParamId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_LOG", nullable = false, insertable = false, updatable = false)
	public LogWs getLogWs() {
		return this.logWs;
	}

	public void setLogWs(LogWs logWs) {
		this.logWs = logWs;
	}

	@Column(name = "VALEUR", length = 500)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "FORMAT", length = 50)
	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	@Column(name = "CLASS_NAME", length = 100)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

}
