package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogWs generated by hbm2java
 */
@Entity
@Table(name = "LOG_WS", schema = "TOM")
public class LogWs implements java.io.Serializable {

	private BigDecimal idLog;
	private Date DLog;
	private String ws;
	private String methode;
	private String sysAppelant;
	private boolean resultat;
	private String CRetour;
	private String operation;
	private String exception;
	private Set<LogWsParam> logWsParams = new HashSet<LogWsParam>(0);

	public LogWs() {
	}

	public LogWs(BigDecimal idLog, Date DLog, String ws, boolean resultat) {
		this.idLog = idLog;
		this.DLog = DLog;
		this.ws = ws;
		this.resultat = resultat;
	}

	public LogWs(BigDecimal idLog, Date DLog, String ws, String methode, String sysAppelant, boolean resultat,
			String CRetour, String operation, String exception, Set<LogWsParam> logWsParams) {
		this.idLog = idLog;
		this.DLog = DLog;
		this.ws = ws;
		this.methode = methode;
		this.sysAppelant = sysAppelant;
		this.resultat = resultat;
		this.CRetour = CRetour;
		this.operation = operation;
		this.exception = exception;
		this.logWsParams = logWsParams;
	}

	@Id

	@Column(name = "ID_LOG", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdLog() {
		return this.idLog;
	}

	public void setIdLog(BigDecimal idLog) {
		this.idLog = idLog;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_LOG", nullable = false, length = 11)
	public Date getDLog() {
		return this.DLog;
	}

	public void setDLog(Date DLog) {
		this.DLog = DLog;
	}

	@Column(name = "WS", nullable = false, length = 100)
	public String getWs() {
		return this.ws;
	}

	public void setWs(String ws) {
		this.ws = ws;
	}

	@Column(name = "METHODE", length = 100)
	public String getMethode() {
		return this.methode;
	}

	public void setMethode(String methode) {
		this.methode = methode;
	}

	@Column(name = "SYS_APPELANT", length = 50)
	public String getSysAppelant() {
		return this.sysAppelant;
	}

	public void setSysAppelant(String sysAppelant) {
		this.sysAppelant = sysAppelant;
	}

	@Column(name = "RESULTAT", nullable = false, precision = 1, scale = 0)
	public boolean isResultat() {
		return this.resultat;
	}

	public void setResultat(boolean resultat) {
		this.resultat = resultat;
	}

	@Column(name = "C_RETOUR", length = 20)
	public String getCRetour() {
		return this.CRetour;
	}

	public void setCRetour(String CRetour) {
		this.CRetour = CRetour;
	}

	@Column(name = "OPERATION", length = 50)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "EXCEPTION", length = 1000)
	public String getException() {
		return this.exception;
	}

	public void setException(String exception) {
		this.exception = exception;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logWs")
	public Set<LogWsParam> getLogWsParams() {
		return this.logWsParams;
	}

	public void setLogWsParams(Set<LogWsParam> logWsParams) {
		this.logWsParams = logWsParams;
	}

}
