package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Motif generated by hbm2java
 */
@Entity
@Table(name = "MOTIF", schema = "TOM")
public class Motif implements java.io.Serializable {

	private String CMotif;
	private String motif;
	private String mapSys;
	private String mapSysCode;
	private Boolean FFacturable;
	private String motifExt;
	private Set<DemSuivi> demSuivis = new HashSet<DemSuivi>(0);
	private Set<Demande> demandes = new HashSet<Demande>(0);
	private Set<OtSuivi> otSuivis = new HashSet<OtSuivi>(0);
	private Set<PrmOtMotif> prmOtMotifs = new HashSet<PrmOtMotif>(0);
	private Set<Ot> ots = new HashSet<Ot>(0);
	private Set<PrmDemMotif> prmDemMotifs = new HashSet<PrmDemMotif>(0);
	private Set<BillingParamEvent> billingParamEvents = new HashSet<BillingParamEvent>(0);
	private Set<BillingEvent> billingEvents = new HashSet<BillingEvent>(0);

	public Motif() {
	}

	public Motif(String CMotif, String motif) {
		this.CMotif = CMotif;
		this.motif = motif;
	}

	public Motif(String CMotif, String motif, String mapSys, String mapSysCode, Boolean FFacturable, String motifExt,
			Set<DemSuivi> demSuivis, Set<Demande> demandes, Set<OtSuivi> otSuivis, Set<PrmOtMotif> prmOtMotifs,
			Set<Ot> ots, Set<PrmDemMotif> prmDemMotifs, Set<BillingParamEvent> billingParamEvents,
			Set<BillingEvent> billingEvents) {
		this.CMotif = CMotif;
		this.motif = motif;
		this.mapSys = mapSys;
		this.mapSysCode = mapSysCode;
		this.FFacturable = FFacturable;
		this.motifExt = motifExt;
		this.demSuivis = demSuivis;
		this.demandes = demandes;
		this.otSuivis = otSuivis;
		this.prmOtMotifs = prmOtMotifs;
		this.ots = ots;
		this.prmDemMotifs = prmDemMotifs;
		this.billingParamEvents = billingParamEvents;
		this.billingEvents = billingEvents;
	}

	@Id

	@Column(name = "C_MOTIF", unique = true, nullable = false, length = 100)
	public String getCMotif() {
		return this.CMotif;
	}

	public void setCMotif(String CMotif) {
		this.CMotif = CMotif;
	}

	@Column(name = "MOTIF", nullable = false, length = 100)
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	@Column(name = "MAP_SYS", length = 10)
	public String getMapSys() {
		return this.mapSys;
	}

	public void setMapSys(String mapSys) {
		this.mapSys = mapSys;
	}

	@Column(name = "MAP_SYS_CODE", length = 20)
	public String getMapSysCode() {
		return this.mapSysCode;
	}

	public void setMapSysCode(String mapSysCode) {
		this.mapSysCode = mapSysCode;
	}

	@Column(name = "F_FACTURABLE", precision = 1, scale = 0)
	public Boolean getFFacturable() {
		return this.FFacturable;
	}

	public void setFFacturable(Boolean FFacturable) {
		this.FFacturable = FFacturable;
	}

	@Column(name = "MOTIF_EXT", length = 100)
	public String getMotifExt() {
		return this.motifExt;
	}

	public void setMotifExt(String motifExt) {
		this.motifExt = motifExt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motif")
	public Set<DemSuivi> getDemSuivis() {
		return this.demSuivis;
	}

	public void setDemSuivis(Set<DemSuivi> demSuivis) {
		this.demSuivis = demSuivis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motif")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motif")
	public Set<OtSuivi> getOtSuivis() {
		return this.otSuivis;
	}

	public void setOtSuivis(Set<OtSuivi> otSuivis) {
		this.otSuivis = otSuivis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motif")
	public Set<PrmOtMotif> getPrmOtMotifs() {
		return this.prmOtMotifs;
	}

	public void setPrmOtMotifs(Set<PrmOtMotif> prmOtMotifs) {
		this.prmOtMotifs = prmOtMotifs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motif")
	public Set<Ot> getOts() {
		return this.ots;
	}

	public void setOts(Set<Ot> ots) {
		this.ots = ots;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motif")
	public Set<PrmDemMotif> getPrmDemMotifs() {
		return this.prmDemMotifs;
	}

	public void setPrmDemMotifs(Set<PrmDemMotif> prmDemMotifs) {
		this.prmDemMotifs = prmDemMotifs;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "motifs")
	public Set<BillingParamEvent> getBillingParamEvents() {
		return this.billingParamEvents;
	}

	public void setBillingParamEvents(Set<BillingParamEvent> billingParamEvents) {
		this.billingParamEvents = billingParamEvents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motif")
	public Set<BillingEvent> getBillingEvents() {
		return this.billingEvents;
	}

	public void setBillingEvents(Set<BillingEvent> billingEvents) {
		this.billingEvents = billingEvents;
	}

}
