package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Offre generated by hbm2java
 */
@Entity
@Table(name = "OFFRE", schema = "TOM")
public class Offre implements java.io.Serializable {

	private String idOffre;
	private String offre;
	private String CBscs;

	public Offre() {
	}

	public Offre(String idOffre) {
		this.idOffre = idOffre;
	}

	public Offre(String idOffre, String offre, String CBscs) {
		this.idOffre = idOffre;
		this.offre = offre;
		this.CBscs = CBscs;
	}

	@Id

	@Column(name = "ID_OFFRE", unique = true, nullable = false, length = 100)
	public String getIdOffre() {
		return this.idOffre;
	}

	public void setIdOffre(String idOffre) {
		this.idOffre = idOffre;
	}

	@Column(name = "OFFRE", length = 100)
	public String getOffre() {
		return this.offre;
	}

	public void setOffre(String offre) {
		this.offre = offre;
	}

	@Column(name = "C_BSCS", length = 100)
	public String getCBscs() {
		return this.CBscs;
	}

	public void setCBscs(String CBscs) {
		this.CBscs = CBscs;
	}

}
