package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OperationProcess generated by hbm2java
 */
@Entity
@Table(name = "OPERATION_PROCESS", schema = "TOM")
public class OperationProcess implements java.io.Serializable {

	private BigDecimal operationId;
	private String operationCode;
	private String processId;

	public OperationProcess() {
	}

	public OperationProcess(BigDecimal operationId, String processId) {
		this.operationId = operationId;
		this.processId = processId;
	}

	public OperationProcess(BigDecimal operationId, String operationCode, String processId) {
		this.operationId = operationId;
		this.operationCode = operationCode;
		this.processId = processId;
	}

	@Id

	@Column(name = "OPERATION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getOperationId() {
		return this.operationId;
	}

	public void setOperationId(BigDecimal operationId) {
		this.operationId = operationId;
	}

	@Column(name = "OPERATION_CODE", length = 50)
	public String getOperationCode() {
		return this.operationCode;
	}

	public void setOperationCode(String operationCode) {
		this.operationCode = operationCode;
	}

	@Column(name = "PROCESS_ID", nullable = false, length = 100)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

}
