package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ot generated by hbm2java
 */
@Entity
@Table(name = "OT", schema = "TOM")
public class Ot implements java.io.Serializable {

	private OtId id;
	private Demande demande;
	private Equipe equipe;
	private Motif motif;
	private Ot ot;
	private PrmOtEtat prmOtEtat;
	private PrmOtType prmOtType;
	private Unite unite;
	private String comm;
	private Date DCreation;
	private Date DAffectation;
	private Date DEtat;
	private String loginEtat;
	private Date DFinReelle;
	private Date DFinPrevue;
	private String etatSiraj;
	private String motifSiraj;
	private Set<Ot> ots = new HashSet<Ot>(0);
	private Set<OtDoc> otDocs = new HashSet<OtDoc>(0);
	private Set<OtProp> otProps = new HashSet<OtProp>(0);
	private Set<OtSuivi> otSuivis = new HashSet<OtSuivi>(0);

	public Ot() {
	}

	public Ot(OtId id, Demande demande, PrmOtEtat prmOtEtat, PrmOtType prmOtType, Unite unite, Date DCreation,
			Date DEtat) {
		this.id = id;
		this.demande = demande;
		this.prmOtEtat = prmOtEtat;
		this.prmOtType = prmOtType;
		this.unite = unite;
		this.DCreation = DCreation;
		this.DEtat = DEtat;
	}

	public Ot(OtId id, Demande demande, Equipe equipe, Motif motif, Ot ot, PrmOtEtat prmOtEtat, PrmOtType prmOtType,
			Unite unite, String comm, Date DCreation, Date DAffectation, Date DEtat, String loginEtat, Date DFinReelle,
			Date DFinPrevue, String etatSiraj, String motifSiraj, Set<Ot> ots, Set<OtDoc> otDocs, Set<OtProp> otProps,
			Set<OtSuivi> otSuivis) {
		this.id = id;
		this.demande = demande;
		this.equipe = equipe;
		this.motif = motif;
		this.ot = ot;
		this.prmOtEtat = prmOtEtat;
		this.prmOtType = prmOtType;
		this.unite = unite;
		this.comm = comm;
		this.DCreation = DCreation;
		this.DAffectation = DAffectation;
		this.DEtat = DEtat;
		this.loginEtat = loginEtat;
		this.DFinReelle = DFinReelle;
		this.DFinPrevue = DFinPrevue;
		this.etatSiraj = etatSiraj;
		this.motifSiraj = motifSiraj;
		this.ots = ots;
		this.otDocs = otDocs;
		this.otProps = otProps;
		this.otSuivis = otSuivis;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noOt", column = @Column(name = "NO_OT", nullable = false, precision = 22, scale = 0)) })
	public OtId getId() {
		return this.id;
	}

	public void setId(OtId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEM", nullable = false, insertable = false, updatable = false)
	public Demande getDemande() {
		return this.demande;
	}

	public void setDemande(Demande demande) {
		this.demande = demande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EQUIPE")
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_MOTIF")
	public Motif getMotif() {
		return this.motif;
	}

	public void setMotif(Motif motif) {
		this.motif = motif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "ID_DEM_MERE", referencedColumnName = "ID_DEM"),
			@JoinColumn(name = "NO_OT_PERE", referencedColumnName = "NO_OT") })
	public Ot getOt() {
		return this.ot;
	}

	public void setOt(Ot ot) {
		this.ot = ot;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmOtEtat getPrmOtEtat() {
		return this.prmOtEtat;
	}

	public void setPrmOtEtat(PrmOtEtat prmOtEtat) {
		this.prmOtEtat = prmOtEtat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_OT", nullable = false)
	public PrmOtType getPrmOtType() {
		return this.prmOtType;
	}

	public void setPrmOtType(PrmOtType prmOtType) {
		this.prmOtType = prmOtType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_UNITE", nullable = false)
	public Unite getUnite() {
		return this.unite;
	}

	public void setUnite(Unite unite) {
		this.unite = unite;
	}

	@Column(name = "COMM", length = 500)
	public String getComm() {
		return this.comm;
	}

	public void setComm(String comm) {
		this.comm = comm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CREATION", nullable = false, length = 11)
	public Date getDCreation() {
		return this.DCreation;
	}

	public void setDCreation(Date DCreation) {
		this.DCreation = DCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_AFFECTATION", length = 11)
	public Date getDAffectation() {
		return this.DAffectation;
	}

	public void setDAffectation(Date DAffectation) {
		this.DAffectation = DAffectation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ETAT", nullable = false, length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	@Column(name = "LOGIN_ETAT", length = 20)
	public String getLoginEtat() {
		return this.loginEtat;
	}

	public void setLoginEtat(String loginEtat) {
		this.loginEtat = loginEtat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_FIN_REELLE", length = 11)
	public Date getDFinReelle() {
		return this.DFinReelle;
	}

	public void setDFinReelle(Date DFinReelle) {
		this.DFinReelle = DFinReelle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_FIN_PREVUE", length = 11)
	public Date getDFinPrevue() {
		return this.DFinPrevue;
	}

	public void setDFinPrevue(Date DFinPrevue) {
		this.DFinPrevue = DFinPrevue;
	}

	@Column(name = "ETAT_SIRAJ", length = 10)
	public String getEtatSiraj() {
		return this.etatSiraj;
	}

	public void setEtatSiraj(String etatSiraj) {
		this.etatSiraj = etatSiraj;
	}

	@Column(name = "MOTIF_SIRAJ", length = 100)
	public String getMotifSiraj() {
		return this.motifSiraj;
	}

	public void setMotifSiraj(String motifSiraj) {
		this.motifSiraj = motifSiraj;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ot")
	public Set<Ot> getOts() {
		return this.ots;
	}

	public void setOts(Set<Ot> ots) {
		this.ots = ots;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ot")
	public Set<OtDoc> getOtDocs() {
		return this.otDocs;
	}

	public void setOtDocs(Set<OtDoc> otDocs) {
		this.otDocs = otDocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ot")
	public Set<OtProp> getOtProps() {
		return this.otProps;
	}

	public void setOtProps(Set<OtProp> otProps) {
		this.otProps = otProps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ot")
	public Set<OtSuivi> getOtSuivis() {
		return this.otSuivis;
	}

	public void setOtSuivis(Set<OtSuivi> otSuivis) {
		this.otSuivis = otSuivis;
	}

}
