package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtDoc generated by hbm2java
 */
@Entity
@Table(name = "OT_DOC", schema = "TOM")
public class OtDoc implements java.io.Serializable {

	private OtDocId id;
	private Ot ot;
	private String desDoc;
	private String pathDoc;
	private Date DCreation;
	private String loginCreation;

	public OtDoc() {
	}

	public OtDoc(OtDocId id, Ot ot, String desDoc, String pathDoc, Date DCreation, String loginCreation) {
		this.id = id;
		this.ot = ot;
		this.desDoc = desDoc;
		this.pathDoc = pathDoc;
		this.DCreation = DCreation;
		this.loginCreation = loginCreation;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noOt", column = @Column(name = "NO_OT", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noDoc", column = @Column(name = "NO_DOC", nullable = false, precision = 22, scale = 0)) })
	public OtDocId getId() {
		return this.id;
	}

	public void setId(OtDocId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_DEM", referencedColumnName = "ID_DEM", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NO_OT", referencedColumnName = "NO_OT", nullable = false, insertable = false, updatable = false) })
	public Ot getOt() {
		return this.ot;
	}

	public void setOt(Ot ot) {
		this.ot = ot;
	}

	@Column(name = "DES_DOC", nullable = false, length = 100)
	public String getDesDoc() {
		return this.desDoc;
	}

	public void setDesDoc(String desDoc) {
		this.desDoc = desDoc;
	}

	@Column(name = "PATH_DOC", nullable = false, length = 200)
	public String getPathDoc() {
		return this.pathDoc;
	}

	public void setPathDoc(String pathDoc) {
		this.pathDoc = pathDoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CREATION", nullable = false, length = 11)
	public Date getDCreation() {
		return this.DCreation;
	}

	public void setDCreation(Date DCreation) {
		this.DCreation = DCreation;
	}

	@Column(name = "LOGIN_CREATION", nullable = false, length = 20)
	public String getLoginCreation() {
		return this.loginCreation;
	}

	public void setLoginCreation(String loginCreation) {
		this.loginCreation = loginCreation;
	}

}
