package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OtDocId generated by hbm2java
 */
@Embeddable
public class OtDocId implements java.io.Serializable {

	private BigDecimal idDem;
	private BigDecimal noOt;
	private BigDecimal noDoc;

	public OtDocId() {
	}

	public OtDocId(BigDecimal idDem, BigDecimal noOt, BigDecimal noDoc) {
		this.idDem = idDem;
		this.noOt = noOt;
		this.noDoc = noDoc;
	}

	@Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "NO_OT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNoOt() {
		return this.noOt;
	}

	public void setNoOt(BigDecimal noOt) {
		this.noOt = noOt;
	}

	@Column(name = "NO_DOC", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNoDoc() {
		return this.noDoc;
	}

	public void setNoDoc(BigDecimal noDoc) {
		this.noDoc = noDoc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OtDocId))
			return false;
		OtDocId castOther = (OtDocId) other;

		return ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null && castOther.getIdDem() != null
				&& this.getIdDem().equals(castOther.getIdDem())))
				&& ((this.getNoOt() == castOther.getNoOt()) || (this.getNoOt() != null && castOther.getNoOt() != null
						&& this.getNoOt().equals(castOther.getNoOt())))
				&& ((this.getNoDoc() == castOther.getNoDoc()) || (this.getNoDoc() != null
						&& castOther.getNoDoc() != null && this.getNoDoc().equals(castOther.getNoDoc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + (getNoOt() == null ? 0 : this.getNoOt().hashCode());
		result = 37 * result + (getNoDoc() == null ? 0 : this.getNoDoc().hashCode());
		return result;
	}

}
