package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OtId generated by hbm2java
 */
@Embeddable
public class OtId implements java.io.Serializable {

	private BigDecimal idDem;
	private BigDecimal noOt;

	public OtId() {
	}

	public OtId(BigDecimal idDem, BigDecimal noOt) {
		this.idDem = idDem;
		this.noOt = noOt;
	}

	@Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "NO_OT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNoOt() {
		return this.noOt;
	}

	public void setNoOt(BigDecimal noOt) {
		this.noOt = noOt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OtId))
			return false;
		OtId castOther = (OtId) other;

		return ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null && castOther.getIdDem() != null
				&& this.getIdDem().equals(castOther.getIdDem())))
				&& ((this.getNoOt() == castOther.getNoOt()) || (this.getNoOt() != null && castOther.getNoOt() != null
						&& this.getNoOt().equals(castOther.getNoOt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + (getNoOt() == null ? 0 : this.getNoOt().hashCode());
		return result;
	}

}
