package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtPropSuivi generated by hbm2java
 */
@Entity
@Table(name = "OT_PROP_SUIVI", schema = "TOM")
public class OtPropSuivi implements java.io.Serializable {

	private OtPropSuiviId id;
	private OtProp otProp;
	private String valeur;
	private String idValeur;
	private String comm;
	private Date DModif;
	private String loginModif;

	public OtPropSuivi() {
	}

	public OtPropSuivi(OtPropSuiviId id, OtProp otProp) {
		this.id = id;
		this.otProp = otProp;
	}

	public OtPropSuivi(OtPropSuiviId id, OtProp otProp, String valeur, String idValeur, String comm, Date DModif,
			String loginModif) {
		this.id = id;
		this.otProp = otProp;
		this.valeur = valeur;
		this.idValeur = idValeur;
		this.comm = comm;
		this.DModif = DModif;
		this.loginModif = loginModif;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noOt", column = @Column(name = "NO_OT", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "CProp", column = @Column(name = "C_PROP", nullable = false, length = 50)),
			@AttributeOverride(name = "groupe", column = @Column(name = "GROUPE", nullable = false, length = 50)),
			@AttributeOverride(name = "DSuivi", column = @Column(name = "D_SUIVI", nullable = false, length = 11)) })
	public OtPropSuiviId getId() {
		return this.id;
	}

	public void setId(OtPropSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_DEM", referencedColumnName = "ID_DEM", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NO_OT", referencedColumnName = "NO_OT", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "C_PROP", referencedColumnName = "C_PROP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "GROUPE", referencedColumnName = "GROUPE", nullable = false, insertable = false, updatable = false) })
	public OtProp getOtProp() {
		return this.otProp;
	}

	public void setOtProp(OtProp otProp) {
		this.otProp = otProp;
	}

	@Column(name = "VALEUR", length = 200)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "ID_VALEUR", length = 100)
	public String getIdValeur() {
		return this.idValeur;
	}

	public void setIdValeur(String idValeur) {
		this.idValeur = idValeur;
	}

	@Column(name = "COMM", length = 500)
	public String getComm() {
		return this.comm;
	}

	public void setComm(String comm) {
		this.comm = comm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_MODIF", length = 11)
	public Date getDModif() {
		return this.DModif;
	}

	public void setDModif(Date DModif) {
		this.DModif = DModif;
	}

	@Column(name = "LOGIN_MODIF", length = 20)
	public String getLoginModif() {
		return this.loginModif;
	}

	public void setLoginModif(String loginModif) {
		this.loginModif = loginModif;
	}

}
