package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OtPropSuiviId generated by hbm2java
 */
@Embeddable
public class OtPropSuiviId implements java.io.Serializable {

	private BigDecimal idDem;
	private BigDecimal noOt;
	private String CProp;
	private String groupe;
	private Date DSuivi;

	public OtPropSuiviId() {
	}

	public OtPropSuiviId(BigDecimal idDem, BigDecimal noOt, String CProp, String groupe, Date DSuivi) {
		this.idDem = idDem;
		this.noOt = noOt;
		this.CProp = CProp;
		this.groupe = groupe;
		this.DSuivi = DSuivi;
	}

	@Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "NO_OT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNoOt() {
		return this.noOt;
	}

	public void setNoOt(BigDecimal noOt) {
		this.noOt = noOt;
	}

	@Column(name = "C_PROP", nullable = false, length = 50)
	public String getCProp() {
		return this.CProp;
	}

	public void setCProp(String CProp) {
		this.CProp = CProp;
	}

	@Column(name = "GROUPE", nullable = false, length = 50)
	public String getGroupe() {
		return this.groupe;
	}

	public void setGroupe(String groupe) {
		this.groupe = groupe;
	}

	@Column(name = "D_SUIVI", nullable = false, length = 11)
	public Date getDSuivi() {
		return this.DSuivi;
	}

	public void setDSuivi(Date DSuivi) {
		this.DSuivi = DSuivi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OtPropSuiviId))
			return false;
		OtPropSuiviId castOther = (OtPropSuiviId) other;

		return ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null && castOther.getIdDem() != null
				&& this.getIdDem().equals(castOther.getIdDem())))
				&& ((this.getNoOt() == castOther.getNoOt()) || (this.getNoOt() != null && castOther.getNoOt() != null
						&& this.getNoOt().equals(castOther.getNoOt())))
				&& ((this.getCProp() == castOther.getCProp()) || (this.getCProp() != null
						&& castOther.getCProp() != null && this.getCProp().equals(castOther.getCProp())))
				&& ((this.getGroupe() == castOther.getGroupe()) || (this.getGroupe() != null
						&& castOther.getGroupe() != null && this.getGroupe().equals(castOther.getGroupe())))
				&& ((this.getDSuivi() == castOther.getDSuivi()) || (this.getDSuivi() != null
						&& castOther.getDSuivi() != null && this.getDSuivi().equals(castOther.getDSuivi())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + (getNoOt() == null ? 0 : this.getNoOt().hashCode());
		result = 37 * result + (getCProp() == null ? 0 : this.getCProp().hashCode());
		result = 37 * result + (getGroupe() == null ? 0 : this.getGroupe().hashCode());
		result = 37 * result + (getDSuivi() == null ? 0 : this.getDSuivi().hashCode());
		return result;
	}

}
