package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OtSuivi generated by hbm2java
 */
@Entity
@Table(name = "OT_SUIVI", schema = "TOM")
public class OtSuivi implements java.io.Serializable {

	private OtSuiviId id;
	private Motif motif;
	private Ot ot;
	private PrmOtEtat prmOtEtat;
	private String loginEtat;
	private String comm;
	private String pj;
	private BigDecimal idEquipe;
	private String CUnite;

	public OtSuivi() {
	}

	public OtSuivi(OtSuiviId id, Ot ot, PrmOtEtat prmOtEtat, String CUnite) {
		this.id = id;
		this.ot = ot;
		this.prmOtEtat = prmOtEtat;
		this.CUnite = CUnite;
	}

	public OtSuivi(OtSuiviId id, Motif motif, Ot ot, PrmOtEtat prmOtEtat, String loginEtat, String comm, String pj,
			BigDecimal idEquipe, String CUnite) {
		this.id = id;
		this.motif = motif;
		this.ot = ot;
		this.prmOtEtat = prmOtEtat;
		this.loginEtat = loginEtat;
		this.comm = comm;
		this.pj = pj;
		this.idEquipe = idEquipe;
		this.CUnite = CUnite;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDem", column = @Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noOt", column = @Column(name = "NO_OT", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "DEtat", column = @Column(name = "D_ETAT", nullable = false, length = 11)) })
	public OtSuiviId getId() {
		return this.id;
	}

	public void setId(OtSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_MOTIF")
	public Motif getMotif() {
		return this.motif;
	}

	public void setMotif(Motif motif) {
		this.motif = motif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_DEM", referencedColumnName = "ID_DEM", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NO_OT", referencedColumnName = "NO_OT", nullable = false, insertable = false, updatable = false) })
	public Ot getOt() {
		return this.ot;
	}

	public void setOt(Ot ot) {
		this.ot = ot;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmOtEtat getPrmOtEtat() {
		return this.prmOtEtat;
	}

	public void setPrmOtEtat(PrmOtEtat prmOtEtat) {
		this.prmOtEtat = prmOtEtat;
	}

	@Column(name = "LOGIN_ETAT", length = 20)
	public String getLoginEtat() {
		return this.loginEtat;
	}

	public void setLoginEtat(String loginEtat) {
		this.loginEtat = loginEtat;
	}

	@Column(name = "COMM", length = 500)
	public String getComm() {
		return this.comm;
	}

	public void setComm(String comm) {
		this.comm = comm;
	}

	@Column(name = "PJ", length = 200)
	public String getPj() {
		return this.pj;
	}

	public void setPj(String pj) {
		this.pj = pj;
	}

	@Column(name = "ID_EQUIPE", precision = 22, scale = 0)
	public BigDecimal getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(BigDecimal idEquipe) {
		this.idEquipe = idEquipe;
	}

	@Column(name = "C_UNITE", nullable = false, length = 20)
	public String getCUnite() {
		return this.CUnite;
	}

	public void setCUnite(String CUnite) {
		this.CUnite = CUnite;
	}

}
