package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OtSuiviId generated by hbm2java
 */
@Embeddable
public class OtSuiviId implements java.io.Serializable {

	private BigDecimal idDem;
	private BigDecimal noOt;
	private Date DEtat;

	public OtSuiviId() {
	}

	public OtSuiviId(BigDecimal idDem, BigDecimal noOt, Date DEtat) {
		this.idDem = idDem;
		this.noOt = noOt;
		this.DEtat = DEtat;
	}

	@Column(name = "ID_DEM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDem() {
		return this.idDem;
	}

	public void setIdDem(BigDecimal idDem) {
		this.idDem = idDem;
	}

	@Column(name = "NO_OT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNoOt() {
		return this.noOt;
	}

	public void setNoOt(BigDecimal noOt) {
		this.noOt = noOt;
	}

	@Column(name = "D_ETAT", nullable = false, length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OtSuiviId))
			return false;
		OtSuiviId castOther = (OtSuiviId) other;

		return ((this.getIdDem() == castOther.getIdDem()) || (this.getIdDem() != null && castOther.getIdDem() != null
				&& this.getIdDem().equals(castOther.getIdDem())))
				&& ((this.getNoOt() == castOther.getNoOt()) || (this.getNoOt() != null && castOther.getNoOt() != null
						&& this.getNoOt().equals(castOther.getNoOt())))
				&& ((this.getDEtat() == castOther.getDEtat()) || (this.getDEtat() != null
						&& castOther.getDEtat() != null && this.getDEtat().equals(castOther.getDEtat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdDem() == null ? 0 : this.getIdDem().hashCode());
		result = 37 * result + (getNoOt() == null ? 0 : this.getNoOt().hashCode());
		result = 37 * result + (getDEtat() == null ? 0 : this.getDEtat().hashCode());
		return result;
	}

}
