package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParamGen generated by hbm2java
 */
@Entity
@Table(name = "PARAM_GEN", schema = "TOM")
public class ParamGen implements java.io.Serializable {

	private String CParam;
	private String param;
	private String descParam;
	private String valeur;
	private Date DDebApp;
	private Date DFinApp;
	private Set<PrmOpOtPart> prmOpOtParts = new HashSet<PrmOpOtPart>(0);

	public ParamGen() {
	}

	public ParamGen(String CParam, String param, String valeur) {
		this.CParam = CParam;
		this.param = param;
		this.valeur = valeur;
	}

	public ParamGen(String CParam, String param, String descParam, String valeur, Date DDebApp, Date DFinApp,
			Set<PrmOpOtPart> prmOpOtParts) {
		this.CParam = CParam;
		this.param = param;
		this.descParam = descParam;
		this.valeur = valeur;
		this.DDebApp = DDebApp;
		this.DFinApp = DFinApp;
		this.prmOpOtParts = prmOpOtParts;
	}

	@Id

	@Column(name = "C_PARAM", unique = true, nullable = false, length = 50)
	public String getCParam() {
		return this.CParam;
	}

	public void setCParam(String CParam) {
		this.CParam = CParam;
	}

	@Column(name = "PARAM", nullable = false, length = 100)
	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	@Column(name = "DESC_PARAM", length = 500)
	public String getDescParam() {
		return this.descParam;
	}

	public void setDescParam(String descParam) {
		this.descParam = descParam;
	}

	@Column(name = "VALEUR", nullable = false, length = 200)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_DEB_APP", length = 7)
	public Date getDDebApp() {
		return this.DDebApp;
	}

	public void setDDebApp(Date DDebApp) {
		this.DDebApp = DDebApp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_FIN_APP", length = 7)
	public Date getDFinApp() {
		return this.DFinApp;
	}

	public void setDFinApp(Date DFinApp) {
		this.DFinApp = DFinApp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paramGen")
	public Set<PrmOpOtPart> getPrmOpOtParts() {
		return this.prmOpOtParts;
	}

	public void setPrmOpOtParts(Set<PrmOpOtPart> prmOpOtParts) {
		this.prmOpOtParts = prmOpOtParts;
	}

}
