package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ParamJf generated by hbm2java
 */
@Entity
@Table(name = "PARAM_JF", schema = "TOM")
public class ParamJf implements java.io.Serializable {

	private BigDecimal noJf;
	private String jf;
	private byte jour;
	private byte mois;
	private byte duree;
	private boolean FEtat;

	public ParamJf() {
	}

	public ParamJf(BigDecimal noJf, String jf, byte jour, byte mois, byte duree, boolean FEtat) {
		this.noJf = noJf;
		this.jf = jf;
		this.jour = jour;
		this.mois = mois;
		this.duree = duree;
		this.FEtat = FEtat;
	}

	@Id

	@Column(name = "NO_JF", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getNoJf() {
		return this.noJf;
	}

	public void setNoJf(BigDecimal noJf) {
		this.noJf = noJf;
	}

	@Column(name = "JF", nullable = false, length = 200)
	public String getJf() {
		return this.jf;
	}

	public void setJf(String jf) {
		this.jf = jf;
	}

	@Column(name = "JOUR", nullable = false, precision = 2, scale = 0)
	public byte getJour() {
		return this.jour;
	}

	public void setJour(byte jour) {
		this.jour = jour;
	}

	@Column(name = "MOIS", nullable = false, precision = 2, scale = 0)
	public byte getMois() {
		return this.mois;
	}

	public void setMois(byte mois) {
		this.mois = mois;
	}

	@Column(name = "DUREE", nullable = false, precision = 2, scale = 0)
	public byte getDuree() {
		return this.duree;
	}

	public void setDuree(byte duree) {
		this.duree = duree;
	}

	@Column(name = "F_ETAT", nullable = false, precision = 1, scale = 0)
	public boolean isFEtat() {
		return this.FEtat;
	}

	public void setFEtat(boolean FEtat) {
		this.FEtat = FEtat;
	}

}
