package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParamJfAnnee generated by hbm2java
 */
@Entity
@Table(name = "PARAM_JF_ANNEE", schema = "TOM")
public class ParamJfAnnee implements java.io.Serializable {

	private BigDecimal idJf;
	private ParamJfAnnee paramJfAnnee;
	private Date DJf;
	private String jf;
	private Date DCreation;
	private String loginCreation;
	private Set<ParamJfAnnee> paramJfAnnees = new HashSet<ParamJfAnnee>(0);

	public ParamJfAnnee() {
	}

	public ParamJfAnnee(BigDecimal idJf, String jf) {
		this.idJf = idJf;
		this.jf = jf;
	}

	public ParamJfAnnee(BigDecimal idJf, ParamJfAnnee paramJfAnnee, Date DJf, String jf, Date DCreation,
			String loginCreation, Set<ParamJfAnnee> paramJfAnnees) {
		this.idJf = idJf;
		this.paramJfAnnee = paramJfAnnee;
		this.DJf = DJf;
		this.jf = jf;
		this.DCreation = DCreation;
		this.loginCreation = loginCreation;
		this.paramJfAnnees = paramJfAnnees;
	}

	@Id

	@Column(name = "ID_JF", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdJf() {
		return this.idJf;
	}

	public void setIdJf(BigDecimal idJf) {
		this.idJf = idJf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JF_PERE")
	public ParamJfAnnee getParamJfAnnee() {
		return this.paramJfAnnee;
	}

	public void setParamJfAnnee(ParamJfAnnee paramJfAnnee) {
		this.paramJfAnnee = paramJfAnnee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_JF", length = 7)
	public Date getDJf() {
		return this.DJf;
	}

	public void setDJf(Date DJf) {
		this.DJf = DJf;
	}

	@Column(name = "JF", nullable = false, length = 200)
	public String getJf() {
		return this.jf;
	}

	public void setJf(String jf) {
		this.jf = jf;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CREATION", length = 11)
	public Date getDCreation() {
		return this.DCreation;
	}

	public void setDCreation(Date DCreation) {
		this.DCreation = DCreation;
	}

	@Column(name = "LOGIN_CREATION", length = 20)
	public String getLoginCreation() {
		return this.loginCreation;
	}

	public void setLoginCreation(String loginCreation) {
		this.loginCreation = loginCreation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paramJfAnnee")
	public Set<ParamJfAnnee> getParamJfAnnees() {
		return this.paramJfAnnees;
	}

	public void setParamJfAnnees(Set<ParamJfAnnee> paramJfAnnees) {
		this.paramJfAnnees = paramJfAnnees;
	}

}
