package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parc generated by hbm2java
 */
@Entity
@Table(name = "PARC", schema = "TOM")
public class Parc implements java.io.Serializable {

	private BigDecimal idParc;
	private Localite localite;
	private Parc parcByIdParcLie;
	private Parc parcByIdParcGroupe;
	private Partenaire partenaire;
	private PrmParcEtat prmParcEtat;
	private byte typeSupport;
	private String numLigne;
	private boolean FInsProv;
	private Date DInsFinProv;
	private Date DFinSuspProv;
	private String idOffre;
	private String offre;
	private String typeClient;
	private String idClient;
	private String nom;
	private String prenom;
	private String typeIdentifiant;
	private String identifiant;
	private String contact1;
	private String contact2;
	private BigDecimal idAdrInst;
	private String adrInst;
	private String adrInstX;
	private String adrInstY;
	private BigDecimal codePostal;
	private String actelRattache;
	private Date DCreation;
	private Date DLiv;
	private Date DEtat;
	private String obs;
	private String codeAcces;
	private Boolean typeDgrp;
	private Date DGroupe;
	private String idAdrInstSig;
	private String idOffreFix;
	private Set<ParcProp> parcProps = new HashSet<ParcProp>(0);
	private Set<ParcSuivi> parcSuivisForIdParcGroupe = new HashSet<ParcSuivi>(0);
	private Set<Parc> parcsForIdParcLie = new HashSet<Parc>(0);
	private Set<Dunning> dunnings = new HashSet<Dunning>(0);
	private Set<Parc> parcsForIdParcGroupe = new HashSet<Parc>(0);
	private Set<ParcSs> parcSses = new HashSet<ParcSs>(0);
	private Set<Demande> demandes = new HashSet<Demande>(0);
	private Set<ParcServ> parcServs = new HashSet<ParcServ>(0);
	private Set<ParcSuivi> parcSuivisForIdParc = new HashSet<ParcSuivi>(0);

	public Parc() {
	}

	public Parc(BigDecimal idParc, PrmParcEtat prmParcEtat, byte typeSupport, boolean FInsProv, Date DCreation,
			Date DLiv, Date DEtat) {
		this.idParc = idParc;
		this.prmParcEtat = prmParcEtat;
		this.typeSupport = typeSupport;
		this.FInsProv = FInsProv;
		this.DCreation = DCreation;
		this.DLiv = DLiv;
		this.DEtat = DEtat;
	}

	public Parc(BigDecimal idParc, Localite localite, Parc parcByIdParcLie, Parc parcByIdParcGroupe,
			Partenaire partenaire, PrmParcEtat prmParcEtat, byte typeSupport, String numLigne, boolean FInsProv,
			Date DInsFinProv, Date DFinSuspProv, String idOffre, String offre, String typeClient, String idClient,
			String nom, String prenom, String typeIdentifiant, String identifiant, String contact1, String contact2,
			BigDecimal idAdrInst, String adrInst, String adrInstX, String adrInstY, BigDecimal codePostal,
			String actelRattache, Date DCreation, Date DLiv, Date DEtat, String obs, String codeAcces, Boolean typeDgrp,
			Date DGroupe, String idAdrInstSig, String idOffreFix, Set<ParcProp> parcProps,
			Set<ParcSuivi> parcSuivisForIdParcGroupe, Set<Parc> parcsForIdParcLie, Set<Dunning> dunnings,
			Set<Parc> parcsForIdParcGroupe, Set<ParcSs> parcSses, Set<Demande> demandes, Set<ParcServ> parcServs,
			Set<ParcSuivi> parcSuivisForIdParc) {
		this.idParc = idParc;
		this.localite = localite;
		this.parcByIdParcLie = parcByIdParcLie;
		this.parcByIdParcGroupe = parcByIdParcGroupe;
		this.partenaire = partenaire;
		this.prmParcEtat = prmParcEtat;
		this.typeSupport = typeSupport;
		this.numLigne = numLigne;
		this.FInsProv = FInsProv;
		this.DInsFinProv = DInsFinProv;
		this.DFinSuspProv = DFinSuspProv;
		this.idOffre = idOffre;
		this.offre = offre;
		this.typeClient = typeClient;
		this.idClient = idClient;
		this.nom = nom;
		this.prenom = prenom;
		this.typeIdentifiant = typeIdentifiant;
		this.identifiant = identifiant;
		this.contact1 = contact1;
		this.contact2 = contact2;
		this.idAdrInst = idAdrInst;
		this.adrInst = adrInst;
		this.adrInstX = adrInstX;
		this.adrInstY = adrInstY;
		this.codePostal = codePostal;
		this.actelRattache = actelRattache;
		this.DCreation = DCreation;
		this.DLiv = DLiv;
		this.DEtat = DEtat;
		this.obs = obs;
		this.codeAcces = codeAcces;
		this.typeDgrp = typeDgrp;
		this.DGroupe = DGroupe;
		this.idAdrInstSig = idAdrInstSig;
		this.idOffreFix = idOffreFix;
		this.parcProps = parcProps;
		this.parcSuivisForIdParcGroupe = parcSuivisForIdParcGroupe;
		this.parcsForIdParcLie = parcsForIdParcLie;
		this.dunnings = dunnings;
		this.parcsForIdParcGroupe = parcsForIdParcGroupe;
		this.parcSses = parcSses;
		this.demandes = demandes;
		this.parcServs = parcServs;
		this.parcSuivisForIdParc = parcSuivisForIdParc;
	}

	@Id

	@Column(name = "ID_PARC", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdParc() {
		return this.idParc;
	}

	public void setIdParc(BigDecimal idParc) {
		this.idParc = idParc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_LOC")
	public Localite getLocalite() {
		return this.localite;
	}

	public void setLocalite(Localite localite) {
		this.localite = localite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARC_LIE")
	public Parc getParcByIdParcLie() {
		return this.parcByIdParcLie;
	}

	public void setParcByIdParcLie(Parc parcByIdParcLie) {
		this.parcByIdParcLie = parcByIdParcLie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARC_GROUPE")
	public Parc getParcByIdParcGroupe() {
		return this.parcByIdParcGroupe;
	}

	public void setParcByIdParcGroupe(Parc parcByIdParcGroupe) {
		this.parcByIdParcGroupe = parcByIdParcGroupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PART")
	public Partenaire getPartenaire() {
		return this.partenaire;
	}

	public void setPartenaire(Partenaire partenaire) {
		this.partenaire = partenaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmParcEtat getPrmParcEtat() {
		return this.prmParcEtat;
	}

	public void setPrmParcEtat(PrmParcEtat prmParcEtat) {
		this.prmParcEtat = prmParcEtat;
	}

	@Column(name = "TYPE_SUPPORT", nullable = false, precision = 2, scale = 0)
	public byte getTypeSupport() {
		return this.typeSupport;
	}

	public void setTypeSupport(byte typeSupport) {
		this.typeSupport = typeSupport;
	}

	@Column(name = "NUM_LIGNE", length = 20)
	public String getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(String numLigne) {
		this.numLigne = numLigne;
	}

	@Column(name = "F_INS_PROV", nullable = false, precision = 1, scale = 0)
	public boolean isFInsProv() {
		return this.FInsProv;
	}

	public void setFInsProv(boolean FInsProv) {
		this.FInsProv = FInsProv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_INS_FIN_PROV", length = 7)
	public Date getDInsFinProv() {
		return this.DInsFinProv;
	}

	public void setDInsFinProv(Date DInsFinProv) {
		this.DInsFinProv = DInsFinProv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_FIN_SUSP_PROV", length = 7)
	public Date getDFinSuspProv() {
		return this.DFinSuspProv;
	}

	public void setDFinSuspProv(Date DFinSuspProv) {
		this.DFinSuspProv = DFinSuspProv;
	}

	@Column(name = "ID_OFFRE", length = 50)
	public String getIdOffre() {
		return this.idOffre;
	}

	public void setIdOffre(String idOffre) {
		this.idOffre = idOffre;
	}

	@Column(name = "OFFRE", length = 200)
	public String getOffre() {
		return this.offre;
	}

	public void setOffre(String offre) {
		this.offre = offre;
	}

	@Column(name = "TYPE_CLIENT", length = 50)
	public String getTypeClient() {
		return this.typeClient;
	}

	public void setTypeClient(String typeClient) {
		this.typeClient = typeClient;
	}

	@Column(name = "ID_CLIENT", length = 100)
	public String getIdClient() {
		return this.idClient;
	}

	public void setIdClient(String idClient) {
		this.idClient = idClient;
	}

	@Column(name = "NOM", length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "TYPE_IDENTIFIANT", length = 50)
	public String getTypeIdentifiant() {
		return this.typeIdentifiant;
	}

	public void setTypeIdentifiant(String typeIdentifiant) {
		this.typeIdentifiant = typeIdentifiant;
	}

	@Column(name = "IDENTIFIANT", length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "CONTACT_1", length = 250)
	public String getContact1() {
		return this.contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	@Column(name = "CONTACT_2", length = 250)
	public String getContact2() {
		return this.contact2;
	}

	public void setContact2(String contact2) {
		this.contact2 = contact2;
	}

	@Column(name = "ID_ADR_INST", precision = 22, scale = 0)
	public BigDecimal getIdAdrInst() {
		return this.idAdrInst;
	}

	public void setIdAdrInst(BigDecimal idAdrInst) {
		this.idAdrInst = idAdrInst;
	}

	@Column(name = "ADR_INST", length = 1000)
	public String getAdrInst() {
		return this.adrInst;
	}

	public void setAdrInst(String adrInst) {
		this.adrInst = adrInst;
	}

	@Column(name = "ADR_INST_X", length = 20)
	public String getAdrInstX() {
		return this.adrInstX;
	}

	public void setAdrInstX(String adrInstX) {
		this.adrInstX = adrInstX;
	}

	@Column(name = "ADR_INST_Y", length = 20)
	public String getAdrInstY() {
		return this.adrInstY;
	}

	public void setAdrInstY(String adrInstY) {
		this.adrInstY = adrInstY;
	}

	@Column(name = "CODE_POSTAL", precision = 22, scale = 0)
	public BigDecimal getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(BigDecimal codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "ACTEL_RATTACHE", length = 100)
	public String getActelRattache() {
		return this.actelRattache;
	}

	public void setActelRattache(String actelRattache) {
		this.actelRattache = actelRattache;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CREATION", nullable = false, length = 11)
	public Date getDCreation() {
		return this.DCreation;
	}

	public void setDCreation(Date DCreation) {
		this.DCreation = DCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_LIV", nullable = false, length = 11)
	public Date getDLiv() {
		return this.DLiv;
	}

	public void setDLiv(Date DLiv) {
		this.DLiv = DLiv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ETAT", nullable = false, length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	@Column(name = "OBS", length = 500)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Column(name = "CODE_ACCES", length = 50)
	public String getCodeAcces() {
		return this.codeAcces;
	}

	public void setCodeAcces(String codeAcces) {
		this.codeAcces = codeAcces;
	}

	@Column(name = "TYPE_DGRP", precision = 1, scale = 0)
	public Boolean getTypeDgrp() {
		return this.typeDgrp;
	}

	public void setTypeDgrp(Boolean typeDgrp) {
		this.typeDgrp = typeDgrp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_GROUPE", length = 7)
	public Date getDGroupe() {
		return this.DGroupe;
	}

	public void setDGroupe(Date DGroupe) {
		this.DGroupe = DGroupe;
	}

	@Column(name = "ID_ADR_INST_SIG", length = 200)
	public String getIdAdrInstSig() {
		return this.idAdrInstSig;
	}

	public void setIdAdrInstSig(String idAdrInstSig) {
		this.idAdrInstSig = idAdrInstSig;
	}

	@Column(name = "ID_OFFRE_FIX", length = 200)
	public String getIdOffreFix() {
		return this.idOffreFix;
	}

	public void setIdOffreFix(String idOffreFix) {
		this.idOffreFix = idOffreFix;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parc")
	public Set<ParcProp> getParcProps() {
		return this.parcProps;
	}

	public void setParcProps(Set<ParcProp> parcProps) {
		this.parcProps = parcProps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcByIdParcGroupe")
	public Set<ParcSuivi> getParcSuivisForIdParcGroupe() {
		return this.parcSuivisForIdParcGroupe;
	}

	public void setParcSuivisForIdParcGroupe(Set<ParcSuivi> parcSuivisForIdParcGroupe) {
		this.parcSuivisForIdParcGroupe = parcSuivisForIdParcGroupe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcByIdParcLie")
	public Set<Parc> getParcsForIdParcLie() {
		return this.parcsForIdParcLie;
	}

	public void setParcsForIdParcLie(Set<Parc> parcsForIdParcLie) {
		this.parcsForIdParcLie = parcsForIdParcLie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parc")
	public Set<Dunning> getDunnings() {
		return this.dunnings;
	}

	public void setDunnings(Set<Dunning> dunnings) {
		this.dunnings = dunnings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcByIdParcGroupe")
	public Set<Parc> getParcsForIdParcGroupe() {
		return this.parcsForIdParcGroupe;
	}

	public void setParcsForIdParcGroupe(Set<Parc> parcsForIdParcGroupe) {
		this.parcsForIdParcGroupe = parcsForIdParcGroupe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parc")
	public Set<ParcSs> getParcSses() {
		return this.parcSses;
	}

	public void setParcSses(Set<ParcSs> parcSses) {
		this.parcSses = parcSses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parc")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parc")
	public Set<ParcServ> getParcServs() {
		return this.parcServs;
	}

	public void setParcServs(Set<ParcServ> parcServs) {
		this.parcServs = parcServs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcByIdParc")
	public Set<ParcSuivi> getParcSuivisForIdParc() {
		return this.parcSuivisForIdParc;
	}

	public void setParcSuivisForIdParc(Set<ParcSuivi> parcSuivisForIdParc) {
		this.parcSuivisForIdParc = parcSuivisForIdParc;
	}

}
