package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ParcSsPrmSuivi generated by hbm2java
 */
@Entity
@Table(name = "PARC_SS_PRM_SUIVI", schema = "TOM")
public class ParcSsPrmSuivi implements java.io.Serializable {

	private ParcSsPrmSuiviId id;
	private ParcSsSuivi parcSsSuivi;
	private String param;
	private String valeur;

	public ParcSsPrmSuivi() {
	}

	public ParcSsPrmSuivi(ParcSsPrmSuiviId id, ParcSsSuivi parcSsSuivi, String valeur) {
		this.id = id;
		this.parcSsSuivi = parcSsSuivi;
		this.valeur = valeur;
	}

	public ParcSsPrmSuivi(ParcSsPrmSuiviId id, ParcSsSuivi parcSsSuivi, String param, String valeur) {
		this.id = id;
		this.parcSsSuivi = parcSsSuivi;
		this.param = param;
		this.valeur = valeur;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idParc", column = @Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "DSuivi", column = @Column(name = "D_SUIVI", nullable = false, length = 11)),
			@AttributeOverride(name = "noSs", column = @Column(name = "NO_SS", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "noValSs", column = @Column(name = "NO_VAL_SS", nullable = false, precision = 3, scale = 0)) })
	public ParcSsPrmSuiviId getId() {
		return this.id;
	}

	public void setId(ParcSsPrmSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_PARC", referencedColumnName = "ID_PARC", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "D_SUIVI", referencedColumnName = "D_SUIVI", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NO_SS", referencedColumnName = "NO_SS", nullable = false, insertable = false, updatable = false) })
	public ParcSsSuivi getParcSsSuivi() {
		return this.parcSsSuivi;
	}

	public void setParcSsSuivi(ParcSsSuivi parcSsSuivi) {
		this.parcSsSuivi = parcSsSuivi;
	}

	@Column(name = "PARAM", length = 100)
	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	@Column(name = "VALEUR", nullable = false, length = 100)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

}
