package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ParcSsPrm generated by hbm2java
 */
@Entity
@Table(name = "PARC_SS_PRM", schema = "TOM")
public class ParcSsPrm implements java.io.Serializable {

	private ParcSsPrmId id;
	private ParcSs parcSs;
	private String param;
	private String valeur;

	public ParcSsPrm() {
	}

	public ParcSsPrm(ParcSsPrmId id, ParcSs parcSs, String valeur) {
		this.id = id;
		this.parcSs = parcSs;
		this.valeur = valeur;
	}

	public ParcSsPrm(ParcSsPrmId id, ParcSs parcSs, String param, String valeur) {
		this.id = id;
		this.parcSs = parcSs;
		this.param = param;
		this.valeur = valeur;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idParc", column = @Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noSs", column = @Column(name = "NO_SS", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "noValSs", column = @Column(name = "NO_VAL_SS", nullable = false, precision = 3, scale = 0)) })
	public ParcSsPrmId getId() {
		return this.id;
	}

	public void setId(ParcSsPrmId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_PARC", referencedColumnName = "ID_PARC", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "NO_SS", referencedColumnName = "NO_SS", nullable = false, insertable = false, updatable = false) })
	public ParcSs getParcSs() {
		return this.parcSs;
	}

	public void setParcSs(ParcSs parcSs) {
		this.parcSs = parcSs;
	}

	@Column(name = "PARAM", length = 100)
	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	@Column(name = "VALEUR", nullable = false, length = 100)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

}
