package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParcSs generated by hbm2java
 */
@Entity
@Table(name = "PARC_SS", schema = "TOM")
public class ParcSs implements java.io.Serializable {

	private ParcSsId id;
	private Parc parc;
	private String idSsSrc;
	private String srvSupp;
	private String typeServSup;
	private Date DActiv;
	private Set<ParcSsPrm> parcSsPrms = new HashSet<ParcSsPrm>(0);

	public ParcSs() {
	}

	public ParcSs(ParcSsId id, Parc parc, String srvSupp, String typeServSup) {
		this.id = id;
		this.parc = parc;
		this.srvSupp = srvSupp;
		this.typeServSup = typeServSup;
	}

	public ParcSs(ParcSsId id, Parc parc, String idSsSrc, String srvSupp, String typeServSup, Date DActiv,
			Set<ParcSsPrm> parcSsPrms) {
		this.id = id;
		this.parc = parc;
		this.idSsSrc = idSsSrc;
		this.srvSupp = srvSupp;
		this.typeServSup = typeServSup;
		this.DActiv = DActiv;
		this.parcSsPrms = parcSsPrms;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idParc", column = @Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "noSs", column = @Column(name = "NO_SS", nullable = false, precision = 3, scale = 0)) })
	public ParcSsId getId() {
		return this.id;
	}

	public void setId(ParcSsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARC", nullable = false, insertable = false, updatable = false)
	public Parc getParc() {
		return this.parc;
	}

	public void setParc(Parc parc) {
		this.parc = parc;
	}

	@Column(name = "ID_SS_SRC", length = 50)
	public String getIdSsSrc() {
		return this.idSsSrc;
	}

	public void setIdSsSrc(String idSsSrc) {
		this.idSsSrc = idSsSrc;
	}

	@Column(name = "SRV_SUPP", nullable = false, length = 100)
	public String getSrvSupp() {
		return this.srvSupp;
	}

	public void setSrvSupp(String srvSupp) {
		this.srvSupp = srvSupp;
	}

	@Column(name = "TYPE_SERV_SUP", nullable = false, length = 10)
	public String getTypeServSup() {
		return this.typeServSup;
	}

	public void setTypeServSup(String typeServSup) {
		this.typeServSup = typeServSup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ACTIV", length = 11)
	public Date getDActiv() {
		return this.DActiv;
	}

	public void setDActiv(Date DActiv) {
		this.DActiv = DActiv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcSs")
	public Set<ParcSsPrm> getParcSsPrms() {
		return this.parcSsPrms;
	}

	public void setParcSsPrms(Set<ParcSsPrm> parcSsPrms) {
		this.parcSsPrms = parcSsPrms;
	}

}
