package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParcSuivi generated by hbm2java
 */
@Entity
@Table(name = "PARC_SUIVI", schema = "TOM")
public class ParcSuivi implements java.io.Serializable {

	private ParcSuiviId id;
	private Localite localite;
	private Parc parcByIdParcGroupe;
	private Parc parcByIdParc;
	private PrmParcEtat prmParcEtat;
	private String motifSuivi;
	private String numLigne;
	private String typeClient;
	private String idClient;
	private String nom;
	private String prenom;
	private String typeIdentifiant;
	private String identifiant;
	private String contact1;
	private String contact2;
	private String idOffre;
	private String offre;
	private BigDecimal idAdrInst;
	private String adrInst;
	private Boolean typeDgrp;
	private String codeAcces;
	private String obs;
	private Set<ParcSsSuivi> parcSsSuivis = new HashSet<ParcSsSuivi>(0);
	private Set<ParcPropSuivi> parcPropSuivis = new HashSet<ParcPropSuivi>(0);

	public ParcSuivi() {
	}

	public ParcSuivi(ParcSuiviId id, Parc parcByIdParc, PrmParcEtat prmParcEtat, String motifSuivi) {
		this.id = id;
		this.parcByIdParc = parcByIdParc;
		this.prmParcEtat = prmParcEtat;
		this.motifSuivi = motifSuivi;
	}

	public ParcSuivi(ParcSuiviId id, Localite localite, Parc parcByIdParcGroupe, Parc parcByIdParc,
			PrmParcEtat prmParcEtat, String motifSuivi, String numLigne, String typeClient, String idClient, String nom,
			String prenom, String typeIdentifiant, String identifiant, String contact1, String contact2, String idOffre,
			String offre, BigDecimal idAdrInst, String adrInst, Boolean typeDgrp, String codeAcces, String obs,
			Set<ParcSsSuivi> parcSsSuivis, Set<ParcPropSuivi> parcPropSuivis) {
		this.id = id;
		this.localite = localite;
		this.parcByIdParcGroupe = parcByIdParcGroupe;
		this.parcByIdParc = parcByIdParc;
		this.prmParcEtat = prmParcEtat;
		this.motifSuivi = motifSuivi;
		this.numLigne = numLigne;
		this.typeClient = typeClient;
		this.idClient = idClient;
		this.nom = nom;
		this.prenom = prenom;
		this.typeIdentifiant = typeIdentifiant;
		this.identifiant = identifiant;
		this.contact1 = contact1;
		this.contact2 = contact2;
		this.idOffre = idOffre;
		this.offre = offre;
		this.idAdrInst = idAdrInst;
		this.adrInst = adrInst;
		this.typeDgrp = typeDgrp;
		this.codeAcces = codeAcces;
		this.obs = obs;
		this.parcSsSuivis = parcSsSuivis;
		this.parcPropSuivis = parcPropSuivis;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idParc", column = @Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "DSuivi", column = @Column(name = "D_SUIVI", nullable = false, length = 11)) })
	public ParcSuiviId getId() {
		return this.id;
	}

	public void setId(ParcSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_LOC")
	public Localite getLocalite() {
		return this.localite;
	}

	public void setLocalite(Localite localite) {
		this.localite = localite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARC_GROUPE")
	public Parc getParcByIdParcGroupe() {
		return this.parcByIdParcGroupe;
	}

	public void setParcByIdParcGroupe(Parc parcByIdParcGroupe) {
		this.parcByIdParcGroupe = parcByIdParcGroupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARC", nullable = false, insertable = false, updatable = false)
	public Parc getParcByIdParc() {
		return this.parcByIdParc;
	}

	public void setParcByIdParc(Parc parcByIdParc) {
		this.parcByIdParc = parcByIdParc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmParcEtat getPrmParcEtat() {
		return this.prmParcEtat;
	}

	public void setPrmParcEtat(PrmParcEtat prmParcEtat) {
		this.prmParcEtat = prmParcEtat;
	}

	@Column(name = "MOTIF_SUIVI", nullable = false, length = 200)
	public String getMotifSuivi() {
		return this.motifSuivi;
	}

	public void setMotifSuivi(String motifSuivi) {
		this.motifSuivi = motifSuivi;
	}

	@Column(name = "NUM_LIGNE", length = 20)
	public String getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(String numLigne) {
		this.numLigne = numLigne;
	}

	@Column(name = "TYPE_CLIENT", length = 50)
	public String getTypeClient() {
		return this.typeClient;
	}

	public void setTypeClient(String typeClient) {
		this.typeClient = typeClient;
	}

	@Column(name = "ID_CLIENT", length = 100)
	public String getIdClient() {
		return this.idClient;
	}

	public void setIdClient(String idClient) {
		this.idClient = idClient;
	}

	@Column(name = "NOM", length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "TYPE_IDENTIFIANT", length = 50)
	public String getTypeIdentifiant() {
		return this.typeIdentifiant;
	}

	public void setTypeIdentifiant(String typeIdentifiant) {
		this.typeIdentifiant = typeIdentifiant;
	}

	@Column(name = "IDENTIFIANT", length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "CONTACT_1", length = 100)
	public String getContact1() {
		return this.contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	@Column(name = "CONTACT_2", length = 100)
	public String getContact2() {
		return this.contact2;
	}

	public void setContact2(String contact2) {
		this.contact2 = contact2;
	}

	@Column(name = "ID_OFFRE", length = 50)
	public String getIdOffre() {
		return this.idOffre;
	}

	public void setIdOffre(String idOffre) {
		this.idOffre = idOffre;
	}

	@Column(name = "OFFRE", length = 200)
	public String getOffre() {
		return this.offre;
	}

	public void setOffre(String offre) {
		this.offre = offre;
	}

	@Column(name = "ID_ADR_INST", precision = 22, scale = 0)
	public BigDecimal getIdAdrInst() {
		return this.idAdrInst;
	}

	public void setIdAdrInst(BigDecimal idAdrInst) {
		this.idAdrInst = idAdrInst;
	}

	@Column(name = "ADR_INST", length = 1000)
	public String getAdrInst() {
		return this.adrInst;
	}

	public void setAdrInst(String adrInst) {
		this.adrInst = adrInst;
	}

	@Column(name = "TYPE_DGRP", precision = 1, scale = 0)
	public Boolean getTypeDgrp() {
		return this.typeDgrp;
	}

	public void setTypeDgrp(Boolean typeDgrp) {
		this.typeDgrp = typeDgrp;
	}

	@Column(name = "CODE_ACCES", length = 50)
	public String getCodeAcces() {
		return this.codeAcces;
	}

	public void setCodeAcces(String codeAcces) {
		this.codeAcces = codeAcces;
	}

	@Column(name = "OBS", length = 500)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcSuivi")
	public Set<ParcSsSuivi> getParcSsSuivis() {
		return this.parcSsSuivis;
	}

	public void setParcSsSuivis(Set<ParcSsSuivi> parcSsSuivis) {
		this.parcSsSuivis = parcSsSuivis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcSuivi")
	public Set<ParcPropSuivi> getParcPropSuivis() {
		return this.parcPropSuivis;
	}

	public void setParcPropSuivis(Set<ParcPropSuivi> parcPropSuivis) {
		this.parcPropSuivis = parcPropSuivis;
	}

}
