package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ParcProp generated by hbm2java
 */
@Entity
@Table(name = "PARC_PROP", schema = "TOM")
public class ParcProp implements java.io.Serializable {

	private ParcPropId id;
	private Parc parc;
	private ParcServ parcServ;
	private Propriete propriete;
	private String valeur;
	private String idValeur;

	public ParcProp() {
	}

	public ParcProp(ParcPropId id, Parc parc, ParcServ parcServ, Propriete propriete) {
		this.id = id;
		this.parc = parc;
		this.parcServ = parcServ;
		this.propriete = propriete;
	}

	public ParcProp(ParcPropId id, Parc parc, ParcServ parcServ, Propriete propriete, String valeur, String idValeur) {
		this.id = id;
		this.parc = parc;
		this.parcServ = parcServ;
		this.propriete = propriete;
		this.valeur = valeur;
		this.idValeur = idValeur;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "CProp", column = @Column(name = "C_PROP", nullable = false, length = 50)),
			@AttributeOverride(name = "idParc", column = @Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "groupe", column = @Column(name = "GROUPE", nullable = false, length = 50)) })
	public ParcPropId getId() {
		return this.id;
	}

	public void setId(ParcPropId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARC", nullable = false, insertable = false, updatable = false)
	public Parc getParc() {
		return this.parc;
	}

	public void setParc(Parc parc) {
		this.parc = parc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_PARC", referencedColumnName = "ID_PARC", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "C_TYPE_SERV", referencedColumnName = "C_TYPE_SERV", insertable = false, updatable = false) })
	public ParcServ getParcServ() {
		return this.parcServ;
	}

	public void setParcServ(ParcServ parcServ) {
		this.parcServ = parcServ;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PROP", nullable = false, insertable = false, updatable = false)
	public Propriete getPropriete() {
		return this.propriete;
	}

	public void setPropriete(Propriete propriete) {
		this.propriete = propriete;
	}

	@Column(name = "VALEUR", length = 200)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "ID_VALEUR", length = 100)
	public String getIdValeur() {
		return this.idValeur;
	}

	public void setIdValeur(String idValeur) {
		this.idValeur = idValeur;
	}

}
