package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ParcPropSuivi generated by hbm2java
 */
@Entity
@Table(name = "PARC_PROP_SUIVI", schema = "TOM")
public class ParcPropSuivi implements java.io.Serializable {

	private ParcPropSuiviId id;
	private ParcSuivi parcSuivi;
	private Propriete propriete;
	private String valeur;
	private String idValeur;

	public ParcPropSuivi() {
	}

	public ParcPropSuivi(ParcPropSuiviId id, ParcSuivi parcSuivi, Propriete propriete) {
		this.id = id;
		this.parcSuivi = parcSuivi;
		this.propriete = propriete;
	}

	public ParcPropSuivi(ParcPropSuiviId id, ParcSuivi parcSuivi, Propriete propriete, String valeur, String idValeur) {
		this.id = id;
		this.parcSuivi = parcSuivi;
		this.propriete = propriete;
		this.valeur = valeur;
		this.idValeur = idValeur;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idParc", column = @Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "CProp", column = @Column(name = "C_PROP", nullable = false, length = 50)),
			@AttributeOverride(name = "DSuivi", column = @Column(name = "D_SUIVI", nullable = false, length = 11)),
			@AttributeOverride(name = "groupe", column = @Column(name = "GROUPE", nullable = false, length = 50)) })
	public ParcPropSuiviId getId() {
		return this.id;
	}

	public void setId(ParcPropSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_PARC", referencedColumnName = "ID_PARC", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "D_SUIVI", referencedColumnName = "D_SUIVI", nullable = false, insertable = false, updatable = false) })
	public ParcSuivi getParcSuivi() {
		return this.parcSuivi;
	}

	public void setParcSuivi(ParcSuivi parcSuivi) {
		this.parcSuivi = parcSuivi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PROP", nullable = false, insertable = false, updatable = false)
	public Propriete getPropriete() {
		return this.propriete;
	}

	public void setPropriete(Propriete propriete) {
		this.propriete = propriete;
	}

	@Column(name = "VALEUR", length = 200)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

	@Column(name = "ID_VALEUR", length = 100)
	public String getIdValeur() {
		return this.idValeur;
	}

	public void setIdValeur(String idValeur) {
		this.idValeur = idValeur;
	}

}
