package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ParcServSuivi generated by hbm2java
 */
@Entity
@Table(name = "PARC_SERV_SUIVI", schema = "TOM")
public class ParcServSuivi implements java.io.Serializable {

	private ParcServSuiviId id;
	private ParcServ parcServ;
	private Partenaire partenaire;
	private PrmParcEtat prmParcEtat;
	private String numLigne;
	private String codeAcces;
	private String obs;

	public ParcServSuivi() {
	}

	public ParcServSuivi(ParcServSuiviId id, ParcServ parcServ, PrmParcEtat prmParcEtat) {
		this.id = id;
		this.parcServ = parcServ;
		this.prmParcEtat = prmParcEtat;
	}

	public ParcServSuivi(ParcServSuiviId id, ParcServ parcServ, Partenaire partenaire, PrmParcEtat prmParcEtat,
			String numLigne, String codeAcces, String obs) {
		this.id = id;
		this.parcServ = parcServ;
		this.partenaire = partenaire;
		this.prmParcEtat = prmParcEtat;
		this.numLigne = numLigne;
		this.codeAcces = codeAcces;
		this.obs = obs;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idParc", column = @Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "CTypeServ", column = @Column(name = "C_TYPE_SERV", nullable = false, length = 20)),
			@AttributeOverride(name = "DSuivi", column = @Column(name = "D_SUIVI", nullable = false, length = 11)) })
	public ParcServSuiviId getId() {
		return this.id;
	}

	public void setId(ParcServSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_PARC", referencedColumnName = "ID_PARC", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "C_TYPE_SERV", referencedColumnName = "C_TYPE_SERV", nullable = false, insertable = false, updatable = false) })
	public ParcServ getParcServ() {
		return this.parcServ;
	}

	public void setParcServ(ParcServ parcServ) {
		this.parcServ = parcServ;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PART")
	public Partenaire getPartenaire() {
		return this.partenaire;
	}

	public void setPartenaire(Partenaire partenaire) {
		this.partenaire = partenaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmParcEtat getPrmParcEtat() {
		return this.prmParcEtat;
	}

	public void setPrmParcEtat(PrmParcEtat prmParcEtat) {
		this.prmParcEtat = prmParcEtat;
	}

	@Column(name = "NUM_LIGNE", length = 20)
	public String getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(String numLigne) {
		this.numLigne = numLigne;
	}

	@Column(name = "CODE_ACCES", length = 50)
	public String getCodeAcces() {
		return this.codeAcces;
	}

	public void setCodeAcces(String codeAcces) {
		this.codeAcces = codeAcces;
	}

	@Column(name = "OBS", length = 500)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
