package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParcPropId generated by hbm2java
 */
@Embeddable
public class ParcPropId implements java.io.Serializable {

	private String CProp;
	private BigDecimal idParc;
	private String groupe;

	public ParcPropId() {
	}

	public ParcPropId(String CProp, BigDecimal idParc, String groupe) {
		this.CProp = CProp;
		this.idParc = idParc;
		this.groupe = groupe;
	}

	@Column(name = "C_PROP", nullable = false, length = 50)
	public String getCProp() {
		return this.CProp;
	}

	public void setCProp(String CProp) {
		this.CProp = CProp;
	}

	@Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdParc() {
		return this.idParc;
	}

	public void setIdParc(BigDecimal idParc) {
		this.idParc = idParc;
	}

	@Column(name = "GROUPE", nullable = false, length = 50)
	public String getGroupe() {
		return this.groupe;
	}

	public void setGroupe(String groupe) {
		this.groupe = groupe;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParcPropId))
			return false;
		ParcPropId castOther = (ParcPropId) other;

		return ((this.getCProp() == castOther.getCProp()) || (this.getCProp() != null && castOther.getCProp() != null
				&& this.getCProp().equals(castOther.getCProp())))
				&& ((this.getIdParc() == castOther.getIdParc()) || (this.getIdParc() != null
						&& castOther.getIdParc() != null && this.getIdParc().equals(castOther.getIdParc())))
				&& ((this.getGroupe() == castOther.getGroupe()) || (this.getGroupe() != null
						&& castOther.getGroupe() != null && this.getGroupe().equals(castOther.getGroupe())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCProp() == null ? 0 : this.getCProp().hashCode());
		result = 37 * result + (getIdParc() == null ? 0 : this.getIdParc().hashCode());
		result = 37 * result + (getGroupe() == null ? 0 : this.getGroupe().hashCode());
		return result;
	}

}
