package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParcPropSuiviId generated by hbm2java
 */
@Embeddable
public class ParcPropSuiviId implements java.io.Serializable {

	private BigDecimal idParc;
	private String CProp;
	private Date DSuivi;
	private String groupe;

	public ParcPropSuiviId() {
	}

	public ParcPropSuiviId(BigDecimal idParc, String CProp, Date DSuivi, String groupe) {
		this.idParc = idParc;
		this.CProp = CProp;
		this.DSuivi = DSuivi;
		this.groupe = groupe;
	}

	@Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdParc() {
		return this.idParc;
	}

	public void setIdParc(BigDecimal idParc) {
		this.idParc = idParc;
	}

	@Column(name = "C_PROP", nullable = false, length = 50)
	public String getCProp() {
		return this.CProp;
	}

	public void setCProp(String CProp) {
		this.CProp = CProp;
	}

	@Column(name = "D_SUIVI", nullable = false, length = 11)
	public Date getDSuivi() {
		return this.DSuivi;
	}

	public void setDSuivi(Date DSuivi) {
		this.DSuivi = DSuivi;
	}

	@Column(name = "GROUPE", nullable = false, length = 50)
	public String getGroupe() {
		return this.groupe;
	}

	public void setGroupe(String groupe) {
		this.groupe = groupe;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParcPropSuiviId))
			return false;
		ParcPropSuiviId castOther = (ParcPropSuiviId) other;

		return ((this.getIdParc() == castOther.getIdParc()) || (this.getIdParc() != null
				&& castOther.getIdParc() != null && this.getIdParc().equals(castOther.getIdParc())))
				&& ((this.getCProp() == castOther.getCProp()) || (this.getCProp() != null
						&& castOther.getCProp() != null && this.getCProp().equals(castOther.getCProp())))
				&& ((this.getDSuivi() == castOther.getDSuivi()) || (this.getDSuivi() != null
						&& castOther.getDSuivi() != null && this.getDSuivi().equals(castOther.getDSuivi())))
				&& ((this.getGroupe() == castOther.getGroupe()) || (this.getGroupe() != null
						&& castOther.getGroupe() != null && this.getGroupe().equals(castOther.getGroupe())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdParc() == null ? 0 : this.getIdParc().hashCode());
		result = 37 * result + (getCProp() == null ? 0 : this.getCProp().hashCode());
		result = 37 * result + (getDSuivi() == null ? 0 : this.getDSuivi().hashCode());
		result = 37 * result + (getGroupe() == null ? 0 : this.getGroupe().hashCode());
		return result;
	}

}
