package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParcSsSuivi generated by hbm2java
 */
@Entity
@Table(name = "PARC_SS_SUIVI", schema = "TOM")
public class ParcSsSuivi implements java.io.Serializable {

	private ParcSsSuiviId id;
	private ParcSuivi parcSuivi;
	private String idSsSrc;
	private String srvSupp;
	private String typeServSup;
	private Date DActiv;
	private Date DDesactiv;
	private Set<ParcSsPrmSuivi> parcSsPrmSuivis = new HashSet<ParcSsPrmSuivi>(0);

	public ParcSsSuivi() {
	}

	public ParcSsSuivi(ParcSsSuiviId id, ParcSuivi parcSuivi, String srvSupp, String typeServSup) {
		this.id = id;
		this.parcSuivi = parcSuivi;
		this.srvSupp = srvSupp;
		this.typeServSup = typeServSup;
	}

	public ParcSsSuivi(ParcSsSuiviId id, ParcSuivi parcSuivi, String idSsSrc, String srvSupp, String typeServSup,
			Date DActiv, Date DDesactiv, Set<ParcSsPrmSuivi> parcSsPrmSuivis) {
		this.id = id;
		this.parcSuivi = parcSuivi;
		this.idSsSrc = idSsSrc;
		this.srvSupp = srvSupp;
		this.typeServSup = typeServSup;
		this.DActiv = DActiv;
		this.DDesactiv = DDesactiv;
		this.parcSsPrmSuivis = parcSsPrmSuivis;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idParc", column = @Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "DSuivi", column = @Column(name = "D_SUIVI", nullable = false, length = 11)),
			@AttributeOverride(name = "noSs", column = @Column(name = "NO_SS", nullable = false, precision = 3, scale = 0)) })
	public ParcSsSuiviId getId() {
		return this.id;
	}

	public void setId(ParcSsSuiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_PARC", referencedColumnName = "ID_PARC", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "D_SUIVI", referencedColumnName = "D_SUIVI", nullable = false, insertable = false, updatable = false) })
	public ParcSuivi getParcSuivi() {
		return this.parcSuivi;
	}

	public void setParcSuivi(ParcSuivi parcSuivi) {
		this.parcSuivi = parcSuivi;
	}

	@Column(name = "ID_SS_SRC", length = 50)
	public String getIdSsSrc() {
		return this.idSsSrc;
	}

	public void setIdSsSrc(String idSsSrc) {
		this.idSsSrc = idSsSrc;
	}

	@Column(name = "SRV_SUPP", nullable = false, length = 100)
	public String getSrvSupp() {
		return this.srvSupp;
	}

	public void setSrvSupp(String srvSupp) {
		this.srvSupp = srvSupp;
	}

	@Column(name = "TYPE_SERV_SUP", nullable = false, length = 10)
	public String getTypeServSup() {
		return this.typeServSup;
	}

	public void setTypeServSup(String typeServSup) {
		this.typeServSup = typeServSup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ACTIV", length = 11)
	public Date getDActiv() {
		return this.DActiv;
	}

	public void setDActiv(Date DActiv) {
		this.DActiv = DActiv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_DESACTIV", length = 11)
	public Date getDDesactiv() {
		return this.DDesactiv;
	}

	public void setDDesactiv(Date DDesactiv) {
		this.DDesactiv = DDesactiv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcSsSuivi")
	public Set<ParcSsPrmSuivi> getParcSsPrmSuivis() {
		return this.parcSsPrmSuivis;
	}

	public void setParcSsPrmSuivis(Set<ParcSsPrmSuivi> parcSsPrmSuivis) {
		this.parcSsPrmSuivis = parcSsPrmSuivis;
	}

}
