package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParcServ generated by hbm2java
 */
@Entity
@Table(name = "PARC_SERV", schema = "TOM")
public class ParcServ implements java.io.Serializable {

	private ParcServId id;
	private Parc parc;
	private Partenaire partenaire;
	private PrmParcEtat prmParcEtat;
	private PrmTypeServ prmTypeServ;
	private String numLigne;
	private String codeAcces;
	private Date DLiv;
	private Date DEtat;
	private String obs;
	private Set<ParcProp> parcProps = new HashSet<ParcProp>(0);
	private Set<ParcServSuivi> parcServSuivis = new HashSet<ParcServSuivi>(0);

	public ParcServ() {
	}

	public ParcServ(ParcServId id, Parc parc, PrmParcEtat prmParcEtat, PrmTypeServ prmTypeServ, Date DLiv, Date DEtat) {
		this.id = id;
		this.parc = parc;
		this.prmParcEtat = prmParcEtat;
		this.prmTypeServ = prmTypeServ;
		this.DLiv = DLiv;
		this.DEtat = DEtat;
	}

	public ParcServ(ParcServId id, Parc parc, Partenaire partenaire, PrmParcEtat prmParcEtat, PrmTypeServ prmTypeServ,
			String numLigne, String codeAcces, Date DLiv, Date DEtat, String obs, Set<ParcProp> parcProps,
			Set<ParcServSuivi> parcServSuivis) {
		this.id = id;
		this.parc = parc;
		this.partenaire = partenaire;
		this.prmParcEtat = prmParcEtat;
		this.prmTypeServ = prmTypeServ;
		this.numLigne = numLigne;
		this.codeAcces = codeAcces;
		this.DLiv = DLiv;
		this.DEtat = DEtat;
		this.obs = obs;
		this.parcProps = parcProps;
		this.parcServSuivis = parcServSuivis;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idParc", column = @Column(name = "ID_PARC", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "CTypeServ", column = @Column(name = "C_TYPE_SERV", nullable = false, length = 20)) })
	public ParcServId getId() {
		return this.id;
	}

	public void setId(ParcServId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARC", nullable = false, insertable = false, updatable = false)
	public Parc getParc() {
		return this.parc;
	}

	public void setParc(Parc parc) {
		this.parc = parc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PART")
	public Partenaire getPartenaire() {
		return this.partenaire;
	}

	public void setPartenaire(Partenaire partenaire) {
		this.partenaire = partenaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false)
	public PrmParcEtat getPrmParcEtat() {
		return this.prmParcEtat;
	}

	public void setPrmParcEtat(PrmParcEtat prmParcEtat) {
		this.prmParcEtat = prmParcEtat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_SERV", nullable = false, insertable = false, updatable = false)
	public PrmTypeServ getPrmTypeServ() {
		return this.prmTypeServ;
	}

	public void setPrmTypeServ(PrmTypeServ prmTypeServ) {
		this.prmTypeServ = prmTypeServ;
	}

	@Column(name = "NUM_LIGNE", length = 20)
	public String getNumLigne() {
		return this.numLigne;
	}

	public void setNumLigne(String numLigne) {
		this.numLigne = numLigne;
	}

	@Column(name = "CODE_ACCES", length = 50)
	public String getCodeAcces() {
		return this.codeAcces;
	}

	public void setCodeAcces(String codeAcces) {
		this.codeAcces = codeAcces;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_LIV", nullable = false, length = 11)
	public Date getDLiv() {
		return this.DLiv;
	}

	public void setDLiv(Date DLiv) {
		this.DLiv = DLiv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ETAT", nullable = false, length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	@Column(name = "OBS", length = 500)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcServ")
	public Set<ParcProp> getParcProps() {
		return this.parcProps;
	}

	public void setParcProps(Set<ParcProp> parcProps) {
		this.parcProps = parcProps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parcServ")
	public Set<ParcServSuivi> getParcServSuivis() {
		return this.parcServSuivis;
	}

	public void setParcServSuivis(Set<ParcServSuivi> parcServSuivis) {
		this.parcServSuivis = parcServSuivis;
	}

}
