package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PlagesNumero generated by hbm2java
 */
@Entity
@Table(name = "PLAGES_NUMERO", schema = "TOM")
public class PlagesNumero implements java.io.Serializable {

	private PlagesNumeroId id;

	public PlagesNumero() {
	}

	public PlagesNumero(PlagesNumeroId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codRegion", column = @Column(name = "COD_REGION", length = 258)),
			@AttributeOverride(name = "codCentral", column = @Column(name = "COD_CENTRAL", length = 4)),
			@AttributeOverride(name = "numTelDu", column = @Column(name = "NUM_TEL_DU", precision = 22, scale = 0)),
			@AttributeOverride(name = "numTelAu", column = @Column(name = "NUM_TEL_AU", precision = 22, scale = 0)),
			@AttributeOverride(name = "rgId", column = @Column(name = "RG_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "codCdc", column = @Column(name = "COD_CDC", length = 20)),
			@AttributeOverride(name = "codeActel", column = @Column(name = "CODE_ACTEL", length = 3)) })
	public PlagesNumeroId getId() {
		return this.id;
	}

	public void setId(PlagesNumeroId id) {
		this.id = id;
	}

}
