package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PlagesNumeroVirt generated by hbm2java
 */
@Entity
@Table(name = "PLAGES_NUMERO_VIRT", schema = "TOM")
public class PlagesNumeroVirt implements java.io.Serializable {

	private PlagesNumeroVirtId id;

	public PlagesNumeroVirt() {
	}

	public PlagesNumeroVirt(PlagesNumeroVirtId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "numTelDu", column = @Column(name = "NUM_TEL_DU", precision = 22, scale = 0)),
			@AttributeOverride(name = "numTelAu", column = @Column(name = "NUM_TEL_AU", precision = 22, scale = 0)),
			@AttributeOverride(name = "cleDatasource", column = @Column(name = "CLE_DATASOURCE", length = 100)),
			@AttributeOverride(name = "tableName", column = @Column(name = "TABLE_NAME", length = 50)),
			@AttributeOverride(name = "numLigneColumn", column = @Column(name = "NUM_LIGNE_COLUMN", length = 50)),
			@AttributeOverride(name = "codeRegionColumn", column = @Column(name = "CODE_REGION_COLUMN", length = 50)) })
	public PlagesNumeroVirtId getId() {
		return this.id;
	}

	public void setId(PlagesNumeroVirtId id) {
		this.id = id;
	}

}
