package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlagesNumeroId generated by hbm2java
 */
@Embeddable
public class PlagesNumeroId implements java.io.Serializable {

	private String codRegion;
	private String codCentral;
	private BigDecimal numTelDu;
	private BigDecimal numTelAu;
	private BigDecimal rgId;
	private String codCdc;
	private String codeActel;

	public PlagesNumeroId() {
	}

	public PlagesNumeroId(String codRegion, String codCentral, BigDecimal numTelDu, BigDecimal numTelAu,
			BigDecimal rgId, String codCdc, String codeActel) {
		this.codRegion = codRegion;
		this.codCentral = codCentral;
		this.numTelDu = numTelDu;
		this.numTelAu = numTelAu;
		this.rgId = rgId;
		this.codCdc = codCdc;
		this.codeActel = codeActel;
	}

	@Column(name = "COD_REGION", length = 258)
	public String getCodRegion() {
		return this.codRegion;
	}

	public void setCodRegion(String codRegion) {
		this.codRegion = codRegion;
	}

	@Column(name = "COD_CENTRAL", length = 4)
	public String getCodCentral() {
		return this.codCentral;
	}

	public void setCodCentral(String codCentral) {
		this.codCentral = codCentral;
	}

	@Column(name = "NUM_TEL_DU", precision = 22, scale = 0)
	public BigDecimal getNumTelDu() {
		return this.numTelDu;
	}

	public void setNumTelDu(BigDecimal numTelDu) {
		this.numTelDu = numTelDu;
	}

	@Column(name = "NUM_TEL_AU", precision = 22, scale = 0)
	public BigDecimal getNumTelAu() {
		return this.numTelAu;
	}

	public void setNumTelAu(BigDecimal numTelAu) {
		this.numTelAu = numTelAu;
	}

	@Column(name = "RG_ID", precision = 22, scale = 0)
	public BigDecimal getRgId() {
		return this.rgId;
	}

	public void setRgId(BigDecimal rgId) {
		this.rgId = rgId;
	}

	@Column(name = "COD_CDC", length = 20)
	public String getCodCdc() {
		return this.codCdc;
	}

	public void setCodCdc(String codCdc) {
		this.codCdc = codCdc;
	}

	@Column(name = "CODE_ACTEL", length = 3)
	public String getCodeActel() {
		return this.codeActel;
	}

	public void setCodeActel(String codeActel) {
		this.codeActel = codeActel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlagesNumeroId))
			return false;
		PlagesNumeroId castOther = (PlagesNumeroId) other;

		return ((this.getCodRegion() == castOther.getCodRegion()) || (this.getCodRegion() != null
				&& castOther.getCodRegion() != null && this.getCodRegion().equals(castOther.getCodRegion())))
				&& ((this.getCodCentral() == castOther.getCodCentral()) || (this.getCodCentral() != null
						&& castOther.getCodCentral() != null && this.getCodCentral().equals(castOther.getCodCentral())))
				&& ((this.getNumTelDu() == castOther.getNumTelDu()) || (this.getNumTelDu() != null
						&& castOther.getNumTelDu() != null && this.getNumTelDu().equals(castOther.getNumTelDu())))
				&& ((this.getNumTelAu() == castOther.getNumTelAu()) || (this.getNumTelAu() != null
						&& castOther.getNumTelAu() != null && this.getNumTelAu().equals(castOther.getNumTelAu())))
				&& ((this.getRgId() == castOther.getRgId()) || (this.getRgId() != null && castOther.getRgId() != null
						&& this.getRgId().equals(castOther.getRgId())))
				&& ((this.getCodCdc() == castOther.getCodCdc()) || (this.getCodCdc() != null
						&& castOther.getCodCdc() != null && this.getCodCdc().equals(castOther.getCodCdc())))
				&& ((this.getCodeActel() == castOther.getCodeActel()) || (this.getCodeActel() != null
						&& castOther.getCodeActel() != null && this.getCodeActel().equals(castOther.getCodeActel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodRegion() == null ? 0 : this.getCodRegion().hashCode());
		result = 37 * result + (getCodCentral() == null ? 0 : this.getCodCentral().hashCode());
		result = 37 * result + (getNumTelDu() == null ? 0 : this.getNumTelDu().hashCode());
		result = 37 * result + (getNumTelAu() == null ? 0 : this.getNumTelAu().hashCode());
		result = 37 * result + (getRgId() == null ? 0 : this.getRgId().hashCode());
		result = 37 * result + (getCodCdc() == null ? 0 : this.getCodCdc().hashCode());
		result = 37 * result + (getCodeActel() == null ? 0 : this.getCodeActel().hashCode());
		return result;
	}

}
