package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlagesNumeroVirtId generated by hbm2java
 */
@Embeddable
public class PlagesNumeroVirtId implements java.io.Serializable {

	private BigDecimal numTelDu;
	private BigDecimal numTelAu;
	private String cleDatasource;
	private String tableName;
	private String numLigneColumn;
	private String codeRegionColumn;

	public PlagesNumeroVirtId() {
	}

	public PlagesNumeroVirtId(BigDecimal numTelDu, BigDecimal numTelAu, String cleDatasource, String tableName,
			String numLigneColumn, String codeRegionColumn) {
		this.numTelDu = numTelDu;
		this.numTelAu = numTelAu;
		this.cleDatasource = cleDatasource;
		this.tableName = tableName;
		this.numLigneColumn = numLigneColumn;
		this.codeRegionColumn = codeRegionColumn;
	}

	@Column(name = "NUM_TEL_DU", precision = 22, scale = 0)
	public BigDecimal getNumTelDu() {
		return this.numTelDu;
	}

	public void setNumTelDu(BigDecimal numTelDu) {
		this.numTelDu = numTelDu;
	}

	@Column(name = "NUM_TEL_AU", precision = 22, scale = 0)
	public BigDecimal getNumTelAu() {
		return this.numTelAu;
	}

	public void setNumTelAu(BigDecimal numTelAu) {
		this.numTelAu = numTelAu;
	}

	@Column(name = "CLE_DATASOURCE", length = 100)
	public String getCleDatasource() {
		return this.cleDatasource;
	}

	public void setCleDatasource(String cleDatasource) {
		this.cleDatasource = cleDatasource;
	}

	@Column(name = "TABLE_NAME", length = 50)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "NUM_LIGNE_COLUMN", length = 50)
	public String getNumLigneColumn() {
		return this.numLigneColumn;
	}

	public void setNumLigneColumn(String numLigneColumn) {
		this.numLigneColumn = numLigneColumn;
	}

	@Column(name = "CODE_REGION_COLUMN", length = 50)
	public String getCodeRegionColumn() {
		return this.codeRegionColumn;
	}

	public void setCodeRegionColumn(String codeRegionColumn) {
		this.codeRegionColumn = codeRegionColumn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlagesNumeroVirtId))
			return false;
		PlagesNumeroVirtId castOther = (PlagesNumeroVirtId) other;

		return ((this.getNumTelDu() == castOther.getNumTelDu()) || (this.getNumTelDu() != null
				&& castOther.getNumTelDu() != null && this.getNumTelDu().equals(castOther.getNumTelDu())))
				&& ((this.getNumTelAu() == castOther.getNumTelAu()) || (this.getNumTelAu() != null
						&& castOther.getNumTelAu() != null && this.getNumTelAu().equals(castOther.getNumTelAu())))
				&& ((this.getCleDatasource() == castOther.getCleDatasource())
						|| (this.getCleDatasource() != null && castOther.getCleDatasource() != null
								&& this.getCleDatasource().equals(castOther.getCleDatasource())))
				&& ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
						&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& ((this.getNumLigneColumn() == castOther.getNumLigneColumn())
						|| (this.getNumLigneColumn() != null && castOther.getNumLigneColumn() != null
								&& this.getNumLigneColumn().equals(castOther.getNumLigneColumn())))
				&& ((this.getCodeRegionColumn() == castOther.getCodeRegionColumn())
						|| (this.getCodeRegionColumn() != null && castOther.getCodeRegionColumn() != null
								&& this.getCodeRegionColumn().equals(castOther.getCodeRegionColumn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNumTelDu() == null ? 0 : this.getNumTelDu().hashCode());
		result = 37 * result + (getNumTelAu() == null ? 0 : this.getNumTelAu().hashCode());
		result = 37 * result + (getCleDatasource() == null ? 0 : this.getCleDatasource().hashCode());
		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (getNumLigneColumn() == null ? 0 : this.getNumLigneColumn().hashCode());
		result = 37 * result + (getCodeRegionColumn() == null ? 0 : this.getCodeRegionColumn().hashCode());
		return result;
	}

}
