package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrmDemEtatPart generated by hbm2java
 */
@Entity
@Table(name = "PRM_DEM_ETAT_PART", schema = "TOM")
public class PrmDemEtatPart implements java.io.Serializable {

	private short noEtat;
	private String etat;
	private Set<PrmEtatMapping> prmEtatMappings = new HashSet<PrmEtatMapping>(0);

	public PrmDemEtatPart() {
	}

	public PrmDemEtatPart(short noEtat, String etat) {
		this.noEtat = noEtat;
		this.etat = etat;
	}

	public PrmDemEtatPart(short noEtat, String etat, Set<PrmEtatMapping> prmEtatMappings) {
		this.noEtat = noEtat;
		this.etat = etat;
		this.prmEtatMappings = prmEtatMappings;
	}

	@Id

	@Column(name = "NO_ETAT", unique = true, nullable = false, precision = 4, scale = 0)
	public short getNoEtat() {
		return this.noEtat;
	}

	public void setNoEtat(short noEtat) {
		this.noEtat = noEtat;
	}

	@Column(name = "ETAT", nullable = false, length = 100)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmDemEtatPart")
	public Set<PrmEtatMapping> getPrmEtatMappings() {
		return this.prmEtatMappings;
	}

	public void setPrmEtatMappings(Set<PrmEtatMapping> prmEtatMappings) {
		this.prmEtatMappings = prmEtatMappings;
	}

}
