package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrmDemMotifId generated by hbm2java
 */
@Embeddable
public class PrmDemMotifId implements java.io.Serializable {

	private String CMotif;
	private String COp;
	private short noEtat;

	public PrmDemMotifId() {
	}

	public PrmDemMotifId(String CMotif, String COp, short noEtat) {
		this.CMotif = CMotif;
		this.COp = COp;
		this.noEtat = noEtat;
	}

	@Column(name = "C_MOTIF", nullable = false, length = 100)
	public String getCMotif() {
		return this.CMotif;
	}

	public void setCMotif(String CMotif) {
		this.CMotif = CMotif;
	}

	@Column(name = "C_OP", nullable = false, length = 20)
	public String getCOp() {
		return this.COp;
	}

	public void setCOp(String COp) {
		this.COp = COp;
	}

	@Column(name = "NO_ETAT", nullable = false, precision = 3, scale = 0)
	public short getNoEtat() {
		return this.noEtat;
	}

	public void setNoEtat(short noEtat) {
		this.noEtat = noEtat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrmDemMotifId))
			return false;
		PrmDemMotifId castOther = (PrmDemMotifId) other;

		return ((this.getCMotif() == castOther.getCMotif()) || (this.getCMotif() != null
				&& castOther.getCMotif() != null && this.getCMotif().equals(castOther.getCMotif())))
				&& ((this.getCOp() == castOther.getCOp()) || (this.getCOp() != null && castOther.getCOp() != null
						&& this.getCOp().equals(castOther.getCOp())))
				&& (this.getNoEtat() == castOther.getNoEtat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCMotif() == null ? 0 : this.getCMotif().hashCode());
		result = 37 * result + (getCOp() == null ? 0 : this.getCOp().hashCode());
		result = 37 * result + this.getNoEtat();
		return result;
	}

}
