package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrmEtatMappingId generated by hbm2java
 */
@Embeddable
public class PrmEtatMappingId implements java.io.Serializable {

	private String COp;
	private short prmNoEtat;
	private short noEtat;
	private String CPart;

	public PrmEtatMappingId() {
	}

	public PrmEtatMappingId(String COp, short prmNoEtat, short noEtat, String CPart) {
		this.COp = COp;
		this.prmNoEtat = prmNoEtat;
		this.noEtat = noEtat;
		this.CPart = CPart;
	}

	@Column(name = "C_OP", nullable = false, length = 20)
	public String getCOp() {
		return this.COp;
	}

	public void setCOp(String COp) {
		this.COp = COp;
	}

	@Column(name = "PRM_NO_ETAT", nullable = false, precision = 3, scale = 0)
	public short getPrmNoEtat() {
		return this.prmNoEtat;
	}

	public void setPrmNoEtat(short prmNoEtat) {
		this.prmNoEtat = prmNoEtat;
	}

	@Column(name = "NO_ETAT", nullable = false, precision = 4, scale = 0)
	public short getNoEtat() {
		return this.noEtat;
	}

	public void setNoEtat(short noEtat) {
		this.noEtat = noEtat;
	}

	@Column(name = "C_PART", nullable = false, length = 20)
	public String getCPart() {
		return this.CPart;
	}

	public void setCPart(String CPart) {
		this.CPart = CPart;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrmEtatMappingId))
			return false;
		PrmEtatMappingId castOther = (PrmEtatMappingId) other;

		return ((this.getCOp() == castOther.getCOp())
				|| (this.getCOp() != null && castOther.getCOp() != null && this.getCOp().equals(castOther.getCOp())))
				&& (this.getPrmNoEtat() == castOther.getPrmNoEtat()) && (this.getNoEtat() == castOther.getNoEtat())
				&& ((this.getCPart() == castOther.getCPart()) || (this.getCPart() != null
						&& castOther.getCPart() != null && this.getCPart().equals(castOther.getCPart())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCOp() == null ? 0 : this.getCOp().hashCode());
		result = 37 * result + this.getPrmNoEtat();
		result = 37 * result + this.getNoEtat();
		result = 37 * result + (getCPart() == null ? 0 : this.getCPart().hashCode());
		return result;
	}

}
