package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrmEtatMapping generated by hbm2java
 */
@Entity
@Table(name = "PRM_ETAT_MAPPING", schema = "TOM")
public class PrmEtatMapping implements java.io.Serializable {

	private PrmEtatMappingId id;
	private Partenaire partenaire;
	private PrmDemEtatOp prmDemEtatOp;
	private PrmDemEtatPart prmDemEtatPart;

	public PrmEtatMapping() {
	}

	public PrmEtatMapping(PrmEtatMappingId id, Partenaire partenaire, PrmDemEtatOp prmDemEtatOp,
			PrmDemEtatPart prmDemEtatPart) {
		this.id = id;
		this.partenaire = partenaire;
		this.prmDemEtatOp = prmDemEtatOp;
		this.prmDemEtatPart = prmDemEtatPart;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "COp", column = @Column(name = "C_OP", nullable = false, length = 20)),
			@AttributeOverride(name = "prmNoEtat", column = @Column(name = "PRM_NO_ETAT", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "noEtat", column = @Column(name = "NO_ETAT", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "CPart", column = @Column(name = "C_PART", nullable = false, length = 20)) })
	public PrmEtatMappingId getId() {
		return this.id;
	}

	public void setId(PrmEtatMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PART", nullable = false, insertable = false, updatable = false)
	public Partenaire getPartenaire() {
		return this.partenaire;
	}

	public void setPartenaire(Partenaire partenaire) {
		this.partenaire = partenaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "C_OP", referencedColumnName = "C_OP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRM_NO_ETAT", referencedColumnName = "NO_ETAT", nullable = false, insertable = false, updatable = false) })
	public PrmDemEtatOp getPrmDemEtatOp() {
		return this.prmDemEtatOp;
	}

	public void setPrmDemEtatOp(PrmDemEtatOp prmDemEtatOp) {
		this.prmDemEtatOp = prmDemEtatOp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false, insertable = false, updatable = false)
	public PrmDemEtatPart getPrmDemEtatPart() {
		return this.prmDemEtatPart;
	}

	public void setPrmDemEtatPart(PrmDemEtatPart prmDemEtatPart) {
		this.prmDemEtatPart = prmDemEtatPart;
	}

}
