package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrmOtMotifId generated by hbm2java
 */
@Embeddable
public class PrmOtMotifId implements java.io.Serializable {

	private String CMotif;
	private String CTypeOt;
	private short noEtat;
	private String COp;

	public PrmOtMotifId() {
	}

	public PrmOtMotifId(String CMotif, String CTypeOt, short noEtat, String COp) {
		this.CMotif = CMotif;
		this.CTypeOt = CTypeOt;
		this.noEtat = noEtat;
		this.COp = COp;
	}

	@Column(name = "C_MOTIF", nullable = false, length = 100)
	public String getCMotif() {
		return this.CMotif;
	}

	public void setCMotif(String CMotif) {
		this.CMotif = CMotif;
	}

	@Column(name = "C_TYPE_OT", nullable = false, length = 20)
	public String getCTypeOt() {
		return this.CTypeOt;
	}

	public void setCTypeOt(String CTypeOt) {
		this.CTypeOt = CTypeOt;
	}

	@Column(name = "NO_ETAT", nullable = false, precision = 3, scale = 0)
	public short getNoEtat() {
		return this.noEtat;
	}

	public void setNoEtat(short noEtat) {
		this.noEtat = noEtat;
	}

	@Column(name = "C_OP", nullable = false, length = 20)
	public String getCOp() {
		return this.COp;
	}

	public void setCOp(String COp) {
		this.COp = COp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrmOtMotifId))
			return false;
		PrmOtMotifId castOther = (PrmOtMotifId) other;

		return ((this.getCMotif() == castOther.getCMotif()) || (this.getCMotif() != null
				&& castOther.getCMotif() != null && this.getCMotif().equals(castOther.getCMotif())))
				&& ((this.getCTypeOt() == castOther.getCTypeOt()) || (this.getCTypeOt() != null
						&& castOther.getCTypeOt() != null && this.getCTypeOt().equals(castOther.getCTypeOt())))
				&& (this.getNoEtat() == castOther.getNoEtat())
				&& ((this.getCOp() == castOther.getCOp()) || (this.getCOp() != null && castOther.getCOp() != null
						&& this.getCOp().equals(castOther.getCOp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCMotif() == null ? 0 : this.getCMotif().hashCode());
		result = 37 * result + (getCTypeOt() == null ? 0 : this.getCTypeOt().hashCode());
		result = 37 * result + this.getNoEtat();
		result = 37 * result + (getCOp() == null ? 0 : this.getCOp().hashCode());
		return result;
	}

}
