package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrmOtEtat generated by hbm2java
 */
@Entity
@Table(name = "PRM_OT_ETAT", schema = "TOM")
public class PrmOtEtat implements java.io.Serializable {

	private short noEtat;
	private String etat;
	private String CEtatBpm;
	private Set<Ot> ots = new HashSet<Ot>(0);
	private Set<PrmOtMotif> prmOtMotifs = new HashSet<PrmOtMotif>(0);
	private Set<DunningOtSuivi> dunningOtSuivis = new HashSet<DunningOtSuivi>(0);
	private Set<PrmOtType> prmOtTypes = new HashSet<PrmOtType>(0);
	private Set<DunningOt> dunningOts = new HashSet<DunningOt>(0);
	private Set<OtSuivi> otSuivis = new HashSet<OtSuivi>(0);

	public PrmOtEtat() {
	}

	public PrmOtEtat(short noEtat, String etat) {
		this.noEtat = noEtat;
		this.etat = etat;
	}

	public PrmOtEtat(short noEtat, String etat, String CEtatBpm, Set<Ot> ots, Set<PrmOtMotif> prmOtMotifs,
			Set<DunningOtSuivi> dunningOtSuivis, Set<PrmOtType> prmOtTypes, Set<DunningOt> dunningOts,
			Set<OtSuivi> otSuivis) {
		this.noEtat = noEtat;
		this.etat = etat;
		this.CEtatBpm = CEtatBpm;
		this.ots = ots;
		this.prmOtMotifs = prmOtMotifs;
		this.dunningOtSuivis = dunningOtSuivis;
		this.prmOtTypes = prmOtTypes;
		this.dunningOts = dunningOts;
		this.otSuivis = otSuivis;
	}

	@Id

	@Column(name = "NO_ETAT", unique = true, nullable = false, precision = 3, scale = 0)
	public short getNoEtat() {
		return this.noEtat;
	}

	public void setNoEtat(short noEtat) {
		this.noEtat = noEtat;
	}

	@Column(name = "ETAT", nullable = false, length = 100)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "C_ETAT_BPM", length = 200)
	public String getCEtatBpm() {
		return this.CEtatBpm;
	}

	public void setCEtatBpm(String CEtatBpm) {
		this.CEtatBpm = CEtatBpm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtEtat")
	public Set<Ot> getOts() {
		return this.ots;
	}

	public void setOts(Set<Ot> ots) {
		this.ots = ots;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtEtat")
	public Set<PrmOtMotif> getPrmOtMotifs() {
		return this.prmOtMotifs;
	}

	public void setPrmOtMotifs(Set<PrmOtMotif> prmOtMotifs) {
		this.prmOtMotifs = prmOtMotifs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtEtat")
	public Set<DunningOtSuivi> getDunningOtSuivis() {
		return this.dunningOtSuivis;
	}

	public void setDunningOtSuivis(Set<DunningOtSuivi> dunningOtSuivis) {
		this.dunningOtSuivis = dunningOtSuivis;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "prmOtEtats")
	public Set<PrmOtType> getPrmOtTypes() {
		return this.prmOtTypes;
	}

	public void setPrmOtTypes(Set<PrmOtType> prmOtTypes) {
		this.prmOtTypes = prmOtTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtEtat")
	public Set<DunningOt> getDunningOts() {
		return this.dunningOts;
	}

	public void setDunningOts(Set<DunningOt> dunningOts) {
		this.dunningOts = dunningOts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtEtat")
	public Set<OtSuivi> getOtSuivis() {
		return this.otSuivis;
	}

	public void setOtSuivis(Set<OtSuivi> otSuivis) {
		this.otSuivis = otSuivis;
	}

}
