package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrmOtType generated by hbm2java
 */
@Entity
@Table(name = "PRM_OT_TYPE", schema = "TOM")
public class PrmOtType implements java.io.Serializable {

	private String CTypeOt;
	private PrmOtType prmOtType;
	private UniteType uniteTypeByCTypeUniteSec;
	private UniteType uniteTypeByCTypeUnite;
	private String typeOt;
	private boolean FAffect;
	private Boolean FResAuto;
	private boolean FSs;
	private Boolean FImprim;
	private Short jalon;
	private short classe;
	private boolean FModifUt;
	private Set<PrmTypeOtProp> prmTypeOtProps = new HashSet<PrmTypeOtProp>(0);
	private Set<Ot> ots = new HashSet<Ot>(0);
	private Set<PrmOpOtPart> prmOpOtParts = new HashSet<PrmOpOtPart>(0);
	private Set<DunningOt> dunningOts = new HashSet<DunningOt>(0);
	private Set<Operation> operations = new HashSet<Operation>(0);
	private Set<PrmOtMotif> prmOtMotifs = new HashSet<PrmOtMotif>(0);
	private Set<PrmOtType> prmOtTypes = new HashSet<PrmOtType>(0);
	private Set<PrmOtEtat> prmOtEtats = new HashSet<PrmOtEtat>(0);

	public PrmOtType() {
	}

	public PrmOtType(String CTypeOt, UniteType uniteTypeByCTypeUnite, String typeOt, boolean FAffect, boolean FSs,
			short classe, boolean FModifUt) {
		this.CTypeOt = CTypeOt;
		this.uniteTypeByCTypeUnite = uniteTypeByCTypeUnite;
		this.typeOt = typeOt;
		this.FAffect = FAffect;
		this.FSs = FSs;
		this.classe = classe;
		this.FModifUt = FModifUt;
	}

	public PrmOtType(String CTypeOt, PrmOtType prmOtType, UniteType uniteTypeByCTypeUniteSec,
			UniteType uniteTypeByCTypeUnite, String typeOt, boolean FAffect, Boolean FResAuto, boolean FSs,
			Boolean FImprim, Short jalon, short classe, boolean FModifUt, Set<PrmTypeOtProp> prmTypeOtProps,
			Set<Ot> ots, Set<PrmOpOtPart> prmOpOtParts, Set<DunningOt> dunningOts, Set<Operation> operations,
			Set<PrmOtMotif> prmOtMotifs, Set<PrmOtType> prmOtTypes, Set<PrmOtEtat> prmOtEtats) {
		this.CTypeOt = CTypeOt;
		this.prmOtType = prmOtType;
		this.uniteTypeByCTypeUniteSec = uniteTypeByCTypeUniteSec;
		this.uniteTypeByCTypeUnite = uniteTypeByCTypeUnite;
		this.typeOt = typeOt;
		this.FAffect = FAffect;
		this.FResAuto = FResAuto;
		this.FSs = FSs;
		this.FImprim = FImprim;
		this.jalon = jalon;
		this.classe = classe;
		this.FModifUt = FModifUt;
		this.prmTypeOtProps = prmTypeOtProps;
		this.ots = ots;
		this.prmOpOtParts = prmOpOtParts;
		this.dunningOts = dunningOts;
		this.operations = operations;
		this.prmOtMotifs = prmOtMotifs;
		this.prmOtTypes = prmOtTypes;
		this.prmOtEtats = prmOtEtats;
	}

	@Id

	@Column(name = "C_TYPE_OT", unique = true, nullable = false, length = 20)
	public String getCTypeOt() {
		return this.CTypeOt;
	}

	public void setCTypeOt(String CTypeOt) {
		this.CTypeOt = CTypeOt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_OT_PERE")
	public PrmOtType getPrmOtType() {
		return this.prmOtType;
	}

	public void setPrmOtType(PrmOtType prmOtType) {
		this.prmOtType = prmOtType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_UNITE_SEC")
	public UniteType getUniteTypeByCTypeUniteSec() {
		return this.uniteTypeByCTypeUniteSec;
	}

	public void setUniteTypeByCTypeUniteSec(UniteType uniteTypeByCTypeUniteSec) {
		this.uniteTypeByCTypeUniteSec = uniteTypeByCTypeUniteSec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_UNITE", nullable = false)
	public UniteType getUniteTypeByCTypeUnite() {
		return this.uniteTypeByCTypeUnite;
	}

	public void setUniteTypeByCTypeUnite(UniteType uniteTypeByCTypeUnite) {
		this.uniteTypeByCTypeUnite = uniteTypeByCTypeUnite;
	}

	@Column(name = "TYPE_OT", nullable = false, length = 100)
	public String getTypeOt() {
		return this.typeOt;
	}

	public void setTypeOt(String typeOt) {
		this.typeOt = typeOt;
	}

	@Column(name = "F_AFFECT", nullable = false, precision = 1, scale = 0)
	public boolean isFAffect() {
		return this.FAffect;
	}

	public void setFAffect(boolean FAffect) {
		this.FAffect = FAffect;
	}

	@Column(name = "F_RES_AUTO", precision = 1, scale = 0)
	public Boolean getFResAuto() {
		return this.FResAuto;
	}

	public void setFResAuto(Boolean FResAuto) {
		this.FResAuto = FResAuto;
	}

	@Column(name = "F_SS", nullable = false, precision = 1, scale = 0)
	public boolean isFSs() {
		return this.FSs;
	}

	public void setFSs(boolean FSs) {
		this.FSs = FSs;
	}

	@Column(name = "F_IMPRIM", precision = 1, scale = 0)
	public Boolean getFImprim() {
		return this.FImprim;
	}

	public void setFImprim(Boolean FImprim) {
		this.FImprim = FImprim;
	}

	@Column(name = "JALON", precision = 3, scale = 0)
	public Short getJalon() {
		return this.jalon;
	}

	public void setJalon(Short jalon) {
		this.jalon = jalon;
	}

	@Column(name = "CLASSE", nullable = false, precision = 3, scale = 0)
	public short getClasse() {
		return this.classe;
	}

	public void setClasse(short classe) {
		this.classe = classe;
	}

	@Column(name = "F_MODIF_UT", nullable = false, precision = 1, scale = 0)
	public boolean isFModifUt() {
		return this.FModifUt;
	}

	public void setFModifUt(boolean FModifUt) {
		this.FModifUt = FModifUt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtType")
	public Set<PrmTypeOtProp> getPrmTypeOtProps() {
		return this.prmTypeOtProps;
	}

	public void setPrmTypeOtProps(Set<PrmTypeOtProp> prmTypeOtProps) {
		this.prmTypeOtProps = prmTypeOtProps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtType")
	public Set<Ot> getOts() {
		return this.ots;
	}

	public void setOts(Set<Ot> ots) {
		this.ots = ots;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtType")
	public Set<PrmOpOtPart> getPrmOpOtParts() {
		return this.prmOpOtParts;
	}

	public void setPrmOpOtParts(Set<PrmOpOtPart> prmOpOtParts) {
		this.prmOpOtParts = prmOpOtParts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtType")
	public Set<DunningOt> getDunningOts() {
		return this.dunningOts;
	}

	public void setDunningOts(Set<DunningOt> dunningOts) {
		this.dunningOts = dunningOts;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "prmOtTypes")
	public Set<Operation> getOperations() {
		return this.operations;
	}

	public void setOperations(Set<Operation> operations) {
		this.operations = operations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtType")
	public Set<PrmOtMotif> getPrmOtMotifs() {
		return this.prmOtMotifs;
	}

	public void setPrmOtMotifs(Set<PrmOtMotif> prmOtMotifs) {
		this.prmOtMotifs = prmOtMotifs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmOtType")
	public Set<PrmOtType> getPrmOtTypes() {
		return this.prmOtTypes;
	}

	public void setPrmOtTypes(Set<PrmOtType> prmOtTypes) {
		this.prmOtTypes = prmOtTypes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "PRM_OT_TYPE_ETAT", schema = "TOM", joinColumns = {
			@JoinColumn(name = "C_TYPE_OT", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "NO_ETAT", nullable = false, updatable = false) })
	public Set<PrmOtEtat> getPrmOtEtats() {
		return this.prmOtEtats;
	}

	public void setPrmOtEtats(Set<PrmOtEtat> prmOtEtats) {
		this.prmOtEtats = prmOtEtats;
	}

}
