package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrmOpOtPartId generated by hbm2java
 */
@Embeddable
public class PrmOpOtPartId implements java.io.Serializable {

	private String COp;
	private String CTypeOt;
	private String CParam;
	private String CPart;

	public PrmOpOtPartId() {
	}

	public PrmOpOtPartId(String COp, String CTypeOt, String CParam, String CPart) {
		this.COp = COp;
		this.CTypeOt = CTypeOt;
		this.CParam = CParam;
		this.CPart = CPart;
	}

	@Column(name = "C_OP", nullable = false, length = 20)
	public String getCOp() {
		return this.COp;
	}

	public void setCOp(String COp) {
		this.COp = COp;
	}

	@Column(name = "C_TYPE_OT", nullable = false, length = 20)
	public String getCTypeOt() {
		return this.CTypeOt;
	}

	public void setCTypeOt(String CTypeOt) {
		this.CTypeOt = CTypeOt;
	}

	@Column(name = "C_PARAM", nullable = false, length = 50)
	public String getCParam() {
		return this.CParam;
	}

	public void setCParam(String CParam) {
		this.CParam = CParam;
	}

	@Column(name = "C_PART", nullable = false, length = 20)
	public String getCPart() {
		return this.CPart;
	}

	public void setCPart(String CPart) {
		this.CPart = CPart;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrmOpOtPartId))
			return false;
		PrmOpOtPartId castOther = (PrmOpOtPartId) other;

		return ((this.getCOp() == castOther.getCOp())
				|| (this.getCOp() != null && castOther.getCOp() != null && this.getCOp().equals(castOther.getCOp())))
				&& ((this.getCTypeOt() == castOther.getCTypeOt()) || (this.getCTypeOt() != null
						&& castOther.getCTypeOt() != null && this.getCTypeOt().equals(castOther.getCTypeOt())))
				&& ((this.getCParam() == castOther.getCParam()) || (this.getCParam() != null
						&& castOther.getCParam() != null && this.getCParam().equals(castOther.getCParam())))
				&& ((this.getCPart() == castOther.getCPart()) || (this.getCPart() != null
						&& castOther.getCPart() != null && this.getCPart().equals(castOther.getCPart())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCOp() == null ? 0 : this.getCOp().hashCode());
		result = 37 * result + (getCTypeOt() == null ? 0 : this.getCTypeOt().hashCode());
		result = 37 * result + (getCParam() == null ? 0 : this.getCParam().hashCode());
		result = 37 * result + (getCPart() == null ? 0 : this.getCPart().hashCode());
		return result;
	}

}
