package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrmOtMotif generated by hbm2java
 */
@Entity
@Table(name = "PRM_OT_MOTIF", schema = "TOM")
public class PrmOtMotif implements java.io.Serializable {

	private PrmOtMotifId id;
	private Motif motif;
	private Operation operation;
	private PrmOtEtat prmOtEtat;
	private PrmOtType prmOtType;
	private String typeMotif;

	public PrmOtMotif() {
	}

	public PrmOtMotif(PrmOtMotifId id, Motif motif, Operation operation, PrmOtEtat prmOtEtat, PrmOtType prmOtType) {
		this.id = id;
		this.motif = motif;
		this.operation = operation;
		this.prmOtEtat = prmOtEtat;
		this.prmOtType = prmOtType;
	}

	public PrmOtMotif(PrmOtMotifId id, Motif motif, Operation operation, PrmOtEtat prmOtEtat, PrmOtType prmOtType,
			String typeMotif) {
		this.id = id;
		this.motif = motif;
		this.operation = operation;
		this.prmOtEtat = prmOtEtat;
		this.prmOtType = prmOtType;
		this.typeMotif = typeMotif;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "CMotif", column = @Column(name = "C_MOTIF", nullable = false, length = 100)),
			@AttributeOverride(name = "CTypeOt", column = @Column(name = "C_TYPE_OT", nullable = false, length = 20)),
			@AttributeOverride(name = "noEtat", column = @Column(name = "NO_ETAT", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "COp", column = @Column(name = "C_OP", nullable = false, length = 20)) })
	public PrmOtMotifId getId() {
		return this.id;
	}

	public void setId(PrmOtMotifId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_MOTIF", nullable = false, insertable = false, updatable = false)
	public Motif getMotif() {
		return this.motif;
	}

	public void setMotif(Motif motif) {
		this.motif = motif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_OP", nullable = false, insertable = false, updatable = false)
	public Operation getOperation() {
		return this.operation;
	}

	public void setOperation(Operation operation) {
		this.operation = operation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NO_ETAT", nullable = false, insertable = false, updatable = false)
	public PrmOtEtat getPrmOtEtat() {
		return this.prmOtEtat;
	}

	public void setPrmOtEtat(PrmOtEtat prmOtEtat) {
		this.prmOtEtat = prmOtEtat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_OT", nullable = false, insertable = false, updatable = false)
	public PrmOtType getPrmOtType() {
		return this.prmOtType;
	}

	public void setPrmOtType(PrmOtType prmOtType) {
		this.prmOtType = prmOtType;
	}

	@Column(name = "TYPE_MOTIF", length = 20)
	public String getTypeMotif() {
		return this.typeMotif;
	}

	public void setTypeMotif(String typeMotif) {
		this.typeMotif = typeMotif;
	}

}
