package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrmOpOtPart generated by hbm2java
 */
@Entity
@Table(name = "PRM_OP_OT_PART", schema = "TOM")
public class PrmOpOtPart implements java.io.Serializable {

	private PrmOpOtPartId id;
	private Operation operation;
	private ParamGen paramGen;
	private Partenaire partenaire;
	private PrmOtType prmOtType;
	private String valeur;

	public PrmOpOtPart() {
	}

	public PrmOpOtPart(PrmOpOtPartId id, Operation operation, ParamGen paramGen, Partenaire partenaire,
			PrmOtType prmOtType, String valeur) {
		this.id = id;
		this.operation = operation;
		this.paramGen = paramGen;
		this.partenaire = partenaire;
		this.prmOtType = prmOtType;
		this.valeur = valeur;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "COp", column = @Column(name = "C_OP", nullable = false, length = 20)),
			@AttributeOverride(name = "CTypeOt", column = @Column(name = "C_TYPE_OT", nullable = false, length = 20)),
			@AttributeOverride(name = "CParam", column = @Column(name = "C_PARAM", nullable = false, length = 50)),
			@AttributeOverride(name = "CPart", column = @Column(name = "C_PART", nullable = false, length = 20)) })
	public PrmOpOtPartId getId() {
		return this.id;
	}

	public void setId(PrmOpOtPartId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_OP", nullable = false, insertable = false, updatable = false)
	public Operation getOperation() {
		return this.operation;
	}

	public void setOperation(Operation operation) {
		this.operation = operation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PARAM", nullable = false, insertable = false, updatable = false)
	public ParamGen getParamGen() {
		return this.paramGen;
	}

	public void setParamGen(ParamGen paramGen) {
		this.paramGen = paramGen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PART", nullable = false, insertable = false, updatable = false)
	public Partenaire getPartenaire() {
		return this.partenaire;
	}

	public void setPartenaire(Partenaire partenaire) {
		this.partenaire = partenaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_OT", nullable = false, insertable = false, updatable = false)
	public PrmOtType getPrmOtType() {
		return this.prmOtType;
	}

	public void setPrmOtType(PrmOtType prmOtType) {
		this.prmOtType = prmOtType;
	}

	@Column(name = "VALEUR", nullable = false, length = 100)
	public String getValeur() {
		return this.valeur;
	}

	public void setValeur(String valeur) {
		this.valeur = valeur;
	}

}
