package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrmParcEtat generated by hbm2java
 */
@Entity
@Table(name = "PRM_PARC_ETAT", schema = "TOM")
public class PrmParcEtat implements java.io.Serializable {

	private short noEtat;
	private String etat;
	private Set<ParcSuivi> parcSuivis = new HashSet<ParcSuivi>(0);
	private Set<ParcServ> parcServs = new HashSet<ParcServ>(0);
	private Set<ParcServSuivi> parcServSuivis = new HashSet<ParcServSuivi>(0);
	private Set<Parc> parcs = new HashSet<Parc>(0);

	public PrmParcEtat() {
	}

	public PrmParcEtat(short noEtat, String etat) {
		this.noEtat = noEtat;
		this.etat = etat;
	}

	public PrmParcEtat(short noEtat, String etat, Set<ParcSuivi> parcSuivis, Set<ParcServ> parcServs,
			Set<ParcServSuivi> parcServSuivis, Set<Parc> parcs) {
		this.noEtat = noEtat;
		this.etat = etat;
		this.parcSuivis = parcSuivis;
		this.parcServs = parcServs;
		this.parcServSuivis = parcServSuivis;
		this.parcs = parcs;
	}

	@Id

	@Column(name = "NO_ETAT", unique = true, nullable = false, precision = 3, scale = 0)
	public short getNoEtat() {
		return this.noEtat;
	}

	public void setNoEtat(short noEtat) {
		this.noEtat = noEtat;
	}

	@Column(name = "ETAT", nullable = false, length = 100)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmParcEtat")
	public Set<ParcSuivi> getParcSuivis() {
		return this.parcSuivis;
	}

	public void setParcSuivis(Set<ParcSuivi> parcSuivis) {
		this.parcSuivis = parcSuivis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmParcEtat")
	public Set<ParcServ> getParcServs() {
		return this.parcServs;
	}

	public void setParcServs(Set<ParcServ> parcServs) {
		this.parcServs = parcServs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmParcEtat")
	public Set<ParcServSuivi> getParcServSuivis() {
		return this.parcServSuivis;
	}

	public void setParcServSuivis(Set<ParcServSuivi> parcServSuivis) {
		this.parcServSuivis = parcServSuivis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmParcEtat")
	public Set<Parc> getParcs() {
		return this.parcs;
	}

	public void setParcs(Set<Parc> parcs) {
		this.parcs = parcs;
	}

}
