package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrmTypeServ generated by hbm2java
 */
@Entity
@Table(name = "PRM_TYPE_SERV", schema = "TOM")
public class PrmTypeServ implements java.io.Serializable {

	private String CTypeServ;
	private String typeServ;
	private Set<ParcServ> parcServs = new HashSet<ParcServ>(0);
	private Set<Operation> operations = new HashSet<Operation>(0);

	public PrmTypeServ() {
	}

	public PrmTypeServ(String CTypeServ, String typeServ) {
		this.CTypeServ = CTypeServ;
		this.typeServ = typeServ;
	}

	public PrmTypeServ(String CTypeServ, String typeServ, Set<ParcServ> parcServs, Set<Operation> operations) {
		this.CTypeServ = CTypeServ;
		this.typeServ = typeServ;
		this.parcServs = parcServs;
		this.operations = operations;
	}

	@Id

	@Column(name = "C_TYPE_SERV", unique = true, nullable = false, length = 20)
	public String getCTypeServ() {
		return this.CTypeServ;
	}

	public void setCTypeServ(String CTypeServ) {
		this.CTypeServ = CTypeServ;
	}

	@Column(name = "TYPE_SERV", nullable = false, length = 100)
	public String getTypeServ() {
		return this.typeServ;
	}

	public void setTypeServ(String typeServ) {
		this.typeServ = typeServ;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prmTypeServ")
	public Set<ParcServ> getParcServs() {
		return this.parcServs;
	}

	public void setParcServs(Set<ParcServ> parcServs) {
		this.parcServs = parcServs;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "prmTypeServs")
	public Set<Operation> getOperations() {
		return this.operations;
	}

	public void setOperations(Set<Operation> operations) {
		this.operations = operations;
	}

}
