package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrmTypeOtPropId generated by hbm2java
 */
@Embeddable
public class PrmTypeOtPropId implements java.io.Serializable {

	private String CTypeOt;
	private String CProp;

	public PrmTypeOtPropId() {
	}

	public PrmTypeOtPropId(String CTypeOt, String CProp) {
		this.CTypeOt = CTypeOt;
		this.CProp = CProp;
	}

	@Column(name = "C_TYPE_OT", nullable = false, length = 20)
	public String getCTypeOt() {
		return this.CTypeOt;
	}

	public void setCTypeOt(String CTypeOt) {
		this.CTypeOt = CTypeOt;
	}

	@Column(name = "C_PROP", nullable = false, length = 50)
	public String getCProp() {
		return this.CProp;
	}

	public void setCProp(String CProp) {
		this.CProp = CProp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrmTypeOtPropId))
			return false;
		PrmTypeOtPropId castOther = (PrmTypeOtPropId) other;

		return ((this.getCTypeOt() == castOther.getCTypeOt()) || (this.getCTypeOt() != null
				&& castOther.getCTypeOt() != null && this.getCTypeOt().equals(castOther.getCTypeOt())))
				&& ((this.getCProp() == castOther.getCProp()) || (this.getCProp() != null
						&& castOther.getCProp() != null && this.getCProp().equals(castOther.getCProp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCTypeOt() == null ? 0 : this.getCTypeOt().hashCode());
		result = 37 * result + (getCProp() == null ? 0 : this.getCProp().hashCode());
		return result;
	}

}
