package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrmTypeOtOpId generated by hbm2java
 */
@Embeddable
public class PrmTypeOtOpId implements java.io.Serializable {

	private String COp;
	private String CTypeOt;

	public PrmTypeOtOpId() {
	}

	public PrmTypeOtOpId(String COp, String CTypeOt) {
		this.COp = COp;
		this.CTypeOt = CTypeOt;
	}

	@Column(name = "C_OP", nullable = false, length = 20)
	public String getCOp() {
		return this.COp;
	}

	public void setCOp(String COp) {
		this.COp = COp;
	}

	@Column(name = "C_TYPE_OT", nullable = false, length = 20)
	public String getCTypeOt() {
		return this.CTypeOt;
	}

	public void setCTypeOt(String CTypeOt) {
		this.CTypeOt = CTypeOt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrmTypeOtOpId))
			return false;
		PrmTypeOtOpId castOther = (PrmTypeOtOpId) other;

		return ((this.getCOp() == castOther.getCOp())
				|| (this.getCOp() != null && castOther.getCOp() != null && this.getCOp().equals(castOther.getCOp())))
				&& ((this.getCTypeOt() == castOther.getCTypeOt()) || (this.getCTypeOt() != null
						&& castOther.getCTypeOt() != null && this.getCTypeOt().equals(castOther.getCTypeOt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCOp() == null ? 0 : this.getCOp().hashCode());
		result = 37 * result + (getCTypeOt() == null ? 0 : this.getCTypeOt().hashCode());
		return result;
	}

}
