package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrmTypeServOp generated by hbm2java
 */
@Entity
@Table(name = "PRM_TYPE_SERV_OP", schema = "TOM")
public class PrmTypeServOp implements java.io.Serializable {

	private PrmTypeServOpId id;

	public PrmTypeServOp() {
	}

	public PrmTypeServOp(PrmTypeServOpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "COp", column = @Column(name = "C_OP", nullable = false, length = 20)),
			@AttributeOverride(name = "CTypeServ", column = @Column(name = "C_TYPE_SERV", nullable = false, length = 20)) })
	public PrmTypeServOpId getId() {
		return this.id;
	}

	public void setId(PrmTypeServOpId id) {
		this.id = id;
	}

}
