package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrmTypeOtProp generated by hbm2java
 */
@Entity
@Table(name = "PRM_TYPE_OT_PROP", schema = "TOM")
public class PrmTypeOtProp implements java.io.Serializable {

	private PrmTypeOtPropId id;
	private PrmOtType prmOtType;
	private Propriete propriete;
	private boolean FModif;
	private boolean FObligatoire;
	private short ordre;

	public PrmTypeOtProp() {
	}

	public PrmTypeOtProp(PrmTypeOtPropId id, PrmOtType prmOtType, Propriete propriete, boolean FModif,
			boolean FObligatoire, short ordre) {
		this.id = id;
		this.prmOtType = prmOtType;
		this.propriete = propriete;
		this.FModif = FModif;
		this.FObligatoire = FObligatoire;
		this.ordre = ordre;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "CTypeOt", column = @Column(name = "C_TYPE_OT", nullable = false, length = 20)),
			@AttributeOverride(name = "CProp", column = @Column(name = "C_PROP", nullable = false, length = 50)) })
	public PrmTypeOtPropId getId() {
		return this.id;
	}

	public void setId(PrmTypeOtPropId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_OT", nullable = false, insertable = false, updatable = false)
	public PrmOtType getPrmOtType() {
		return this.prmOtType;
	}

	public void setPrmOtType(PrmOtType prmOtType) {
		this.prmOtType = prmOtType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_PROP", nullable = false, insertable = false, updatable = false)
	public Propriete getPropriete() {
		return this.propriete;
	}

	public void setPropriete(Propriete propriete) {
		this.propriete = propriete;
	}

	@Column(name = "F_MODIF", nullable = false, precision = 1, scale = 0)
	public boolean isFModif() {
		return this.FModif;
	}

	public void setFModif(boolean FModif) {
		this.FModif = FModif;
	}

	@Column(name = "F_OBLIGATOIRE", nullable = false, precision = 1, scale = 0)
	public boolean isFObligatoire() {
		return this.FObligatoire;
	}

	public void setFObligatoire(boolean FObligatoire) {
		this.FObligatoire = FObligatoire;
	}

	@Column(name = "ORDRE", nullable = false, precision = 3, scale = 0)
	public short getOrdre() {
		return this.ordre;
	}

	public void setOrdre(short ordre) {
		this.ordre = ordre;
	}

}
