package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrmTypeOtOp generated by hbm2java
 */
@Entity
@Table(name = "PRM_TYPE_OT_OP", schema = "TOM")
public class PrmTypeOtOp implements java.io.Serializable {

	private PrmTypeOtOpId id;

	public PrmTypeOtOp() {
	}

	public PrmTypeOtOp(PrmTypeOtOpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "COp", column = @Column(name = "C_OP", nullable = false, length = 20)),
			@AttributeOverride(name = "CTypeOt", column = @Column(name = "C_TYPE_OT", nullable = false, length = 20)) })
	public PrmTypeOtOpId getId() {
		return this.id;
	}

	public void setId(PrmTypeOtOpId id) {
		this.id = id;
	}

}
