package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrmTypeServOpId generated by hbm2java
 */
@Embeddable
public class PrmTypeServOpId implements java.io.Serializable {

	private String COp;
	private String CTypeServ;

	public PrmTypeServOpId() {
	}

	public PrmTypeServOpId(String COp, String CTypeServ) {
		this.COp = COp;
		this.CTypeServ = CTypeServ;
	}

	@Column(name = "C_OP", nullable = false, length = 20)
	public String getCOp() {
		return this.COp;
	}

	public void setCOp(String COp) {
		this.COp = COp;
	}

	@Column(name = "C_TYPE_SERV", nullable = false, length = 20)
	public String getCTypeServ() {
		return this.CTypeServ;
	}

	public void setCTypeServ(String CTypeServ) {
		this.CTypeServ = CTypeServ;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrmTypeServOpId))
			return false;
		PrmTypeServOpId castOther = (PrmTypeServOpId) other;

		return ((this.getCOp() == castOther.getCOp())
				|| (this.getCOp() != null && castOther.getCOp() != null && this.getCOp().equals(castOther.getCOp())))
				&& ((this.getCTypeServ() == castOther.getCTypeServ()) || (this.getCTypeServ() != null
						&& castOther.getCTypeServ() != null && this.getCTypeServ().equals(castOther.getCTypeServ())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCOp() == null ? 0 : this.getCOp().hashCode());
		result = 37 * result + (getCTypeServ() == null ? 0 : this.getCTypeServ().hashCode());
		return result;
	}

}
