package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProfilType generated by hbm2java
 */
@Entity
@Table(name = "PROFIL_TYPE", schema = "TOM")
public class ProfilType implements java.io.Serializable {

	private String CTypeProfil;
	private UniteType uniteType;
	private String typeProfil;
	private boolean FCentral;
	private Set<FonctionProftype> fonctionProftypes = new HashSet<FonctionProftype>(0);
	private Set<Profil> profils = new HashSet<Profil>(0);

	public ProfilType() {
	}

	public ProfilType(String CTypeProfil, String typeProfil, boolean FCentral) {
		this.CTypeProfil = CTypeProfil;
		this.typeProfil = typeProfil;
		this.FCentral = FCentral;
	}

	public ProfilType(String CTypeProfil, UniteType uniteType, String typeProfil, boolean FCentral,
			Set<FonctionProftype> fonctionProftypes, Set<Profil> profils) {
		this.CTypeProfil = CTypeProfil;
		this.uniteType = uniteType;
		this.typeProfil = typeProfil;
		this.FCentral = FCentral;
		this.fonctionProftypes = fonctionProftypes;
		this.profils = profils;
	}

	@Id

	@Column(name = "C_TYPE_PROFIL", unique = true, nullable = false, length = 20)
	public String getCTypeProfil() {
		return this.CTypeProfil;
	}

	public void setCTypeProfil(String CTypeProfil) {
		this.CTypeProfil = CTypeProfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_UNITE")
	public UniteType getUniteType() {
		return this.uniteType;
	}

	public void setUniteType(UniteType uniteType) {
		this.uniteType = uniteType;
	}

	@Column(name = "TYPE_PROFIL", nullable = false, length = 100)
	public String getTypeProfil() {
		return this.typeProfil;
	}

	public void setTypeProfil(String typeProfil) {
		this.typeProfil = typeProfil;
	}

	@Column(name = "F_CENTRAL", nullable = false, precision = 1, scale = 0)
	public boolean isFCentral() {
		return this.FCentral;
	}

	public void setFCentral(boolean FCentral) {
		this.FCentral = FCentral;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profilType")
	public Set<FonctionProftype> getFonctionProftypes() {
		return this.fonctionProftypes;
	}

	public void setFonctionProftypes(Set<FonctionProftype> fonctionProftypes) {
		this.fonctionProftypes = fonctionProftypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profilType")
	public Set<Profil> getProfils() {
		return this.profils;
	}

	public void setProfils(Set<Profil> profils) {
		this.profils = profils;
	}

}
