package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "PROFIL", schema = "TOM")
public class Profil implements java.io.Serializable {

	private BigDecimal idProfil;
	private ProfilType profilType;
	private String profil;
	private String descProfil;
	private boolean FEtat;
	private Date DEtat;
	private String loginEtat;
	private Set<Fonction> fonctions = new HashSet<Fonction>(0);
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Profil() {
	}

	public Profil(BigDecimal idProfil, ProfilType profilType, String profil, boolean FEtat) {
		this.idProfil = idProfil;
		this.profilType = profilType;
		this.profil = profil;
		this.FEtat = FEtat;
	}

	public Profil(BigDecimal idProfil, ProfilType profilType, String profil, String descProfil, boolean FEtat,
			Date DEtat, String loginEtat, Set<Fonction> fonctions, Set<Utilisateur> utilisateurs) {
		this.idProfil = idProfil;
		this.profilType = profilType;
		this.profil = profil;
		this.descProfil = descProfil;
		this.FEtat = FEtat;
		this.DEtat = DEtat;
		this.loginEtat = loginEtat;
		this.fonctions = fonctions;
		this.utilisateurs = utilisateurs;
	}

	@Id

	@Column(name = "ID_PROFIL", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdProfil() {
		return this.idProfil;
	}

	public void setIdProfil(BigDecimal idProfil) {
		this.idProfil = idProfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_TYPE_PROFIL", nullable = false)
	public ProfilType getProfilType() {
		return this.profilType;
	}

	public void setProfilType(ProfilType profilType) {
		this.profilType = profilType;
	}

	@Column(name = "PROFIL", nullable = false, length = 100)
	public String getProfil() {
		return this.profil;
	}

	public void setProfil(String profil) {
		this.profil = profil;
	}

	@Column(name = "DESC_PROFIL", length = 500)
	public String getDescProfil() {
		return this.descProfil;
	}

	public void setDescProfil(String descProfil) {
		this.descProfil = descProfil;
	}

	@Column(name = "F_ETAT", nullable = false, precision = 1, scale = 0)
	public boolean isFEtat() {
		return this.FEtat;
	}

	public void setFEtat(boolean FEtat) {
		this.FEtat = FEtat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ETAT", length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	@Column(name = "LOGIN_ETAT", length = 20)
	public String getLoginEtat() {
		return this.loginEtat;
	}

	public void setLoginEtat(String loginEtat) {
		this.loginEtat = loginEtat;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "DROIT_ACCES", schema = "TOM", joinColumns = {
			@JoinColumn(name = "ID_PROFIL", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "C_FONCTION", nullable = false, updatable = false) })
	public Set<Fonction> getFonctions() {
		return this.fonctions;
	}

	public void setFonctions(Set<Fonction> fonctions) {
		this.fonctions = fonctions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profil")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
