package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "REGION", schema = "TOM")
public class Region implements java.io.Serializable {

	private String CRegion;
	private String region;
	private String CSig;
	private String codeDrt;
	private Set<Dunning> dunnings = new HashSet<Dunning>(0);
	private Set<Demande> demandes = new HashSet<Demande>(0);
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
	private Set<Unite> unites = new HashSet<Unite>(0);
	private Set<Delegation> delegations = new HashSet<Delegation>(0);

	public Region() {
	}

	public Region(String CRegion, String region) {
		this.CRegion = CRegion;
		this.region = region;
	}

	public Region(String CRegion, String region, String CSig, String codeDrt, Set<Dunning> dunnings,
			Set<Demande> demandes, Set<Utilisateur> utilisateurs, Set<Unite> unites, Set<Delegation> delegations) {
		this.CRegion = CRegion;
		this.region = region;
		this.CSig = CSig;
		this.codeDrt = codeDrt;
		this.dunnings = dunnings;
		this.demandes = demandes;
		this.utilisateurs = utilisateurs;
		this.unites = unites;
		this.delegations = delegations;
	}

	@Id

	@Column(name = "C_REGION", unique = true, nullable = false, length = 10)
	public String getCRegion() {
		return this.CRegion;
	}

	public void setCRegion(String CRegion) {
		this.CRegion = CRegion;
	}

	@Column(name = "REGION", nullable = false, length = 100)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "C_SIG", length = 200)
	public String getCSig() {
		return this.CSig;
	}

	public void setCSig(String CSig) {
		this.CSig = CSig;
	}

	@Column(name = "CODE_DRT")
	public String getCodeDrt() {
		return this.codeDrt;
	}

	public void setCodeDrt(String codeDrt) {
		this.codeDrt = codeDrt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Dunning> getDunnings() {
		return this.dunnings;
	}

	public void setDunnings(Set<Dunning> dunnings) {
		this.dunnings = dunnings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Demande> getDemandes() {
		return this.demandes;
	}

	public void setDemandes(Set<Demande> demandes) {
		this.demandes = demandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Unite> getUnites() {
		return this.unites;
	}

	public void setUnites(Set<Unite> unites) {
		this.unites = unites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Delegation> getDelegations() {
		return this.delegations;
	}

	public void setDelegations(Set<Delegation> delegations) {
		this.delegations = delegations;
	}

}
