package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SousProcessus generated by hbm2java
 */
@Entity
@Table(name = "SOUS_PROCESSUS", schema = "TOM")
public class SousProcessus implements java.io.Serializable {

	private SousProcessusId id;
	private Operation operation;
	private String libProcess;
	private String idProcess;

	public SousProcessus() {
	}

	public SousProcessus(SousProcessusId id, Operation operation, String idProcess) {
		this.id = id;
		this.operation = operation;
		this.idProcess = idProcess;
	}

	public SousProcessus(SousProcessusId id, Operation operation, String libProcess, String idProcess) {
		this.id = id;
		this.operation = operation;
		this.libProcess = libProcess;
		this.idProcess = idProcess;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "COp", column = @Column(name = "C_OP", nullable = false, length = 20)),
			@AttributeOverride(name = "CProcess", column = @Column(name = "C_PROCESS", nullable = false, length = 100)) })
	public SousProcessusId getId() {
		return this.id;
	}

	public void setId(SousProcessusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_OP", nullable = false, insertable = false, updatable = false)
	public Operation getOperation() {
		return this.operation;
	}

	public void setOperation(Operation operation) {
		this.operation = operation;
	}

	@Column(name = "LIB_PROCESS", length = 100)
	public String getLibProcess() {
		return this.libProcess;
	}

	public void setLibProcess(String libProcess) {
		this.libProcess = libProcess;
	}

	@Column(name = "ID_PROCESS", nullable = false, length = 100)
	public String getIdProcess() {
		return this.idProcess;
	}

	public void setIdProcess(String idProcess) {
		this.idProcess = idProcess;
	}

}
