package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SousProcessusId generated by hbm2java
 */
@Embeddable
public class SousProcessusId implements java.io.Serializable {

	private String COp;
	private String CProcess;

	public SousProcessusId() {
	}

	public SousProcessusId(String COp, String CProcess) {
		this.COp = COp;
		this.CProcess = CProcess;
	}

	@Column(name = "C_OP", nullable = false, length = 20)
	public String getCOp() {
		return this.COp;
	}

	public void setCOp(String COp) {
		this.COp = COp;
	}

	@Column(name = "C_PROCESS", nullable = false, length = 100)
	public String getCProcess() {
		return this.CProcess;
	}

	public void setCProcess(String CProcess) {
		this.CProcess = CProcess;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SousProcessusId))
			return false;
		SousProcessusId castOther = (SousProcessusId) other;

		return ((this.getCOp() == castOther.getCOp())
				|| (this.getCOp() != null && castOther.getCOp() != null && this.getCOp().equals(castOther.getCOp())))
				&& ((this.getCProcess() == castOther.getCProcess()) || (this.getCProcess() != null
						&& castOther.getCProcess() != null && this.getCProcess().equals(castOther.getCProcess())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCOp() == null ? 0 : this.getCOp().hashCode());
		result = 37 * result + (getCProcess() == null ? 0 : this.getCProcess().hashCode());
		return result;
	}

}
