package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemActionOld generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_ACTION_OLD", schema = "TOM")
public class SystemActionOld implements java.io.Serializable {

	private BigDecimal idAction;
	private Date dateAction;
	private String sqlAction;
	private String userAction;
	private String ipAction;
	private String machineAction;
	private String programAction;
	private String sidAction;
	private Clob remark;

	public SystemActionOld() {
	}

	public SystemActionOld(BigDecimal idAction) {
		this.idAction = idAction;
	}

	public SystemActionOld(BigDecimal idAction, Date dateAction, String sqlAction, String userAction, String ipAction,
			String machineAction, String programAction, String sidAction, Clob remark) {
		this.idAction = idAction;
		this.dateAction = dateAction;
		this.sqlAction = sqlAction;
		this.userAction = userAction;
		this.ipAction = ipAction;
		this.machineAction = machineAction;
		this.programAction = programAction;
		this.sidAction = sidAction;
		this.remark = remark;
	}

	@Id

	@Column(name = "ID_ACTION", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdAction() {
		return this.idAction;
	}

	public void setIdAction(BigDecimal idAction) {
		this.idAction = idAction;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ACTION", length = 7)
	public Date getDateAction() {
		return this.dateAction;
	}

	public void setDateAction(Date dateAction) {
		this.dateAction = dateAction;
	}

	@Column(name = "SQL_ACTION", length = 500)
	public String getSqlAction() {
		return this.sqlAction;
	}

	public void setSqlAction(String sqlAction) {
		this.sqlAction = sqlAction;
	}

	@Column(name = "USER_ACTION", length = 100)
	public String getUserAction() {
		return this.userAction;
	}

	public void setUserAction(String userAction) {
		this.userAction = userAction;
	}

	@Column(name = "IP_ACTION", length = 100)
	public String getIpAction() {
		return this.ipAction;
	}

	public void setIpAction(String ipAction) {
		this.ipAction = ipAction;
	}

	@Column(name = "MACHINE_ACTION", length = 100)
	public String getMachineAction() {
		return this.machineAction;
	}

	public void setMachineAction(String machineAction) {
		this.machineAction = machineAction;
	}

	@Column(name = "PROGRAM_ACTION", length = 100)
	public String getProgramAction() {
		return this.programAction;
	}

	public void setProgramAction(String programAction) {
		this.programAction = programAction;
	}

	@Column(name = "SID_ACTION", length = 5)
	public String getSidAction() {
		return this.sidAction;
	}

	public void setSidAction(String sidAction) {
		this.sidAction = sidAction;
	}

	@Column(name = "REMARK")
	public Clob getRemark() {
		return this.remark;
	}

	public void setRemark(Clob remark) {
		this.remark = remark;
	}

}
