package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UniteMigId generated by hbm2java
 */
@Embeddable
public class UniteMigId implements java.io.Serializable {

	private String CUnite;
	private String unite;
	private String CUniteSig;

	public UniteMigId() {
	}

	public UniteMigId(String CUnite, String unite, String CUniteSig) {
		this.CUnite = CUnite;
		this.unite = unite;
		this.CUniteSig = CUniteSig;
	}

	@Column(name = "C_UNITE", length = 20)
	public String getCUnite() {
		return this.CUnite;
	}

	public void setCUnite(String CUnite) {
		this.CUnite = CUnite;
	}

	@Column(name = "UNITE", length = 100)
	public String getUnite() {
		return this.unite;
	}

	public void setUnite(String unite) {
		this.unite = unite;
	}

	@Column(name = "C_UNITE_SIG", length = 20)
	public String getCUniteSig() {
		return this.CUniteSig;
	}

	public void setCUniteSig(String CUniteSig) {
		this.CUniteSig = CUniteSig;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UniteMigId))
			return false;
		UniteMigId castOther = (UniteMigId) other;

		return ((this.getCUnite() == castOther.getCUnite()) || (this.getCUnite() != null
				&& castOther.getCUnite() != null && this.getCUnite().equals(castOther.getCUnite())))
				&& ((this.getUnite() == castOther.getUnite()) || (this.getUnite() != null
						&& castOther.getUnite() != null && this.getUnite().equals(castOther.getUnite())))
				&& ((this.getCUniteSig() == castOther.getCUniteSig()) || (this.getCUniteSig() != null
						&& castOther.getCUniteSig() != null && this.getCUniteSig().equals(castOther.getCUniteSig())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCUnite() == null ? 0 : this.getCUnite().hashCode());
		result = 37 * result + (getUnite() == null ? 0 : this.getUnite().hashCode());
		result = 37 * result + (getCUniteSig() == null ? 0 : this.getCUniteSig().hashCode());
		return result;
	}

}
