package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:52:19 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UniteLocaliteId generated by hbm2java
 */
@Embeddable
public class UniteLocaliteId implements java.io.Serializable {

	private String CLoc;
	private String CUnite;

	public UniteLocaliteId() {
	}

	public UniteLocaliteId(String CLoc, String CUnite) {
		this.CLoc = CLoc;
		this.CUnite = CUnite;
	}

	@Column(name = "C_LOC", nullable = false, length = 10)
	public String getCLoc() {
		return this.CLoc;
	}

	public void setCLoc(String CLoc) {
		this.CLoc = CLoc;
	}

	@Column(name = "C_UNITE", nullable = false, length = 20)
	public String getCUnite() {
		return this.CUnite;
	}

	public void setCUnite(String CUnite) {
		this.CUnite = CUnite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UniteLocaliteId))
			return false;
		UniteLocaliteId castOther = (UniteLocaliteId) other;

		return ((this.getCLoc() == castOther.getCLoc()) || (this.getCLoc() != null && castOther.getCLoc() != null
				&& this.getCLoc().equals(castOther.getCLoc())))
				&& ((this.getCUnite() == castOther.getCUnite()) || (this.getCUnite() != null
						&& castOther.getCUnite() != null && this.getCUnite().equals(castOther.getCUnite())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCLoc() == null ? 0 : this.getCLoc().hashCode());
		result = 37 * result + (getCUnite() == null ? 0 : this.getCUnite().hashCode());
		return result;
	}

}
