package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UniteMig generated by hbm2java
 */
@Entity
@Table(name = "UNITE_MIG", schema = "TOM")
public class UniteMig implements java.io.Serializable {

	private UniteMigId id;

	public UniteMig() {
	}

	public UniteMig(UniteMigId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "CUnite", column = @Column(name = "C_UNITE", length = 20)),
			@AttributeOverride(name = "unite", column = @Column(name = "UNITE", length = 100)),
			@AttributeOverride(name = "CUniteSig", column = @Column(name = "C_UNITE_SIG", length = 20)) })
	public UniteMigId getId() {
		return this.id;
	}

	public void setId(UniteMigId id) {
		this.id = id;
	}

}
