package com.tn.itserv.tom.entities;
// Generated 13 mai 2020 � 05:42:52 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR", schema = "TOM")
public class Utilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String login;
	private Profil profil;
	private Region region;
	private Unite unite;
	private String motPasse;
	private boolean FAd;
	private String emplacementAd;
	private String matricule;
	private String nom;
	private String prenom;
	private String email;
	private String tel;
	private boolean FEtat;
	private Date DEtat;
	private Date DSynchroAd;
	private Date DConOff;
	private Set<Equipe> equipes = new HashSet<Equipe>(0);

	public Utilisateur() {
	}

	public Utilisateur(String login, Profil profil, String motPasse, boolean FAd, String nom, String prenom,
			boolean FEtat) {
		this.login = login;
		this.profil = profil;
		this.motPasse = motPasse;
		this.FAd = FAd;
		this.nom = nom;
		this.prenom = prenom;
		this.FEtat = FEtat;
	}

	public Utilisateur(String login, Profil profil, Region region, Unite unite, String motPasse, boolean FAd,
			String emplacementAd, String matricule, String nom, String prenom, String email, String tel, boolean FEtat,
			Date DEtat, Date DSynchroAd, Date DConOff, Set<Equipe> equipes) {
		this.login = login;
		this.profil = profil;
		this.region = region;
		this.unite = unite;
		this.motPasse = motPasse;
		this.FAd = FAd;
		this.emplacementAd = emplacementAd;
		this.matricule = matricule;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.tel = tel;
		this.FEtat = FEtat;
		this.DEtat = DEtat;
		this.DSynchroAd = DSynchroAd;
		this.DConOff = DConOff;
		this.equipes = equipes;
	}

	@Id

	@Column(name = "LOGIN", unique = true, nullable = false, length = 20)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROFIL", nullable = false)
	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_REGION")
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "C_UNITE")
	public Unite getUnite() {
		return this.unite;
	}

	public void setUnite(Unite unite) {
		this.unite = unite;
	}

	@Column(name = "MOT_PASSE", nullable = false, length = 200)
	public String getMotPasse() {
		return this.motPasse;
	}

	public void setMotPasse(String motPasse) {
		this.motPasse = motPasse;
	}

	@Column(name = "F_AD", nullable = false, precision = 1, scale = 0)
	public boolean isFAd() {
		return this.FAd;
	}

	public void setFAd(boolean FAd) {
		this.FAd = FAd;
	}

	@Column(name = "EMPLACEMENT_AD", length = 100)
	public String getEmplacementAd() {
		return this.emplacementAd;
	}

	public void setEmplacementAd(String emplacementAd) {
		this.emplacementAd = emplacementAd;
	}

	@Column(name = "MATRICULE", length = 10)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "NOM", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TEL", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "F_ETAT", nullable = false, precision = 1, scale = 0)
	public boolean isFEtat() {
		return this.FEtat;
	}

	public void setFEtat(boolean FEtat) {
		this.FEtat = FEtat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_ETAT", length = 11)
	public Date getDEtat() {
		return this.DEtat;
	}

	public void setDEtat(Date DEtat) {
		this.DEtat = DEtat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_SYNCHRO_AD", length = 11)
	public Date getDSynchroAd() {
		return this.DSynchroAd;
	}

	public void setDSynchroAd(Date DSynchroAd) {
		this.DSynchroAd = DSynchroAd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "D_CON_OFF", length = 11)
	public Date getDConOff() {
		return this.DConOff;
	}

	public void setDConOff(Date DConOff) {
		this.DConOff = DConOff;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "utilisateurs")
	public Set<Equipe> getEquipes() {
		return this.equipes;
	}

	public void setEquipes(Set<Equipe> equipes) {
		this.equipes = equipes;
	}

}
